import test from 'node:test'
import assert from 'node:assert/strict'
import { mkdtemp, readFile, writeFile } from 'node:fs/promises'
import os from 'node:os'; import path from 'node:path'
import { createProposal, discoverHoloself, getContext, reviewProposal, runHoloself, sanitizePublicProvenance, searchContext, showProposal } from './adapter.js'

async function fake(body) { const dir=await mkdtemp(path.join(os.tmpdir(),'hs-test-')); const file=path.join(dir,'fake.mjs'); await writeFile(file,body); return {dir,file,env:{...process.env,HOLOSELF_EXECUTABLE:file}} }
const validContext={lens:'career',validation:{status:'valid'},warnings:[],self:{documents:[{path:'profile/identity.md',content:'Career content token=abcdefghijklmnop',metadata:{access_lenses:['career'],disclosure:'internal'}},{path:'context/compensation.md',content:'never show',metadata:{access_lenses:['career']}}]}}

test('executes fixed argv with shell-free JS executable and redacts/filter context',async()=>{ const f=await fake(`console.log(JSON.stringify(${JSON.stringify(validContext)}))`); const out=await getContext(a=>runHoloself(a,{env:f.env})); assert.equal(out.documents.length,1); assert.doesNotMatch(out.documents[0].content,/abcdefghijklmnop/); assert.equal((await discoverHoloself(f.env)).command,process.execPath) })
test('search uses positional query and filters compensation',async()=>{ const calls=[]; const results=await searchContext('leadership',async a=>{calls.push(a);return JSON.stringify({results:[{source_file:'profile/identity.md',matching_passage:'ok',access_lenses:['career']},{source_file:'compensation.md',matching_passage:'private',access_lenses:['career']}]})}); assert.deepEqual(calls[0],['search','leadership','--project',calls[0][3],'--json']); assert.equal(results.length,1) })
test('career lens requires an explicit exact permission for every supported shape',async()=>{const shapes=[undefined,null,'career',{other:true},[],{career:false},['career'],{career:true}];const documents=shapes.map((access_lenses,i)=>({path:`profile/doc-${i}.md`,content:`doc ${i}`,metadata:{access_lenses}}));documents.push({path:'profile/compensation-private.md',content:'secret',metadata:{access_lenses:['career']}});for(const status of ['valid','passed']){const out=await getContext(async()=>JSON.stringify({lens:'career',validation:{status},self:{documents}}));assert.deepEqual(out.documents.map(x=>x.content),['doc 6','doc 7'])}await assert.rejects(()=>getContext(async()=>JSON.stringify({lens:'career',validation:{status:'unknown'},self:{documents}})),/explicitly permitted/)})
test('search career predicate rejects missing null string malformed empty and false lenses',async()=>{const shapes=[undefined,null,'career',{other:true},[],{career:false},['career'],{career:true}];const results=shapes.map((access_lenses,i)=>({source_file:`profile/result-${i}.md`,matching_passage:`result ${i}`,access_lenses}));results.push({source_file:'private/compensation.md',matching_passage:'secret',access_lenses:{career:true}});const out=await searchContext('career',async()=>JSON.stringify({results}));assert.deepEqual(out.map(x=>x.passage),['result 6','result 7'])})
test('fails closed on malformed output, unavailable CLI, timeout and output cap',async()=>{ await assert.rejects(()=>getContext(async()=>'{bad'),/malformed/); await assert.rejects(()=>discoverHoloself({...process.env,HOLOSELF_EXECUTABLE:path.join(os.tmpdir(),'missing.mjs')}),/unavailable/); const slow=await fake('setTimeout(()=>console.log("{}"),1000)'); await assert.rejects(()=>runHoloself([],{env:slow.env,timeout:20}),/timed out/); const loud=await fake('console.log("x".repeat(1000))'); await assert.rejects(()=>runHoloself([],{env:loud.env,outputCap:20}),/safe limit/) })
test('rejects unsafe wrapper, IDs, claims and confirmation',async()=>{ const d=await mkdtemp(path.join(os.tmpdir(),'hs-test-')); const cmd=path.join(d,'h.cmd'); await writeFile(cmd,'echo unsafe'); await assert.rejects(()=>discoverHoloself({...process.env,HOLOSELF_EXECUTABLE:cmd},'win32'),/Unsafe/); await assert.rejects(()=>showProposal('../x',async()=>''),/Exact proposal ID/); await assert.rejects(()=>createProposal('x'.repeat(2001),async()=>''),/1-2000/); const id='088e2571-8562-4644-9000-03e9f2e01f9a'; await assert.rejects(()=>reviewProposal(id,'approve','yes',async()=>''),/confirmation/) })
test('proposal create only writes bounded transient source and passes fixed args',async()=>{ let args,source,contents; await createProposal('Reviewed claim',async a=>{args=a; source=a.at(-1); contents=await readFile(source,'utf8'); return 'ok'}); assert.equal(contents,'Reviewed claim'); assert.deepEqual(args.slice(0,4),['propose','--project',args[2],'--claim']); await assert.rejects(()=>readFile(source),/ENOENT/) })
test('show requires matching exact proposal output',async()=>{ const id='088e2571-8562-4644-9000-03e9f2e01f9a'; const p=await showProposal(id,async a=>{assert.deepEqual(a.slice(0,3),['proposals','show',id]); return `proposal_id: ${id}\nclaim: safe\nstatus: pending\n`}); assert.equal(p.id,id); await assert.rejects(()=>showProposal(id,async()=>`proposal_id: 251732fa-0307-47b4-b6aa-b36fa2530ad5`),/match/) })
test('recursive public provenance strips absolute paths and internal file keys while preserving labels links and versions',()=>{const value={label:'Career identity',source:{file_path:'C:\\private\\identity.md',nested:[{source_file:'/home/me/private.md',wikilink:'[[Career Identity]]',version:'v3'}]},provenance:['/secret/root.md','safe-label']};const out=sanitizePublicProvenance(value),raw=JSON.stringify(out);assert.doesNotMatch(raw,/C:\\\\|\/home\/|\/secret\/|file_path|source_file/);assert.match(raw,/Career identity/);assert.match(raw,/\[\[Career Identity\]\]/);assert.match(raw,/v3/)})
test('review uses fixed action argv then refreshes career context',async()=>{ const id='088e2571-8562-4644-9000-03e9f2e01f9a',calls=[]; const result=await reviewProposal(id,'defer',`DEFER:${id}`,async a=>{calls.push(a); return a[0]==='context'?JSON.stringify(validContext):'ok'}); assert.deepEqual(calls[0],['proposals','defer',id,'--project',calls[0][4],'--yes']); assert.equal(result.context.health.lens,'career') })
