import { useEffect, useRef, useState } from 'react'
import { api } from '../api/client.js'

const terminal = new Set(['completed','failed','cancelled','timed_out'])
function List({ title, values }) { return <section><h3>{title}</h3><ul>{values.map(value=><li key={value}>{value}</li>)}</ul></section> }

export default function Actions() {
  const [caps,setCaps]=useState(null), [slug,setSlug]=useState(''), [run,setRun]=useState(null), [error,setError]=useState(''), [status,setStatus]=useState('to_apply'), [preview,setPreview]=useState(null), [override,setOverride]=useState('')
  const dialogRef=useRef(null), runButtonRef=useRef(null), openerRef=useRef(null)
  useEffect(()=>{ api.getActionCapabilities().then(setCaps).catch(e=>setError(e.message)) },[])
  useEffect(()=>{ if(preview){ dialogRef.current?.showModal(); runButtonRef.current?.focus() } },[preview])
  const closePreview=()=>{ dialogRef.current?.close(); setPreview(null); openerRef.current?.focus() }
  const showPreview=(action,event)=>{ openerRef.current=event.currentTarget; setPreview(action) }
  const execute=async()=>{ const action=preview; closePreview(); try { setError(''); const next=await api.startAction(action.id,slug,override||undefined); setRun(next); const source=new EventSource(`/api/actions/runs/${next.id}/events`); for(const event of ['snapshot','queued','running','output','completed','failed','cancelled','timed_out']) source.addEventListener(event,e=>{ const value=JSON.parse(e.data); setRun(value); if(terminal.has(value.state)) source.close() }) } catch(e){setError(e.message)} }
  const mutate=async()=>{ if(!slug) return setError('Enter an application slug.'); if(!confirm(`Change ${slug} status to ${status}? This updates metadata.md and appends an audit entry.`)) return; try { await api.updateApplicationStatus(slug,status); setError(''); alert('Status updated.') } catch(e){setError(e.message)} }
  return <div className="page-stack"><header className="page-heading"><p className="eyebrow">Action center</p><h1>Run trusted workflows</h1><p>Only fixed, allowlisted actions are available. No terminal or arbitrary command input is exposed.</p></header>{error&&<p className="error-state">{error}</p>}{caps&&<><section className="card"><strong>Selected harness: {caps.selectedHarness}</strong><label> Per-run override <select value={override} onChange={e=>setOverride(e.target.value)}><option value="">Use selected ({caps.selectedHarness})</option>{caps.harnesses.map(h=><option key={h.id} value={h.id} disabled={!h.available}>{h.label}{h.available?'':' (unavailable)'}</option>)}</select></label><p>Overrides apply to this run only and do not change Settings.</p></section><label>Application slug <input value={slug} onChange={e=>setSlug(e.target.value)} placeholder="company-role" /></label><section className="card-grid">{caps.actions.map(a=><article className="card" key={a.id}><h2>{a.label}</h2><p>Skill: {a.skill}</p><p>{a.requiresSlug?'Requires an application slug.':'No application prerequisite.'}</p><button disabled={!a.available} onClick={event=>showPreview(a,event)}>Preview</button>{!a.available&&<small>{a.unavailableReason}</small>}</article>)}</section><section className="card"><h2>Update application status</h2><p>{caps.mutation.available?'Uses coordination lock, atomic rename, audit append, and index invalidation.':caps.mutation.reason}</p><select value={status} onChange={e=>setStatus(e.target.value)} disabled={!caps.mutation.available}>{['identified','to_apply','applied','recruiter_screen','interview','offer','rejected','withdrawn','archived'].map(x=><option key={x}>{x}</option>)}</select> <button disabled={!caps.mutation.available} onClick={mutate}>Confirm status change</button></section></>}{run&&<section className="card"><h2>Run result</h2><p>Status: {run.state} {run.truncated&&'(output capped)'}</p>{['queued','running'].includes(run.state)&&<button onClick={()=>api.cancelAction(run.id)}>Cancel</button>}<pre>{run.output}</pre></section>}
  <dialog ref={dialogRef} className="action-dialog" aria-labelledby="action-preview-title" onCancel={event=>{event.preventDefault();closePreview()}}>{preview&&<><h2 id="action-preview-title">Preview: {preview.label}</h2><p><strong>Harness:</strong> {override||caps?.selectedHarness}. <strong>Mode:</strong> {preview.mutability}. The fixed allowlisted prompt runs locally in the vault root.</p><List title="Prerequisites" values={preview.prerequisites}/><List title="Inputs" values={preview.authoritativeInputs}/><List title="Outputs" values={preview.outputs}/><section><h3>Failure behavior</h3><p>{preview.failureBehavior}</p></section>{preview.requiresSlug&&<p><strong>Application:</strong> {slug||'No slug entered — Run will fail safely.'}</p>}<div className="dialog-actions"><button type="button" onClick={closePreview}>Cancel</button><button type="button" className="button--primary" ref={runButtonRef} onClick={execute} disabled={preview.requiresSlug&&!slug}>Run</button></div></>}</dialog></div>
}
