import { useEffect, useRef, useState } from 'react'
import { Link, useBlocker, useParams, useSearchParams } from 'react-router-dom'
import { api } from '../api/client.js'
import { LoadingState, ErrorState, EmptyState } from '../components/AsyncState.jsx'
import StatusBadge from '../components/StatusBadge.jsx'
import PriorityBadge from '../components/PriorityBadge.jsx'
import QuickUpdatePanel from '../components/QuickUpdatePanel.jsx'
import RecentRuns from '../components/RecentRuns.jsx'
import Markdown from '../components/Markdown.jsx'
import { applicationActionsView, preparationView } from '../applicationViewModel.js'

const documents=[['index','Overview'],['jobDescription','Job description'],['fitAnalysis','Fit analysis'],['cv','CV'],['coverLetter','Cover letter'],['companyProfile','Company profile'],['peopleNotes','People notes'],['interviewPrep','Interview prep'],['submissionNotes','Submission notes']]
const labels={to_apply:'To apply',applied:'Applied',recruiter_screen:'Recruiter screen',interview:'Interview',offer:'Offer',rejected:'Rejected',withdrawn:'Withdrawn',archived:'Archived',identified:'Identified'}
const gateLabel=value=>value.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase())

export default function ApplicationDetail(){
 const {slug}=useParams(),[params,setParams]=useSearchParams(),scope=params.get('scope')==='archive'?'archive':'active'
 const [app,setApp]=useState(),[doc,setDoc]=useState(),[active,setActive]=useState(''),[versions,setVersions]=useState([]),[draft,setDraft]=useState(''),[view,setView]=useState(()=>params.get('view')||'preview'),[tab,setTab]=useState(()=>params.get('tab')||'overview'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState(false),[transitioning,setTransitioning]=useState(false),[pending,setPending]=useState(null),[reason,setReason]=useState('')
 const dialogRef=useRef(),openerRef=useRef();const dirty=!!doc&&draft!==doc.content
 const blocker=useBlocker(dirty)
 useEffect(()=>{if(blocker.state==='blocked'){if(window.confirm('Discard unsaved document changes?'))blocker.proceed();else blocker.reset()}},[blocker])
 const load=async()=>{setLoading(true);setError('');try{setApp(await api.getApplication(slug,scope))}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[slug,scope])
 useEffect(()=>{if(!app)return;const nextTab=params.get('tab')||'overview',nextView=params.get('view')||'preview',artifact=params.get('artifact'),version=params.get('version')||undefined;setTab(nextTab);setView(nextView);if(artifact&&(active!==artifact||doc?.version!==(version||null))){setActive(artifact);setDoc();setError('');Promise.all([api.getDocument(scope,slug,artifact,version),api.getDocumentVersions(scope,slug,artifact)]).then(([r,list])=>{setDoc(r);setVersions(list.versions);setDraft(r.content)}).catch(e=>setError(e.message))}else if(!artifact){setActive('');setDoc();setVersions([])}},[app,params.toString(),slug,scope])
 useEffect(()=>{const before=e=>{if(dirty){e.preventDefault();e.returnValue=''}};const key=e=>{if(dirty&&(e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save()}};window.addEventListener('beforeunload',before);window.addEventListener('keydown',key);return()=>{window.removeEventListener('beforeunload',before);window.removeEventListener('keydown',key)}},[dirty,draft,doc])
 const updateQuery=(patch)=>{const next=new URLSearchParams(params);Object.entries(patch).forEach(([k,v])=>v?next.set(k,v):next.delete(k));next.set('scope',scope);setParams(next,{replace:false})}
 const selectTab=value=>{setTab(value);updateQuery({tab:value})}
 const openDoc=async(artifact,version)=>{if(dirty&&!window.confirm('Discard unsaved document changes?'))return;setActive(artifact);updateQuery({tab:'documents',artifact,version:version||'',view});setDoc();setError('');try{const [r,list]=await Promise.all([api.getDocument(scope,slug,artifact,version),api.getDocumentVersions(scope,slug,artifact)]);setDoc(r);setVersions(list.versions);setDraft(r.content)}catch(e){setError(e.message)}}
 const save=async()=>{if(!doc||!dirty||!app||!applicationActionsView(app).preparationWritable)return;let mode='overwrite';if(doc.protected){if(!window.confirm('This submitted artifact is protected. Create a clearly named follow-up version?'))return;mode='follow-up'}setSaving(true);setError('');try{const r=await api.saveDocument(scope,slug,active,draft,doc.revision,mode,doc.version);const reopened=await api.getDocument(scope,slug,active,r.version);setDoc(reopened);setDraft(reopened.content);setVersions((await api.getDocumentVersions(scope,slug,active)).versions);if(r.followUp)window.alert(`Created ${r.filename}; the submitted original was not changed.`)}catch(e){setError(e.message)}finally{setSaving(false)}}
 const askTransition=(target,event)=>{openerRef.current=event.currentTarget;setPending(target);setReason('');dialogRef.current?.showModal()}
 const closeDialog=()=>{dialogRef.current?.close();setPending(null);setReason('');openerRef.current?.focus()}
 const transition=async()=>{if(!pending)return;const target=pending;setTransitioning(true);setError('');try{const result=await api.transitionApplication(slug,target,{scope,reason:reason.trim()||undefined});closeDialog();if(result.href)window.location.assign(result.href);else await load()}catch(e){setError(e.message)}finally{setTransitioning(false)}}
 if(loading&&!app)return <LoadingState label="Opening application…"/>;if(!app)return <ErrorState message={error||'Application not found'} onRetry={load}/>
 const actions=app.actions||{},allowed=new Set(app.lifecycle?.allowedTransitions||[]),preparation=app.preparation,firstMissing=preparation.steps.find(step=>!step.complete),preparationDisplay=preparationView(preparation),actionView=applicationActionsView(app)
 const availableDocs=documents.filter(([key])=>key==='companyProfile'?app.artifacts.companyProfileLocal:app.artifacts[key])
 return <div className="page-stack application-detail" data-testid="application-detail"><Link to="/opportunities" onClick={e=>{if(dirty&&!window.confirm('Discard unsaved document changes?'))e.preventDefault()}}>← Back to opportunities</Link>
 <header className="detail-hero" data-testid="lifecycle-summary"><div><p className="eyebrow">{app.company}</p><h1>{app.role||app.slug}</h1><div className="card-meta"><StatusBadge status={app.lifecycle.status}/><PriorityBadge priority={app.priority}/><span>Updated {app.updated||'unknown'}</span></div></div><div className="preparation-summary" data-testid="preparation-summary"><strong>Preparation completeness</strong><span>{preparationDisplay.valueText}</span><progress max="100" value={preparationDisplay.percent} aria-label="Preparation completeness" aria-valuetext={`${preparationDisplay.valueText}, ${preparationDisplay.percent}%`}>{preparationDisplay.percent}%</progress><small title={preparationDisplay.helper}>{preparationDisplay.helper}</small>{actionView.terminal&&<span className="muted">Closed · historical preparation preserved</span>}</div></header>
 <nav className="detail-tabs" aria-label="Application detail sections">{['overview','documents','relationships','activity'].map(value=>{const next=new URLSearchParams(params);next.set('scope',scope);next.set('tab',value);return <Link key={value} className={tab===value?'tab tab--active':'tab'} aria-current={tab===value?'page':undefined} to={`?${next}`} onClick={e=>{if(dirty&&!window.confirm('Discard unsaved document changes?'))e.preventDefault()}}>{gateLabel(value)}</Link>})}</nav>
 <section className="application-command-bar" aria-label="Application commands"><div>{actionView.primary?.type==='action'&&<Link className="button button--primary" to={`/create?action=${actionView.primary.action}&slug=${slug}&scope=${scope}&returnTo=${encodeURIComponent(`/opportunities/${slug}?scope=${scope}`)}`}>{actionView.primary.label}</Link>}{actionView.primary?.type==='quick-update'&&<button className="button button--primary" onClick={()=>{selectTab('activity');requestAnimationFrame(()=>document.getElementById('quick-update')?.dispatchEvent(new CustomEvent('quick-update-focus',{detail:actionView.primary.focus})))}}>{actionView.primary.label}</button>}{actions.advance&&allowed.has(actions.advance.target)&&<button className={actionView.primary?.type==='advance'?'button button--primary':'button'} disabled={transitioning} onClick={e=>askTransition(actions.advance.target,e)}>Advance</button>}{actionView.primary?.type==='reopen'&&<button className="button button--primary" disabled={transitioning} onClick={e=>askTransition(actionView.primary.target,e)}>Reopen</button>}{actionView.preparationWritable&&<><Link className="button" to={`/create?action=position-analysis&slug=${slug}&scope=${scope}&returnTo=${encodeURIComponent(`/opportunities/${slug}?scope=${scope}`)}`}>Run analysis</Link><Link className="button" to={`/create?action=create-cv&slug=${slug}&scope=${scope}&returnTo=${encodeURIComponent(`/opportunities/${slug}?scope=${scope}`)}`}>Create or refresh CV</Link><Link className="button" to={`/create?action=interview-prep&slug=${slug}&scope=${scope}&returnTo=${encodeURIComponent(`/opportunities/${slug}?scope=${scope}`)}`}>Prepare interview</Link></>}</div>{(actions.close?.length>0||actions.archive)&&<details><summary className="button">More</summary><div className="command-overflow">{actions.close?.filter(target=>allowed.has(target)).map(target=><button key={target} onClick={e=>askTransition(target,e)}>{target==='withdrawn'?'Withdraw':'Close as rejected'}</button>)}{actions.archive&&allowed.has('archived')&&<button onClick={e=>askTransition('archived',e)}>Archive</button>}</div></details>}</section>
 {error&&<p className="document-error" role="alert">{error}</p>}
 {!app.lifecycle?.valid&&<section className="card repair-record" role="alert"><p className="eyebrow">Record repair required</p><h2>Lifecycle status is not recognized</h2><p>This legacy record cannot be advanced safely. Repair its metadata status to a supported value, refresh the vault, then return here.</p><Link className="button button--primary" to="/settings">Open repair tools</Link></section>}
 {tab==='overview'&&<section className="detail-grid" data-testid="overview-section"><article className="card lifecycle-workspace"><p className="eyebrow">Recommended action</p><h2>{actions.advance?`Advance to ${labels[actions.advance.target]}`:actions.reopen?'Reopen application':'No further action recommended'}</h2><p className="muted">Use the command bar above for lifecycle actions.</p></article><article className="card"><p className="eyebrow">Preparation</p><h2>Preparation steps</h2><ul className="check-list" data-testid="preparation-steps">{preparation.steps.map(step=><li key={step.id} className={step.complete?'done':''} data-state={step.complete?'complete':'incomplete'}><span className="check-state-icon" aria-hidden="true">{step.complete?'✓':'○'}</span><span className="sr-only">{step.complete?'Completed: ':'Incomplete: '}</span>{step.complete&&({fit:'fitAnalysis',cv:'cv','cover-letter':'coverLetter'}[step.id])?<button className="link-button" onClick={()=>{selectTab('documents');openDoc({fit:'fitAnalysis',cv:'cv','cover-letter':'coverLetter'}[step.id])}}>{step.label}</button>:step.label}</li>)}</ul>{firstMissing&&<><h3>Next action</h3><p>{firstMissing.label}</p></>}</article></section>}
 {tab==='documents'&&<section data-testid="documents-section"><div className="section-heading"><div><p className="eyebrow">Documents</p><h2>{actionView.preparationWritable?'Editable application workspace':'Preparation documents'}</h2>{!actionView.preparationWritable&&<p className="protection-note">Reopen to edit preparation documents</p>}</div></div><div className="document-layout"><nav className="document-tabs" aria-label="Application documents">{availableDocs.map(([key,label])=>{const next=new URLSearchParams(params);next.set('scope',scope);next.set('tab','documents');next.set('artifact',key);return <Link key={key} aria-current={active===key?'page':undefined} to={`?${next}`}>{label}</Link>})}</nav><div className="document-viewer" aria-labelledby={active?'document-panel-heading':undefined}>{active&&<h3 id="document-panel-heading" className="sr-only">{documents.find(x=>x[0]===active)?.[1]}</h3>}{!active?<EmptyState title="Choose a document"/>:!doc?(error?<ErrorState message={error} onRetry={()=>openDoc(active)}/>:<LoadingState label="Loading document…"/>):<><div className="document-toolbar"><div className="view-toggle"><button aria-pressed={view==='source'} onClick={()=>{setView('source');updateQuery({view:'source'})}}>Source</button><button aria-pressed={view==='preview'} onClick={()=>{setView('preview');updateQuery({view:'preview'})}}>Preview</button></div>{(versions.length>0||doc.version)&&<label>Version <select value={doc.version||''} onChange={e=>openDoc(active,e.target.value||undefined)}><option value="">Submitted/current</option>{versions.map(version=><option key={version} value={version}>{version}</option>)}</select></label>}<span className={dirty?'dirty-indicator is-dirty':'dirty-indicator'}>{dirty?'● Unsaved':'Saved'}</span><button disabled={!actionView.preparationWritable||!dirty||saving} onClick={()=>{setDraft(doc.content);setError('')}}>Revert</button><button disabled={!actionView.preparationWritable||!dirty||saving||!doc.editable} onClick={save}>{doc.protected?'Save follow-up':'Save'}</button><a className="button" href={`/api/vault/documents/${encodeURIComponent(scope)}/${encodeURIComponent(slug)}/${encodeURIComponent(active)}.pdf${doc.version?`?version=${encodeURIComponent(doc.version)}`:''}`}>Export PDF</a><Link className="button" to={`/opportunities/${slug}/documents/${active}/print?scope=${scope}${doc.version?`&version=${encodeURIComponent(doc.version)}`:''}`}>Print</Link></div>{doc.protected&&<p className="protection-note">Submitted version protected. Saving creates a timestamped follow-up; it never overwrites the original.</p>}{view==='source'?<textarea className="document-editor" value={draft} readOnly={!actionView.preparationWritable||!doc.editable} onChange={e=>setDraft(e.target.value)} aria-label="Markdown source"/>:<Markdown content={draft}/>}</>}</div></div></section>}
 {tab==='relationships'&&<section className="detail-grid" data-testid="relationships-section"><article className="card"><p className="eyebrow">Connected company</p><h2>{app.company}</h2>{app.companyProfile?.slug?<Link to={`/companies/${app.companyProfile.slug}?from=${encodeURIComponent(`/opportunities/${slug}?scope=${scope}&tab=relationships`)}`}>View company profile</Link>:<p className="muted">No linked company profile.</p>}</article><article className="card"><p className="eyebrow">Connected people</p><h2>People</h2>{app.people?.length?<ul className="network-list">{app.people.map(p=><li key={p.slug||p.name}><Link to="/network">{p.name}</Link></li>)}</ul>:<p className="muted">No linked people.</p>}</article></section>}
 {tab==='activity'&&<section className="detail-grid" data-testid="activity-section"><article className="card"><p className="eyebrow">Metadata</p><h2>Application summary</h2><dl className="metadata"><dt>Status</dt><dd>{labels[app.lifecycle.status]||app.lifecycle.status}</dd><dt>Created</dt><dd>{app.created||'—'}</dd><dt>Updated</dt><dd>{app.updated||'—'}</dd><dt>Location</dt><dd>{app.location||app.country||'—'}</dd><dt>Narrative</dt><dd>{app.dominantNarrative||'—'}</dd></dl></article><QuickUpdatePanel app={app} scope={scope} onReload={load}/><RecentRuns slug={slug}/><article className="card"><p className="eyebrow">Activity</p><h2>Lifecycle summary</h2><p>Currently {labels[app.lifecycle.status]||app.lifecycle.status}. {app.lifecycle.terminal?'This application is closed.':actions.advance?`Recommended next stage: ${labels[actions.advance.target]}.`:'No next stage is recommended.'}</p><p className="muted">Last metadata update: {app.updated||'unknown'}.</p></article></section>}
 <dialog ref={dialogRef} className="action-dialog lifecycle-dialog" aria-labelledby="transition-title" onCancel={e=>{e.preventDefault();closeDialog()}}>{pending&&<form method="dialog" onSubmit={e=>{e.preventDefault();transition()}}><h2 id="transition-title">{pending==='rejected'||pending==='withdrawn'?'Close application':pending==='archived'?'Archive application':pending==='identified'?'Reopen application':`Advance to ${labels[pending]}`}</h2>{(pending==='rejected'||pending==='withdrawn')&&<><fieldset><legend>Close outcome</legend>{actions.close.map(target=><label key={target}><input type="radio" name="outcome" value={target} checked={pending===target} onChange={()=>setPending(target)}/> {labels[target]}</label>)}</fieldset><label className="dialog-field">Reason <textarea value={reason} onChange={e=>setReason(e.target.value)} required aria-required="true"/></label></>}<p>This updates the application lifecycle and audit record. Document drafts are not changed.</p><div className="dialog-actions"><button type="button" onClick={closeDialog}>Cancel</button><button className="button--primary" disabled={transitioning||(pending==='rejected'||pending==='withdrawn')&&!reason.trim()}>{transitioning?'Updating…':'Confirm'}</button></div></form>}</dialog>
 </div>
}
