import { useEffect,useState } from 'react'
import { Link,useParams,useSearchParams } from 'react-router-dom'
import { api } from '../api/client.js'
import { LoadingState,ErrorState,EmptyState } from '../components/AsyncState.jsx'

export default function Companies(){
 const {slug}=useParams(),[params,setParams]=useSearchParams(),[companies,setCompanies]=useState(),[company,setCompany]=useState(),[query,setQuery]=useState(()=>params.get('q')||''),[error,setError]=useState('')
 const load=()=>{setError('');if(slug)api.getCompany(slug).then(setCompany).catch(e=>setError(e.message));else api.getCompanies().then(setCompanies).catch(e=>setError(e.message))}
 useEffect(load,[slug])
 if(error)return <ErrorState message={error} onRetry={load}/>
 if(slug){if(!company)return <LoadingState label="Opening company…"/>;const from=params.get('from'),back=from?.startsWith('/')&&!from.startsWith('//')?from:'/companies';return <div className="page-stack"><Link to={back}>← {from?'Back to opportunity':'All companies'}</Link><header className="detail-hero"><div><p className="eyebrow">Company</p><h1>{company.name}</h1><p className="muted">Research profile · {company.updated?`updated ${company.updated}`:'freshness unknown'}</p></div></header>{!company.hasFrontmatter&&<p className="protection-note">This profile has limited structured data.</p>}<div className="detail-grid"><article className="card"><h2>Risks and red flags</h2><p>{company.risksRedFlags||'No risks recorded.'}</p></article><article className="card"><h2>Talking points</h2><p>{company.talkingPoints||'No talking points recorded.'}</p></article><article className="card"><h2>Referenced opportunities</h2>{company.referencedByApplications?.length?<ul>{company.referencedByApplications.map(a=>{const item=typeof a==='string'?{slug:a,scope:'active'}:a;return <li key={`${item.scope}:${item.slug}`}><Link to={item.href||`/opportunities/${item.slug}?scope=${item.scope||'active'}`}>{item.label||item.slug}</Link>{item.scope==='archive'&&<span className="muted"> · archived</span>}</li>})}</ul>:<p className="muted">No linked opportunities.</p>}</article><article className="card"><h2>People</h2><Link to={`/network?company=${encodeURIComponent(company.slug)}`}>View related people</Link></article></div></div>}
 if(!companies)return <LoadingState label="Loading companies…"/>;const filtered=companies.filter(c=>c.name.toLowerCase().includes(query.toLowerCase()))
 return <div className="page-stack"><header className="page-heading"><p className="eyebrow">Companies</p><h1>Company intelligence</h1><p>Research, relationships, risks, and opportunity context.</p></header><label className="search-field">Search companies<input className="search-input" type="search" value={query} onChange={e=>{const value=e.target.value;setQuery(value);const next=new URLSearchParams(params);value?next.set('q',value):next.delete('q');setParams(next,{replace:true})}} placeholder="Search by company name…"/></label>{filtered.length?<div className="opportunity-list">{filtered.map(c=><article className="card" key={c.slug}><h2><Link to={`/companies/${c.slug}?from=${encodeURIComponent(`/companies${query?`?q=${encodeURIComponent(query)}`:''}`)}`}>{c.name}</Link></h2><p>{c.referencedByApplications?.length||0} referenced opportunities</p><Link to={`/companies/${c.slug}?from=${encodeURIComponent(`/companies${query?`?q=${encodeURIComponent(query)}`:''}`)}`}>Open company profile →</Link></article>)}</div>:<EmptyState title="No companies found" message="Try a different search."/>}</div>
}
