import { useEffect, useRef, useState } from 'react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { api } from '../api/client.js'
const IDS=new Set(['position-analysis','generate-fit-analysis','create-application-analysis','create-cv','generate-cover-letter','interview-prep'])
const LEGACY={analysis:'position-analysis',cv:'create-cv',interview:'interview-prep'}
const terminal=new Set(['completed','failed','cancelled','timed_out','interrupted','expired','awaiting_apply'])
const draftKey='nextstep.create.draft.v1'
const localPath=value=>value?.startsWith('/')&&!value.startsWith('//')&&!value.includes('\\')?value:'/opportunities'
export default function Create(){
 const [query,setQuery]=useSearchParams(),navigate=useNavigate(),heading=useRef(),errors=useRef(),[caps,setCaps]=useState(null),[step,setStep]=useState(1),[sourceType,setSourceType]=useState('text'),[source,setSource]=useState(''),[file,setFile]=useState(null),[intake,setIntake]=useState(null),[action,setAction]=useState('position-analysis'),[slug,setSlug]=useState(''),[scope,setScope]=useState('active'),[company,setCompany]=useState(''),[role,setRole]=useState(''),[context,setContext]=useState(null),[harness,setHarness]=useState(''),[preview,setPreview]=useState(null),[run,setRun]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[resume,setResume]=useState(null)
 const returnTo=localPath(query.get('returnTo'))
 useEffect(()=>{let raw=query.get('action'),legacyApp=query.get('application'),mapped=LEGACY[raw];const candidate=mapped||raw;if(legacyApp&&!query.get('slug'))setSlug(legacyApp);else setSlug(query.get('slug')||'');setScope(query.get('scope')==='archive'?'archive':'active');if(mapped||legacyApp){setNotice('This older link was updated to the current workflow format.');const next=new URLSearchParams(query);next.set('action',candidate||'position-analysis');if(legacyApp){next.set('slug',legacyApp);next.delete('application')}setQuery(next,{replace:true})}if(candidate&&!IDS.has(candidate)){setError(`Unknown workflow “${candidate}”. Choose a supported workflow below.`);setStep(1)}else if(candidate){setAction(candidate);setStep(query.get('slug')||legacyApp?2:1)}const runId=query.get('runId');if(runId)api.getRun(runId).then(value=>{setRun(value);setStep(4)}).catch(e=>setError(e.message));api.getActionCapabilities().then(setCaps).catch(e=>setError(e.message));const saved=localStorage.getItem(draftKey);if(saved)try{setResume(JSON.parse(saved))}catch{}},[])
 useEffect(()=>{if(slug)api.getApplication(slug,scope).then(setContext).catch(()=>setContext(null));else setContext(null)},[slug,scope])
 useEffect(()=>{if(!intake?.id)return;api.getIntake(intake.id).then(setIntake).catch(()=>{setIntake(null);setNotice('Your evidence intake expired. Add the source again before reviewing or running this workflow.')})},[action,slug,scope])
 useEffect(()=>{heading.current?.focus()},[step]);useEffect(()=>{if(error)errors.current?.focus()},[error])
 useEffect(()=>{if(!run||terminal.has(run.state))return;let es,timer,closed=false;const poll=()=>api.getRun(run.id).then(setRun).catch(()=>{});const connect=()=>{es=new EventSource(`/api/actions/runs/${run.id}/events`);for(const type of ['snapshot','queued','generating','output','awaiting_apply','completed','failed','cancelled','timed_out','interrupted','expired'])es.addEventListener(type,e=>setRun(JSON.parse(e.data)));es.onerror=()=>{es.close();poll();if(!closed)timer=setTimeout(connect,2000)}};connect();return()=>{closed=true;clearTimeout(timer);es?.close()}},[run?.id])
 const saveDraft=()=>{const value={action,slug,scope,company,role,sourceType,source:source.slice(0,20000),returnTo};localStorage.setItem(draftKey,JSON.stringify(value));setNotice('Draft saved on this device. Uploaded file bytes are never saved.');setResume(value)}
 const restore=()=>{Object.assign({},resume);setAction(resume.action);setSlug(resume.slug);setScope(resume.scope);setCompany(resume.company);setRole(resume.role);setSourceType(resume.sourceType);setSource(resume.source);setResume(null);setStep(resume.slug?2:1)}
 const upload=async()=>{let payload;if(sourceType==='url')payload={type:'url',url:source};else if(sourceType==='text')payload={type:'text',text:source};else{if(!file)throw Error('Choose a file');if(file.name.toLowerCase().endsWith('.pdf'))throw Error('PDF execution is unsupported. Paste text or upload .txt/.md.');const base64=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=no;r.readAsDataURL(file)});payload={type:'file',filename:file.name,mime:file.type||undefined,base64}}const created=await api.createIntake(payload);setIntake(created);return created}
 const review=async()=>{try{let current=intake;if(current?.id)current=await api.getIntake(current.id);if(!current&&(action==='create-application-analysis'||((action==='position-analysis'||action==='generate-fit-analysis')&&(!slug||action==='generate-fit-analysis'&&!context?.artifacts?.jobDescription))))current=await upload();setPreview(await api.validateCreate({actionId:action,slug,scope,company,role,intakeId:current?.id,harnessId:harness||undefined}));setStep(3);setError('')}catch(e){if(e.status===404&&intake){setIntake(null);setError('The evidence intake expired. Add the source again, then review.')}else setError(e.message)}}
 const execute=async()=>{try{const value=await api.startCreate({actionId:action,slug,scope,company,role,intakeId:intake?.id,harnessId:harness||undefined});setRun(value);setStep(4);const next=new URLSearchParams(query);next.set('runId',value.id);setQuery(next,{replace:true});localStorage.removeItem(draftKey)}catch(e){if(e.status===409&&intake){setIntake(null);setRun(null);setPreview(null);setStep(2);setNotice('Your evidence intake expired. Choose or paste a replacement source, then review again.');setError('Replacement evidence is required.')}else setError(e.message)}}
 const apply=async()=>{try{setRun(await api.applyRun(run.id,{expectedRevision:run.applyRevision,idempotencyKey:run.id}));setError('')}catch(e){setError(e.message)}}
 const retry=async()=>{try{const value=await api.retryRun(run.id);setRun(value);const next=new URLSearchParams(query);next.set('runId',value.id);setQuery(next,{replace:true});setError('')}catch(e){setError(e.message)}}
 const discard=async()=>{try{await api.discardRun(run.id);setRun(await api.getRun(run.id));setError('')}catch(e){setError(e.message)}}
 const actions=caps?.actions.filter(a=>IDS.has(a.id))||[],chosen=actions.find(a=>a.id===action),needsSource=!slug&&(action==='position-analysis'||action==='create-application-analysis')||(action==='generate-fit-analysis'&&!context?.artifacts?.jobDescription)
 return <div className="page-stack guided-flow"><header className="page-heading"><p className="eyebrow">Governed workflow</p><h1 tabIndex="-1" ref={heading}>{context?`${chosen?.label||'Workflow'} for ${context.role} at ${context.company}`:'Create with control'}</h1><p>Workflow → Context → Review → Run / Result</p></header><div aria-live="polite">Step {step} of 4{run?` · ${run.state}`:''}</div>{notice&&<p className="notice" role="status">{notice}</p>}{error&&<div className="error-state" role="alert" tabIndex="-1" ref={errors}><strong>Check this workflow</strong><p>{error}</p></div>}{resume&&<aside className="card"><strong>Resume saved draft?</strong> <button onClick={restore}>Resume</button> <button onClick={()=>{localStorage.removeItem(draftKey);setResume(null)}}>Discard</button></aside>}
 {step===1&&<section className="card"><h2>Choose workflow</h2><div className="workflow-grid">{actions.map(a=><button className={action===a.id?'workflow-choice selected':'workflow-choice'} key={a.id} onClick={()=>{setAction(a.id);setError('');setStep(2)}}><strong>{a.label}</strong><span>{a.outputs.join(', ')}</span></button>)}</div></section>}
 {step===2&&<section className="card"><h2>Context and prerequisites</h2>{context&&<p><strong>{context.company} — {context.role}</strong> · {scope}</p>}<label>Application slug <input value={slug} onChange={e=>setSlug(e.target.value)}/></label>{action==='create-application-analysis'&&<><label>Company <input value={company} onChange={e=>setCompany(e.target.value)}/></label><label>Role <input value={role} onChange={e=>setRole(e.target.value)}/></label></>}{(needsSource||action==='create-application-analysis')&&<><fieldset><legend>{intake?'Replace evidence source':'Evidence source'}</legend><label>Evidence source <select value={sourceType} onChange={e=>setSourceType(e.target.value)}><option value="text">Paste text</option><option value="url">Public URL</option><option value="file">Text/Markdown file</option></select></label>{sourceType==='file'?<input type="file" accept=".txt,.md,text/plain,text/markdown" onChange={e=>{setFile(e.target.files[0]);setIntake(null)}}/>:<textarea aria-label="Replacement source" value={source} onChange={e=>{setSource(e.target.value);setIntake(null)}} />}</fieldset></>}<div className="flow-actions"><button onClick={()=>setStep(1)}>Back</button><button onClick={saveDraft}>Save draft</button><button className="button button--primary" onClick={review}>Review {chosen?.label?.toLowerCase()}</button></div></section>}
 {step===3&&<section className="card"><h2>Review</h2><h3>Server-verified prerequisites</h3><ul className="prerequisite-list">{preview?.prerequisites?.map(item=><li key={item.id} data-state={item.state}><strong>{item.state==='ready'?'Ready':item.state==='missing'?'Missing':'Unavailable'}</strong> — {item.label}{item.reason&&<span className="muted"> {item.reason}</span>} {item.remediation&&<Link to={item.remediation}>Resolve prerequisite</Link>}</li>)}</ul><dl><dt>Workflow</dt><dd>{chosen?.label}</dd><dt>Context</dt><dd>{context?`${context.company} — ${context.role}`:company&&role?`${company} — ${role}`:'Standalone analysis'}</dd><dt>Evidence</dt><dd>{intake?`${intake.type}: ${intake.filename||'bounded source'}`:slug?'Existing governed application':'None'}</dd><dt>Outputs</dt><dd>{chosen?.outputs.join(', ')}</dd><dt>Expected writes after explicit Apply</dt><dd>{preview?.expectedWrites.length?preview.expectedWrites.join(', '):'None'}</dd><dt>Version behavior</dt><dd>Submitted artifacts are preserved; follow-up versions are created.</dd><dt>Failure behavior</dt><dd>{chosen?.failureBehavior}</dd></dl><details><summary>Advanced execution settings</summary><label>Harness override <select value={harness} onChange={e=>setHarness(e.target.value)}><option value="">Default: {caps?.selectedHarness}</option>{caps?.harnesses.map(h=><option key={h.id} value={h.id} disabled={!h.available}>{h.label}{h.available?'':' — unavailable'}</option>)}</select></label></details><div className="flow-actions"><button onClick={()=>setStep(2)}>Back</button><Link className="button" to={returnTo}>Exit</Link><button className="button button--primary" onClick={execute} disabled={!preview?.valid}>Start {chosen?.label?.toLowerCase()}</button></div></section>}
 {step===4&&run&&<section className="card"><h2>Run and result</h2><p><strong>Status:</strong> {run.state}</p><p>{run.result?.summary||run.resultPreview}</p>{['queued','generating'].includes(run.state)&&<button onClick={async()=>setRun(await api.cancelAction(run.id))}>Cancel run</button>}{run.state==='awaiting_apply'&&<button className="button button--primary" onClick={apply}>Apply generated artifact</button>}{run.retryable&&<button onClick={retry}>Retry run</button>}{run.discardable&&<button onClick={discard}>Discard staged result</button>}<div role="log" aria-label="Workflow activity" className="run-log">{run.output||'Durable sanitized events are recorded by the server.'}</div>{run.artifactLinks?.map(link=><a key={link.path} href={link.url}>{link.label||link.path}</a>)}<Link className="button" to={returnTo}>Back to application</Link></section>}</div>
}
