import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { api } from '../api/client.js'
import StatusBadge from '../components/StatusBadge.jsx'
import PriorityBadge from '../components/PriorityBadge.jsx'
import { LoadingState, ErrorState, EmptyState } from '../components/AsyncState.jsx'
import { applicationActionsView, applicationHref, preparationView } from '../applicationViewModel.js'

const stages=['identified','to_apply','applied','recruiter_screen','interview','offer','rejected','withdrawn','archived']
export default function Dashboard(){
 const [data,setData]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState('active'),[view,setView]=useState('list')
 const load=()=>{setLoading(true);setError('');api.getApplications().then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))};useEffect(load,[])
 const visible=useMemo(()=>data.filter(a=>(status==='all'||(status==='archive'?a.storageScope==='archive':a.storageScope==='active'))&&`${a.company} ${a.role} ${a.slug}`.toLowerCase().includes(query.toLowerCase())),[data,status,query])
 const transition=async(app,target)=>{if(target==='archived'&&!window.confirm(`Archive ${app.company} — ${app.role||app.slug}?`))return;if(app.storageScope==='archive'&&!window.confirm(`Restore ${app.company} — ${app.role||app.slug} as ${target}?`))return;try{const result=await api.transitionApplication(app.slug,target,{scope:app.storageScope});if(result.href)window.location.assign(result.href);else await load()}catch(e){setError(e.message)}}
 if(loading)return <LoadingState label="Mapping your opportunities…"/>;if(error)return <ErrorState message={error} onRetry={load}/>
 return <div className="page-stack"><header className="page-header"><p className="eyebrow">Opportunity pipeline</p><h1>Where your next move is taking shape</h1><p>Search every role, scan preparation, and act without opening each workspace.</p></header><div className="filter-bar"><label className="search-field">Search opportunities<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Company or role"/></label><label>Scope<select value={status} onChange={e=>setStatus(e.target.value)}><option value="active">Active</option><option value="archive">Archived</option><option value="all">All</option></select></label><div className="view-toggle" aria-label="Display" role="group"><button aria-pressed={view==='list'} onClick={()=>setView('list')}>List</button><button aria-pressed={view==='board'} onClick={()=>setView('board')}>Board</button></div></div>{!visible.length?<EmptyState title="No matching opportunities" message="Try a different search or scope."/>:view==='list'?<div className="opportunity-list">{visible.map(a=><Opportunity key={`${a.archived}-${a.slug}`} app={a} transition={transition}/>)}</div>:<div className="board">{stages.map(stage=><section className="board-column" key={stage}><h2>{stage} <span>{visible.filter(a=>a.lifecycle?.status===stage).length}</span></h2>{visible.filter(a=>a.lifecycle?.status===stage).map(a=><Opportunity key={a.slug} app={a} compact transition={transition}/>)}</section>)}</div>}</div>
}
function Opportunity({app,compact,transition}){const href=applicationHref(app),actions=app.actions||{},display=preparationView(app.preparation),actionView=applicationActionsView(app);return <article className={`opportunity-card${compact?' opportunity-card--compact':''}`}><div><p className="eyebrow">{app.company||'Company pending'}</p><h3><Link to={href}>{app.role||app.slug}</Link></h3>{!compact&&<p>{actionView.terminal?'Closed · historical preparation preserved':app.preparation.nextAction}</p>}<strong>Preparation completeness</strong><small>{display.valueText}</small><progress max="100" value={display.percent} aria-label="Preparation completeness" aria-valuetext={`${display.valueText}, ${display.percent}%`}>{display.percent}%</progress><small title={display.helper}>{display.helper}</small></div><div className="card-meta"><StatusBadge status={app.lifecycle?.status||app.status}/><PriorityBadge priority={app.priority}/></div><div className="card-actions">{actionView.primary?.type==='reopen'?<button className="button button--primary" onClick={()=>transition(app,actionView.primary.target)}>Reopen</button>:<Link className="button button--primary" to={href}>{actionView.primary?.type==='preparation'?'Continue preparation':'Open workspace'}</Link>}{actions.advance&&<button onClick={()=>transition(app,actions.advance.target)}>Advance</button>}{actions.archive&&<details><summary aria-label="More actions">•••</summary><div className="card-menu"><button onClick={()=>transition(app,'archived')}>Archive</button></div></details>}</div></article>}
