import { useEffect, useMemo, useState } from 'react'
import { api } from '../api/client.js'

const sections={identity:['profile/identity.md'],positioning:['context/positioning.md'],experience:['context/career.md'],evidence:['context/evidence.md','context/story-bank.md'],capabilities:['context/technical.md','context/claims.md'],preferences:['profile/preferences.md'],voice:['profile/voice.md']}
export default function Profile(){
 const [context,setContext]=useState(null),[proposals,setProposals]=useState([]),[detail,setDetail]=useState(null),[query,setQuery]=useState(''),[results,setResults]=useState([]),[claim,setClaim]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const load=async()=>{try{setError('');const [c,p]=await Promise.all([api.getProfileContext(),api.getProposals()]);setContext(c);setProposals(p)}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[])
 const grouped=useMemo(()=>Object.entries(sections).map(([name,paths])=>[name,(context?.documents||[]).filter(d=>paths.includes(d.path))]).filter(([,d])=>d.length),[context])
 const search=async e=>{e.preventDefault();try{setResults((await api.searchProfile(query)).results)}catch(e){setError(e.message)}}
 const propose=async e=>{e.preventDefault();setBusy(true);try{await api.createProposal(claim);setClaim('');await load()}catch(e){setError(e.message)}finally{setBusy(false)}}
 const review=async(action,id)=>{const token=`${action.toUpperCase()}:${id}`;if(window.prompt(`Type ${token} to confirm. Holoself remains canonical.`)!==token)return;setBusy(true);try{const r=await api.reviewProposal(id,action,token);setContext(r.context);setDetail(null);setProposals(await api.getProposals())}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="profile-page"><header className="page-heading"><div><p className="eyebrow">Holoself · career lens</p><h1>Profile</h1><p>Live, reviewed self-context. Changes always go through a proposal.</p></div><span className={`status-pill ${context?'status-pill--success':''}`}>{context?'Connected':'Unavailable'}</span></header>
 {error&&<div className="error-banner" role="alert">{error}</div>}
 <section className="profile-grid">{grouped.map(([name,docs])=><article className="profile-section" key={name}><p className="eyebrow">{name}</p>{docs.map(d=><div key={d.path}><pre className="profile-content">{d.content}</pre><div className="provenance"><span>Source: {d.provenance}</span><span>{d.disclosure}</span><span>{d.sensitivity}</span>{d.publicationAllowed&&<span>publish-approved</span>}</div></div>)}</article>)}</section>
 <section className="workspace-panel"><h2>Search career context</h2><form className="profile-form" onSubmit={search}><input value={query} onChange={e=>setQuery(e.target.value)} minLength="2" maxLength="200" placeholder="Search evidence, experience, positioning…"/><button>Search</button></form>{results.map((r,i)=><article className="search-result" key={`${r.source}-${i}`}><strong>{r.section||r.source}</strong><p>{r.passage}</p><div className="provenance"><span>{r.provenance||r.source}</span><span>{r.disclosure}</span><span>{r.sensitivity}</span></div></article>)}</section>
 <div className="profile-columns"><section className="workspace-panel"><h2>Propose a profile update</h2><p>No canonical files are edited here. Your claim becomes a reviewable Holoself proposal.</p><form onSubmit={propose}><textarea value={claim} onChange={e=>setClaim(e.target.value)} required maxLength="2000" rows="6"/><div className="form-footer"><small>{claim.length}/2000</small><button disabled={busy}>Create proposal</button></div></form><hr/><h3>Project-owned baseline views</h3><p>Separate working views; they do not override Holoself.</p><a href="/api/vault/documents/master/baseline/cv" className="text-link">Master baseline CV</a></section>
 <section className="workspace-panel"><h2>Proposal review</h2>{proposals.length===0?<p>No proposals.</p>:proposals.map(p=><button className="proposal-row" key={p.id} onClick={async()=>setDetail(await api.getProposal(p.id))}><span><strong>{p.claim}</strong><small>{p.id}</small></span><span>{p.status}</span></button>)}</section></div>
 {detail&&<div className="modal-backdrop"><section className="review-dialog" role="dialog" aria-modal="true" aria-label="Proposal review"><button className="dialog-close" onClick={()=>setDetail(null)} aria-label="Close">×</button><p className="eyebrow">Proposal {detail.status}</p><h2>{detail.claim}</h2><p>{detail.evidence}</p><div className="provenance"><span>ID: {detail.id}</span><span>Target: {detail.target||'Holoself review'}</span></div><div className="review-actions"><button disabled={busy} onClick={()=>review('approve',detail.id)}>Approve</button><button disabled={busy} onClick={()=>review('reject',detail.id)}>Reject</button><button disabled={busy} onClick={()=>review('defer',detail.id)}>Defer</button></div><small>Each action requires typing the exact confirmation token.</small></section></div>}
 </div>
}
