import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { api } from '../api/client.js'
import { LoadingState,ErrorState,EmptyState } from '../components/AsyncState.jsx'
import { applicationHref, preparationView } from '../applicationViewModel.js'
import RecentRuns from '../components/RecentRuns.jsx'
export default function Today(){
 const [state,setState]=useState({loading:true});const load=()=>{setState({loading:true});Promise.all([api.getOverview(),api.getApplications()]).then(([overview,apps])=>setState({overview,apps:apps.filter(a=>!a.lifecycle?.logicallyArchived)})).catch(e=>setState({error:e.message}))};useEffect(load,[])
 if(state.loading)return <LoadingState/>;if(state.error)return <ErrorState message={state.error} onRetry={load}/>
 const priorities=state.apps.filter(a=>!a.lifecycle?.terminal&&!['ready_for_next_step','closed'].includes(a.preparation.state)).sort((a,b)=>(a.priority||'z').localeCompare(b.priority||'z')).slice(0,3),summary=state.overview.preparation
 return <div className="page-stack"><section className="welcome-panel"><p className="eyebrow">Today · Your career, in focus</p><h1>Good morning, Samuel.</h1><p>Your live workspace has {state.overview.totals.applications} active opportunities. Choose the move that creates momentum.</p><div className="welcome-actions"><Link className="button button--primary" to="/opportunities">Review priorities</Link><Link className="button" to="/insights">See signals</Link></div></section><section className="metric-grid"><article><strong>{summary.ready}</strong><span>prepared for next step</span></article><article><strong>{summary.needsAttention}</strong><span>need preparation</span></article><article><strong>{state.overview.totals.people}</strong><span>people in network</span></article><article><strong>{state.overview.totals.companies}</strong><span>company profiles</span></article></section><section><div className="section-heading"><div><p className="eyebrow">Live priorities</p><h2>Recent focus</h2></div><Link to="/opportunities">View pipeline →</Link></div>{priorities.length?<div className="opportunity-list">{priorities.map(a=>{const display=preparationView(a.preparation);return <article className="opportunity-card" key={a.slug}><div><p className="eyebrow">{a.company}</p><h3><Link to={applicationHref(a)}>{a.role||a.slug}</Link></h3><p>{a.preparation.nextAction}</p><strong>Preparation completeness</strong><span>{display.valueText}</span><progress max="100" value={display.percent} aria-label="Preparation completeness" aria-valuetext={`${display.valueText}, ${display.percent}%`}>{display.percent}%</progress><small title={display.helper}>{display.helper}</small></div></article>})}</div>:<EmptyState title="Everything is prepared" message="No immediate preparation gaps were found."/>}</section><RecentRuns /></div>
}
