import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import crypto from 'node:crypto'
import matter from 'gray-matter'
import { executeApplicationCommand } from './commands.js'

function fixture({scope='active',status='applied'}={}){const root=path.join(os.tmpdir(),`commands-${crypto.randomUUID()}`);fs.mkdirSync(root);const c=path.join(root,'Candidatures'),apps=path.join(c,'applications'),archive=path.join(c,'archive','applications'),coord=path.join(root,'.coordination'),folder=path.join(scope==='active'?apps:archive,'acme-role');for(const d of [apps,archive,coord,folder])fs.mkdirSync(d,{recursive:true});fs.writeFileSync(path.join(folder,'metadata.md'),`---\ncompany: Acme\nrole: Role\nstatus: ${status}\napplication_revision: 0\n---\n`);fs.writeFileSync(path.join(folder,'index.md'),`---\nstatus: ${status}\n---\n# Acme\n`);fs.writeFileSync(path.join(c,'index.md'),`| [[applications/acme-role/index|Acme role]] | ${status} |\n`);fs.writeFileSync(path.join(apps,'index.md'),`- [[acme-role/index|Acme role]] — ${status}; fixture narrative\n`);fs.writeFileSync(path.join(coord,'audit-log.md'),'# Audit\n');return{root,folder,paths:{vaultRoot:root,candidaturesDir:c,applicationsDir:apps,archiveApplicationsDir:archive,auditLogPath:path.join(coord,'audit-log.md')}}}
const base=(type,payload,key=type)=>({schemaVersion:1,commandId:key,idempotencyKey:key,expectedRevision:0,type,payload})
const cases=[
 ['application.setPriority',{priority:'high'},d=>assert.equal(d.priority,'high')],
 ['application.setLocation',{country:'Belgium',location:'Brussels'},d=>assert.equal(d.location,'Brussels')],
 ['application.setSource',{url:'https://example.com/job',reference:null},d=>assert.match(d.source,/example/)],
 ['application.recordReuseAssessment',{reviewed:true,note:null,reviewed_at:'2026-08-05'},d=>assert.equal(d.reuse_assessment.reviewed,true)],
 ['application.selectDominantNarrative',{narrative:'AI Transformation Leader'},d=>assert.equal(d.dominant_narrative,'AI Transformation Leader')],
 ['application.recordEmployerResponse',{responseType:'acknowledged',occurredAt:'2026-08-05',note:null,lifecycleTarget:null},d=>assert.equal(d.employer_response.type,'acknowledged')],
 ['application.recordInterview',{occurredAt:'2026-08-05',interviewType:'technical',outcome:'pass',note:null,lifecycleTarget:'recruiter_screen'},d=>assert.equal(d.status,'recruiter_screen')],
 ['application.addNote',{note:'private activity'},d=>assert.equal(d.activity_notes.length,1)],
 ['application.transitionStatus',{target:'recruiter_screen',reason:'response'},d=>assert.equal(d.status,'recruiter_screen')],
]
for(const [type,payload,check] of cases)test(type,()=>{const f=fixture();const result=executeApplicationCommand({paths:f.paths,slug:'acme-role',scope:'active',command:base(type,payload)});assert.equal(result.revision,1);check(matter(fs.readFileSync(path.join(f.folder,'metadata.md'),'utf8')).data);assert.doesNotMatch(fs.readFileSync(f.paths.auditLogPath,'utf8'),/private/)})
test('stale and idempotency semantics',()=>{const f=fixture(),c=base('application.setPriority',{priority:'high'},'k');const a=executeApplicationCommand({paths:f.paths,slug:'acme-role',scope:'active',command:c}),b=executeApplicationCommand({paths:f.paths,slug:'acme-role',scope:'active',command:c});assert.deepEqual(a,b);assert.throws(()=>executeApplicationCommand({paths:f.paths,slug:'acme-role',scope:'active',command:{...c,payload:{priority:'low'}}}),e=>e.statusCode===409);assert.throws(()=>executeApplicationCommand({paths:f.paths,slug:'acme-role',scope:'active',command:{...base('application.addNote',{note:'x'},'new'),expectedRevision:0}}),e=>e.statusCode===412)})
test('scope, terminal and validation restrictions are explicit',()=>{const f=fixture({status:'rejected'});assert.throws(()=>executeApplicationCommand({paths:f.paths,slug:'acme-role',scope:'active',command:base('application.setPriority',{priority:'high'})}),e=>e.statusCode===409);assert.throws(()=>executeApplicationCommand({paths:f.paths,slug:'acme-role',command:base('application.addNote',{note:'x'})}),e=>e.statusCode===422);const archived=fixture({scope:'archive',status:'archived'});const result=executeApplicationCommand({paths:archived.paths,slug:'acme-role',scope:'archive',command:base('application.addNote',{note:'x'})});assert.equal(result.revision,1);const v=fixture();assert.throws(()=>executeApplicationCommand({paths:v.paths,slug:'acme-role',scope:'active',command:base('application.setPriority',{priority:'urgent'})}),e=>e.statusCode>=400&&e.statusCode<500)})
test('legacy folder command rejects submission so canonical Application-ID interface is exclusive',()=>{const f=fixture();assert.throws(()=>executeApplicationCommand({paths:f.paths,slug:'acme-role',scope:'active',command:base('application.recordSubmission',{occurredAt:'2026-08-28',channel:'portal',note:null})}),/Unsupported command type/);assert.equal(matter(fs.readFileSync(path.join(f.folder,'metadata.md'),'utf8')).data.application_revision,0)})
test('repairRecord uses the canonical v2 schema for metadata and local indexes',()=>{const metadataRepair=fixture();fs.rmSync(path.join(metadataRepair.folder,'metadata.md'));fs.writeFileSync(path.join(metadataRepair.folder,'index.md'),`---\ntype: application\ncompany: Acme\nrole: Role\nstatus: applied\ncreated: 2026-08-01\nupdated: 2026-08-02\nevidence_note: verified\n---\n# Rich legacy body\n`);executeApplicationCommand({paths:metadataRepair.paths,slug:'acme-role',scope:'active',command:base('application.repairRecord',{target:'metadata'},'repair-metadata')});const repaired=matter(fs.readFileSync(path.join(metadataRepair.folder,'metadata.md'),'utf8')).data;assert.equal(repaired.schema_version,2);assert.equal(repaired.type,'application');assert.equal(repaired.storage_scope,'active');assert.equal(repaired.evidence_note,'verified');assert.equal(repaired.application_revision,1)
 const indexRepair=fixture();fs.appendFileSync(path.join(indexRepair.folder,'metadata.md'),'Rich metadata body\r\n');fs.rmSync(path.join(indexRepair.folder,'index.md'));executeApplicationCommand({paths:indexRepair.paths,slug:'acme-role',scope:'active',command:base('application.repairRecord',{target:'index'},'repair-index')});const index=matter(fs.readFileSync(path.join(indexRepair.folder,'index.md'),'utf8'));assert.deepEqual(index.data,{schema_version:2,type:'application-index',application:'acme-role',status:'applied',storage_scope:'active',updated:index.data.updated});assert.match(index.content,/# Acme — Role/);assert.match(fs.readFileSync(path.join(indexRepair.folder,'metadata.md'),'utf8'),/Rich metadata body\r?\n$/)})
test('post-commit disposable-index failure does not report a durable command as rolled back',()=>{const f=fixture();const result=executeApplicationCommand({paths:f.paths,slug:'acme-role',scope:'active',command:base('application.setPriority',{priority:'high'}),invalidate:()=>{throw new Error('cache removal failed')}});assert.equal(result.revision,1);assert.equal(matter(fs.readFileSync(path.join(f.folder,'metadata.md'),'utf8')).data.priority,'high');assert.match(fs.readFileSync(f.paths.auditLogPath,'utf8'),/application\.setPriority/)})
