import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { acquireVaultLocks } from './lockAdapter.js'
import { listApplicationDocumentVersions, readApplicationDocument, readMasterDocument, resolveApplicationDocument, saveApplicationDocument } from './documents.js'
function fixture(status='to_apply'){const root=fs.mkdtempSync(path.join(os.tmpdir(),'vault-doc-')),active=path.join(root,'apps'),archive=path.join(root,'archive'),folder=path.join(active,'safe-role');fs.mkdirSync(folder,{recursive:true});fs.mkdirSync(path.join(root,'locks'));fs.writeFileSync(path.join(folder,'metadata.md'),`---\nstatus: ${status}\n---\n`);fs.writeFileSync(path.join(folder,'cv.md'),'---\ntitle: Café\n---\n# Résumé 👋');fs.writeFileSync(path.join(folder,'cover-letter.md'),'# Letter');return{root,active,archive,folder,locksDir:path.join(root,'locks'),auditLogPath:path.join(root,'audit.md')}}
const opts=f=>({applicationsRoot:f.active,archiveRoot:f.archive,scope:'active',slug:'safe-role',artifact:'cv',locksDir:f.locksDir,auditLogPath:f.auditLogPath})
test('document resolver rejects scope, slug, artifact, and version traversal',()=>{const roots={applicationsRoot:'/vault/apps',archiveRoot:'/vault/archive'};for(const value of [{scope:'active',slug:'../secret',artifact:'cv'},{scope:'other',slug:'safe-role',artifact:'cv'},{scope:'active',slug:'safe-role',artifact:'../../secret'},{scope:'active',slug:'safe-role',artifact:'cv',version:'../cv-follow-up-20260102T030405Z'}])assert.equal(resolveApplicationDocument({...roots,...value}),null);assert.equal(resolveApplicationDocument({...roots,scope:'active',slug:'safe-role',artifact:'cv'}),path.resolve('/vault/apps/safe-role/cv.md'))})
test('reader preserves UTF-8/frontmatter and exposes revision',()=>{const f=fixture(),result=readApplicationDocument(opts(f));assert.equal(result.content,'---\ntitle: Café\n---\n# Résumé 👋');assert.match(result.revision,/^\d+-[a-f0-9]{64}$/);assert.equal(result.editable,true);fs.rmSync(f.root,{recursive:true,force:true})})
test('master reader allows only the baseline CV reference',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'vault-master-')),master=path.join(root,'Master');fs.mkdirSync(master);fs.writeFileSync(path.join(master,'Samuel_Guedes_Mota_Baseline_CV.md'),'# Baseline CV');const result=readMasterDocument({vaultRoot:root,slug:'baseline',artifact:'cv'});assert.equal(result.status,200);assert.equal(result.content,'# Baseline CV');assert.equal(result.editable,false);for(const value of [{slug:'baseline',artifact:'../../cv'},{slug:'other',artifact:'cv'},{slug:'baseline',artifact:'cv',version:'x'}])assert.equal(readMasterDocument({vaultRoot:root,...value}).status,400);fs.rmSync(root,{recursive:true,force:true})})
test('save uses optimistic concurrency, lock cleanup, audit, invalidation, and atomic replacement',()=>{const f=fixture(),before=readApplicationDocument(opts(f));let invalidated=false;const saved=saveApplicationDocument({...opts(f),content:'# UTF-8 ✓',expectedRevision:before.revision,invalidate:()=>invalidated=true});assert.equal(saved.status,200);assert.equal(fs.readFileSync(path.join(f.folder,'cv.md'),'utf8'),'# UTF-8 ✓');assert.equal(invalidated,true);assert.match(fs.readFileSync(f.auditLogPath,'utf8'),/atomic overwrite/);assert.deepEqual(fs.readdirSync(f.locksDir),[]);assert.equal(saveApplicationDocument({...opts(f),content:'stale',expectedRevision:before.revision}).status,409);const lease=acquireVaultLocks({vaultRoot:f.root,lockDir:f.locksDir,targets:[path.join(f.folder,'cv.md')]});assert.equal(saveApplicationDocument({...opts(f),content:'locked',expectedRevision:saved.revision}).status,423);lease.releaseAll();fs.rmSync(f.root,{recursive:true,force:true})})
for(const status of ['applied','recruiter_screen','interview','offer','rejected','withdrawn','archived'])test(`submitted artifacts remain protected in ${status}`,()=>{const f=fixture(status);assert.equal(readApplicationDocument(opts(f)).protected,true);assert.equal(readApplicationDocument({...opts(f),artifact:'coverLetter'}).protected,true);fs.rmSync(f.root,{recursive:true,force:true})})
test('submission provenance protects canonical artifacts independent of lifecycle',()=>{const f=fixture('to_apply');fs.writeFileSync(path.join(f.folder,'metadata.md'),'---\nstatus: to_apply\nsubmission:\n  confirmed: true\n---\n');const before=readApplicationDocument(opts(f));assert.equal(before.protected,true);const blocked=saveApplicationDocument({...opts(f),content:'# spoof',expectedRevision:before.revision});assert.equal(blocked.status,409);assert.equal(fs.readFileSync(path.join(f.folder,'cv.md'),'utf8'),before.content);fs.rmSync(f.root,{recursive:true,force:true})})
test('follow-up versions are strictly listable, readable, and editable in active lifecycle',()=>{const f=fixture('applied'),before=readApplicationDocument(opts(f)),saved=saveApplicationDocument({...opts(f),content:'# follow up',expectedRevision:before.revision,mode:'follow-up',now:new Date('2026-01-02T03:04:05Z')});assert.equal(saved.version,'cv-follow-up-20260102T030405Z');assert.deepEqual(listApplicationDocumentVersions(opts(f)).versions,[saved.version]);const opened=readApplicationDocument({...opts(f),version:saved.version});assert.equal(opened.content,'# follow up');const edited=saveApplicationDocument({...opts(f),version:saved.version,content:'# edited',expectedRevision:opened.revision});assert.equal(edited.status,200);assert.equal(readApplicationDocument({...opts(f),version:saved.version}).content,'# edited');fs.rmSync(f.root,{recursive:true,force:true})})
for(const status of ['rejected','withdrawn','archived'])test(`terminal ${status} rejects every artifact save before mutation`,()=>{const f=fixture(status);for(const artifact of ['cv','coverLetter','index']){if(artifact==='index')fs.writeFileSync(path.join(f.folder,'index.md'),'# Index');const before=readApplicationDocument({...opts(f),artifact});const result=saveApplicationDocument({...opts(f),artifact,content:'# blocked',expectedRevision:before.revision,mode:'follow-up'});assert.deepEqual({status:result.status,code:result.code},{status:409,code:'APPLICATION_TERMINAL'});assert.equal(readApplicationDocument({...opts(f),artifact}).content,before.content);assert.equal(readApplicationDocument({...opts(f),artifact}).editable,false)}assert.deepEqual(fs.readdirSync(f.locksDir),[]);assert.equal(fs.existsSync(f.auditLogPath),false);fs.rmSync(f.root,{recursive:true,force:true})})
test('archive scope rejects direct service bypass while preserving reads',()=>{const f=fixture();const archivedFolder=path.join(f.archive,'safe-role');fs.mkdirSync(f.archive,{recursive:true});fs.renameSync(f.folder,archivedFolder);f.folder=archivedFolder;const options={...opts(f),scope:'archive'},before=readApplicationDocument(options),result=saveApplicationDocument({...options,content:'# blocked',expectedRevision:before.revision});assert.equal(result.status,409);assert.equal(result.code,'APPLICATION_TERMINAL');assert.equal(readApplicationDocument(options).content,before.content);fs.rmSync(f.root,{recursive:true,force:true})})
test('post-commit invalidation failure keeps committed document and audit successful',()=>{const f=fixture(),before=readApplicationDocument(opts(f));fs.writeFileSync(f.auditLogPath,'# Audit\n');const result=saveApplicationDocument({...opts(f),content:'# changed',expectedRevision:before.revision,invalidate:()=>{throw new Error('injected invalidation failure')}});assert.equal(result.status,200);assert.equal(fs.readFileSync(path.join(f.folder,'cv.md'),'utf8'),'# changed');assert.match(fs.readFileSync(f.auditLogPath,'utf8'),/document-save/);assert.deepEqual(fs.readdirSync(f.locksDir),[]);fs.rmSync(f.root,{recursive:true,force:true})})
test('durable transaction failure rolls back document and audit before commit',()=>{const f=fixture(),before=readApplicationDocument(opts(f)),audit='# Audit\n';fs.writeFileSync(f.auditLogPath,audit);const result=saveApplicationDocument({...opts(f),content:'# changed',expectedRevision:before.revision,deps:{afterStep(step){if(step==='target:0')throw new Error('injected transaction failure')}}});assert.equal(result.status,500);assert.equal(fs.readFileSync(path.join(f.folder,'cv.md'),'utf8'),before.content);assert.equal(fs.readFileSync(f.auditLogPath,'utf8'),audit);assert.deepEqual(fs.readdirSync(f.locksDir),[]);fs.rmSync(f.root,{recursive:true,force:true})})
