import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import crypto from 'node:crypto'
import { acquireVaultLocks, canonicalLockManifest, canonicalVaultIdentity } from './lockAdapter.js'

function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'vault-lock-adapter-')),locks=path.join(root,'.coordination','locks');fs.mkdirSync(locks,{recursive:true});t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return{root,locks}}

test('canonical identities collapse absolute, dot-segment, slash, and backslash aliases',t=>{const f=fixture(t),absolute=path.join(f.root,'Candidatures','applications','safe','metadata.md');const aliases=[absolute,'./Candidatures/applications/safe/metadata.md','Candidatures/applications/safe/../safe/metadata.md','Candidatures\\applications\\safe\\metadata.md'];assert.deepEqual(new Set(aliases.map(value=>canonicalVaultIdentity(f.root,value))),new Set(['Candidatures/applications/safe/metadata.md']));assert.deepEqual(canonicalLockManifest(f.root,aliases),['Candidatures/applications/safe/metadata.md']);for(const unsafe of ['.',f.root,'../escape.md'])assert.throws(()=>canonicalVaultIdentity(f.root,unsafe),/target|escapes/)})

test('alias and cross-subsystem callers contend on the same canonical owner-token lease',t=>{const f=fixture(t),target=path.join(f.root,'Candidatures','applications','safe','metadata.md'),first=acquireVaultLocks({vaultRoot:f.root,lockDir:f.locks,targets:[target],taskId:'document-save'});assert.throws(()=>acquireVaultLocks({vaultRoot:f.root,lockDir:f.locks,targets:['./Candidatures\\applications\\safe\\metadata.md'],taskId:'application-command'}),/EEXIST|locked/i);first.heartbeatAll();first.held[0].token='wrong-token';assert.throws(()=>first.releaseAll(),/owner token/i)})

test('symlink target and lock aliases fail closed where supported',t=>{const f=fixture(t),outside=fs.mkdtempSync(path.join(os.tmpdir(),'vault-outside-'));t.after(()=>fs.rmSync(outside,{recursive:true,force:true}));const alias=path.join(f.root,'alias');try{fs.symlinkSync(outside,alias,process.platform==='win32'?'junction':'dir')}catch(e){if(['EPERM','EACCES'].includes(e.code))return;throw e}assert.throws(()=>canonicalVaultIdentity(f.root,path.join(alias,'file.md')),/symlink|outside/);const identity='safe.md',lockAlias=path.join(f.locks,`${path.basename(identity)}-${awaitDigest(identity)}.lock.json`);function awaitDigest(x){return crypto.createHash('sha256').update(x).digest('hex').slice(0,12)};fs.writeFileSync(path.join(outside,'lock'),'x');try{fs.symlinkSync(path.join(outside,'lock'),lockAlias,'file');assert.throws(()=>acquireVaultLocks({vaultRoot:f.root,lockDir:f.locks,targets:[identity]}),/alias|EEXIST/)}catch(e){if(!['EPERM','EACCES'].includes(e.code))throw e}})

test('automatic heartbeat renews owner-token leases and timer stops on release',async t=>{const f=fixture(t),events=[];const run=(_tool,args)=>{const command=args[0],token=args[args.indexOf('--owner-token')+1];events.push(command);if(command==='acquire')return{lock:{owner_token:'owner'}};if(token!=='owner')throw new Error('owner token mismatch');return{lock:{owner_token:'owner'}}};const lease=acquireVaultLocks({vaultRoot:f.root,lockDir:f.locks,targets:['safe.md'],leaseSeconds:1,runTool:run});await new Promise(r=>setTimeout(r,420));assert.ok(events.includes('heartbeat'));lease.releaseAll();const count=events.length;await new Promise(r=>setTimeout(r,420));assert.equal(events.length,count)})

test('complete manifests are deduplicated, sorted before acquisition, and released in reverse order',t=>{const f=fixture(t),events=[];let token=0;const run=(tool,args)=>{const command=args[0],artifact=args[args.indexOf('--artifact')+1];events.push(`${command}:${artifact}`);return command==='acquire'?{lock:{owner_token:`token-${++token}`}}:{status:command}};const lease=acquireVaultLocks({vaultRoot:f.root,lockDir:f.locks,targets:['z.md','a.md','./z.md'],runTool:run});assert.deepEqual(lease.manifest,['a.md','z.md']);lease.heartbeatAll();lease.releaseAll();assert.deepEqual(events.filter(x=>x.startsWith('acquire:')),['acquire:a.md','acquire:z.md']);assert.deepEqual(events.filter(x=>x.startsWith('release:')),['release:z.md','release:a.md'])})
