import test from 'node:test'
import assert from 'node:assert/strict'
import * as fs from 'node:fs/promises'
import os from 'node:os';import path from 'node:path';import { fileURLToPath } from 'node:url'
import { transitionApplication } from './mutations.js'
const repoRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..')
async function fixture(){const root=await fs.mkdtemp(path.join(os.tmpdir(),'career-mutation-')),apps=path.join(root,'Candidatures/applications'),app=path.join(apps,'acme-role'),locks=path.join(root,'.coordination/locks');await fs.mkdir(app,{recursive:true});await fs.mkdir(path.join(root,'.coordination/tools'),{recursive:true});await fs.mkdir(locks,{recursive:true});await fs.copyFile(path.join(repoRoot,'.coordination/tools/vault-lock.mjs'),path.join(root,'.coordination/tools/vault-lock.mjs'));await fs.writeFile(path.join(app,'metadata.md'),'---\nstatus: identified\ncompany: Acme\n---\nNarrative identified stays.\n');await fs.writeFile(path.join(app,'index.md'),'---\nstatus: identified\n---\nNarrative identified stays.\n');await fs.writeFile(path.join(apps,'index.md'),'| [[acme-role]] | archived | Keep narrative prose |\n');await fs.writeFile(path.join(root,'Candidatures/index.md'),'- [[applications/acme-role]] — rejected — Narrative stays.\n');const auditLogPath=path.join(root,'.coordination/audit-log.md');await fs.writeFile(auditLogPath,'# Audit\n');return{root,paths:{vaultRoot:root,candidaturesDir:path.join(root,'Candidatures'),applicationsDir:apps,archiveApplicationsDir:path.join(root,'Candidatures/archive/applications'),locksDir:locks,auditLogPath}}}
test('validates traversal, invalid statuses, and skipped lifecycle transitions before mutation',async()=>{const{paths}=await fixture();await assert.rejects(()=>transitionApplication({paths,slug:'../evil',target:'to_apply'}),/Invalid application slug/);await assert.rejects(()=>transitionApplication({paths,slug:'acme-role',target:'hacked'}),/Invalid application status/);await assert.rejects(()=>transitionApplication({paths,slug:'acme-role',target:'applied'}),/Invalid lifecycle transition/)})
test('structurally updates stale global statuses and preserves narrative',async()=>{const{paths}=await fixture();let invalidated=false;await transitionApplication({paths,slug:'acme-role',target:'to_apply',invalidate:()=>invalidated=true});for(const file of [path.join(paths.applicationsDir,'acme-role/metadata.md'),path.join(paths.applicationsDir,'acme-role/index.md'),path.join(paths.applicationsDir,'index.md'),path.join(paths.candidaturesDir,'index.md')])assert.match(await fs.readFile(file,'utf8'),/to_apply/);assert.match(await fs.readFile(path.join(paths.applicationsDir,'acme-role/index.md'),'utf8'),/Narrative identified stays/);assert.match(await fs.readFile(paths.auditLogPath,'utf8'),/identified -> to_apply/);assert.equal(invalidated,true);assert.deepEqual(await fs.readdir(paths.locksDir),[])})
for(const defect of ['missing','ambiguous','statusless'])test(`fails closed for ${defect} required global row`,async()=>{const{paths}=await fixture(),index=path.join(paths.applicationsDir,'index.md');if(defect==='missing')await fs.writeFile(index,'| [[other-role]] | identified |\n');if(defect==='ambiguous')await fs.appendFile(index,'| [[acme-role]] | identified |\n');if(defect==='statusless')await fs.writeFile(index,'| [[acme-role]] | no lifecycle here |\n');await assert.rejects(()=>transitionApplication({paths,slug:'acme-role',target:'to_apply'}),/exactly one|missing structural lifecycle status/);assert.match(await fs.readFile(path.join(paths.applicationsDir,'acme-role/metadata.md'),'utf8'),/status: identified/);assert.equal(await fs.readFile(paths.auditLogPath,'utf8'),'# Audit\n');assert.deepEqual(await fs.readdir(paths.locksDir),[])})
test('durable lifecycle transaction rolls back all files and audit on injected crash boundary',async()=>{const{paths}=await fixture(),tracked=[path.join(paths.applicationsDir,'acme-role/metadata.md'),path.join(paths.applicationsDir,'acme-role/index.md'),path.join(paths.applicationsDir,'index.md'),path.join(paths.candidaturesDir,'index.md'),paths.auditLogPath],before=new Map(await Promise.all(tracked.map(async p=>[p,await fs.readFile(p,'utf8')])));await assert.rejects(()=>transitionApplication({paths,slug:'acme-role',target:'to_apply',deps:{afterStep(step){if(step==='target:2')throw new Error('injected transaction failure')}}}),/injected/);for(const p of tracked)assert.equal(await fs.readFile(p,'utf8'),before.get(p));assert.deepEqual(await fs.readdir(paths.locksDir),[])})
test('post-commit lifecycle invalidation failure does not report rollback',async()=>{const{paths}=await fixture();const result=await transitionApplication({paths,slug:'acme-role',target:'to_apply',invalidate:()=>{throw new Error('injected invalidate')}});assert.equal(result.status,'to_apply');assert.match(await fs.readFile(path.join(paths.applicationsDir,'acme-role/metadata.md'),'utf8'),/status: to_apply/);assert.match(await fs.readFile(paths.auditLogPath,'utf8'),/identified -> to_apply/)})
