import test from 'node:test'
import assert from 'node:assert/strict'
import { buildNetworkGraph } from './networkGraph.js'
const application=(slug,extra={})=>({slug,role:slug,company:'Acme',status:'identified',archived:false,people:[],companyProfile:null,updated:'2026-01-02',...extra})
const company={slug:'acme',name:'Acme',referencedByApplications:['a','a','old']},person={slug:'pat',name:'Pat',company:'Acme',referencedByApplications:['a','a','old']}
const model={companies:[company],people:[person],applications:[application('a',{role:'Architect',companyProfile:{slug:'acme',resolved:true},people:[{slug:'pat'},{slug:'pat'}]}),application('solo'),application('old',{archived:true,status:'archived',companyProfile:{slug:'acme',resolved:true},people:[{slug:'pat'}]})]}
test('creates only evidence-backed typed edges without inference',()=>{const g=buildNetworkGraph(model);assert.deepEqual(g.nodes.map(n=>n.id),['company:acme','opportunity:a','opportunity:solo','person:pat']);assert.deepEqual(g.edges.map(e=>e.type),['company-application','person-application','person-company']);assert.equal(g.semantics.inferredRelationships,false)})
test('preserves exact labeled evidence, dates and safe application hrefs',()=>{const e=buildNetworkGraph(model).edges.find(x=>x.type==='person-company');assert.equal(e.weight,1);assert.deepEqual(e.opportunities,['a']);assert.deepEqual(e.evidence[0],{opportunity:{slug:'a',scope:'active',label:'Architect',role:'Architect',company:'Acme',href:'/opportunities/a?scope=active',updated:'2026-01-02'},artifact:'metadata',artifactLabel:'Application metadata',field:'people + company_profile',sourceLabel:'Co-reference in application metadata',href:'/opportunities/a?scope=active',updated:'2026-01-02'});const personNode=buildNetworkGraph(model).nodes.find(n=>n.id==='person:pat');assert.equal(personNode.linkedOpportunities[0].label,'Architect')})
test('never emits raw or unsafe paths',()=>{const g=buildNetworkGraph({applications:[application('../escape',{companyProfile:{slug:'acme',resolved:true}})],companies:[company],people:[]});assert.equal(g.nodes.find(n=>n.type==='opportunity').href,null);assert.equal(g.edges[0].evidence[0].href,null);assert.equal(JSON.stringify(g).includes('folderPath'),false)})
test('does not infer person-company edge from matching company text',()=>{const g=buildNetworkGraph({applications:[application('a',{people:[{slug:'pat'}]})],companies:[company],people:[person]});assert.equal(g.edges.some(e=>e.type==='person-company'),false)})
test('scope and ordering remain explicit and deterministic',()=>{assert.deepEqual(buildNetworkGraph(model).unconnectedActiveOpportunities.map(x=>x.slug),['solo']);assert.deepEqual(buildNetworkGraph(model,{scope:'archive'}).nodes.filter(n=>n.type==='opportunity').map(n=>n.slug),['old']);const a=buildNetworkGraph(model,{scope:'all'}),b=buildNetworkGraph({applications:[...model.applications].reverse(),companies:model.companies,people:model.people},{scope:'all'});assert.deepEqual(a,b)})
