import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto'
import { acquireVaultLocks } from './lockAdapter.js'
import { recoverVaultTransactions,runVaultTransaction,transactionRoot } from './transactionJournal.js'
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'vault-tx-')),locksDir=path.join(root,'.coordination','locks'),folder=path.join(root,'Candidatures','applications','safe'),doc=path.join(folder,'cv.md'),audit=path.join(root,'.coordination','audit-log.md');fs.mkdirSync(folder,{recursive:true});fs.mkdirSync(locksDir,{recursive:true});fs.writeFileSync(doc,'old-doc');fs.writeFileSync(audit,'old-audit');t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return{root,doc,audit,paths:{vaultRoot:root,locksDir,auditLogPath:audit,applicationsDir:path.join(root,'Candidatures','applications'),archiveApplicationsDir:path.join(root,'Candidatures','archive','applications')}}}
const crash=message=>Object.assign(new Error(message),{simulatedCrash:true})
function execute(f,state){const outputs=new Map([[f.doc,'new-doc'],[f.audit,'new-audit']]),lease=acquireVaultLocks({vaultRoot:f.root,lockDir:f.paths.locksDir,targets:[...outputs.keys()]});assert.throws(()=>runVaultTransaction({paths:f.paths,kind:'document-save',context:{scope:'active',slug:'safe',artifact:'cv',version:null},outputs,lease,deps:{afterStep(step){if(step===state)throw crash('crash')}}}),/crash/);lease.releaseAll()}
test('prepared crash recovery restores exact preimages and is idempotent',t=>{const f=fixture(t);execute(f,'target:0');recoverVaultTransactions({paths:f.paths});recoverVaultTransactions({paths:f.paths});assert.equal(fs.readFileSync(f.doc,'utf8'),'old-doc');assert.equal(fs.readFileSync(f.audit,'utf8'),'old-audit');assert.deepEqual(fs.readdirSync(transactionRoot(f.paths)),[])})
test('committed crash recovery preserves complete new state',t=>{const f=fixture(t);execute(f,'committed');recoverVaultTransactions({paths:f.paths});assert.equal(fs.readFileSync(f.doc,'utf8'),'new-doc');assert.equal(fs.readFileSync(f.audit,'utf8'),'new-audit')})
test('forged extra contained target and unknown version fail closed before writes',t=>{const f=fixture(t);execute(f,'target:0');const root=transactionRoot(f.paths),name=fs.readdirSync(root)[0],file=path.join(root,name),j=JSON.parse(fs.readFileSync(file));const unrelated=path.join(f.root,'unrelated.md');fs.writeFileSync(unrelated,'untouched');j.manifest.push('unrelated.md');j.manifest.sort();j.preimages=j.manifest.map(p=>p==='unrelated.md'?{path:p,existed:true,data:Buffer.from('forged').toString('base64')}:j.preimages.find(x=>x.path===p));fs.writeFileSync(file,JSON.stringify(j));assert.throws(()=>recoverVaultTransactions({paths:f.paths}),/Unsafe/);assert.equal(fs.readFileSync(unrelated,'utf8'),'untouched');j.version=999;fs.writeFileSync(file,JSON.stringify(j));assert.throws(()=>recoverVaultTransactions({paths:f.paths}),/Unsafe/)})
