import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import { acquireVaultLocks, canonicalLockManifest, canonicalVaultIdentity } from './lockAdapter.js'

const VERSION=2,SLUG=/^[a-z0-9]+(?:-[a-z0-9]+)*$/,RUN=/^[0-9a-f-]{36}$/i
const ARTIFACTS=Object.freeze({index:'index.md',metadata:'metadata.md',jobDescription:'job-description.md',fitAnalysis:'fit-analysis.md',cv:'cv.md',coverLetter:'cover-letter.md',companyProfile:'company-profile.md',peopleNotes:'people-notes.md',interviewPrep:'interview-prep.md',submissionNotes:'submission-notes.md'})
const VERSION_NAME=/^[a-z][A-Za-z0-9]*-follow-up-\d{8}T\d{6}Z$/
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v
const exact=(x,keys)=>x&&typeof x==='object'&&!Array.isArray(x)&&Object.keys(x).length===keys.length&&keys.every(k=>Object.hasOwn(x,k))
const stateRoot=p=>p.stateRoot||path.join(p.vaultRoot,'.nextstep')
export function transactionRoot(paths){return path.join(stateRoot(paths),'transactions','vault')}
export function syncDirectory(io,directory){let fd;try{fd=io.openSync(directory,'r');io.fsyncSync(fd)}catch(e){if(!['EPERM','EINVAL'].includes(e.code))throw e}finally{if(fd!==undefined)io.closeSync(fd)}}
export function durableAtomicWrite(io,file,data){const temporary=`${file}.tmp-${process.pid}-${crypto.randomUUID()}`;io.mkdirSync(path.dirname(file),{recursive:true});let fd;try{fd=io.openSync(temporary,'wx',0o600);io.writeFileSync(fd,data);io.fsyncSync(fd);io.closeSync(fd);fd=undefined;io.renameSync(temporary,file);syncDirectory(io,path.dirname(file))}finally{if(fd!==undefined)io.closeSync(fd);io.rmSync(temporary,{force:true})}}
function removeDurably(io,file){io.rmSync(file,{force:true});syncDirectory(io,path.dirname(file))}
function roots(p){const state=stateRoot(p);return{active:p.applicationsDir||path.join(p.vaultRoot,'Candidatures','applications'),archive:p.archiveApplicationsDir||path.join(p.vaultRoot,'Candidatures','archive','applications'),cand:p.candidaturesDir||path.join(p.vaultRoot,'Candidatures'),audit:p.auditLogPath||path.join(p.vaultRoot,'.coordination','audit-log.md'),ledger:path.join(state,'transactions','application-commands','ledger.json'),relationalLedger:path.join(state,'transactions','relational-commands','ledger.json'),receipts:path.join(state,'receipts')}}
function appFolder(p,scope,slug){if(!['active','archive'].includes(scope)||!SLUG.test(slug||''))throw new Error('Unsafe vault transaction context');const r=roots(p);return path.join(scope==='active'?r.active:r.archive,slug)}
function expected(p,kind,c){const r=roots(p);if(kind==='application-command'){if(!exact(c,['commandId','lifecycle','scope','slug'])||typeof c.lifecycle!=='boolean')throw 0;const f=appFolder(p,c.scope,c.slug);return[c.lifecycle?[path.join(f,'metadata.md'),path.join(f,'index.md'),path.join(r.cand,'index.md'),path.join(r.active,'index.md')]:[path.join(f,'metadata.md')],r.audit,r.ledger].flat()}
 if(kind==='application-repair'){if(!exact(c,['commandId','scope','slug','target'])||!['metadata','index'].includes(c.target))throw 0;const f=appFolder(p,c.scope,c.slug);return[path.join(f,'metadata.md'),path.join(f,'index.md'),r.audit,r.ledger]}
 if(kind==='document-save'){if(!exact(c,['artifact','scope','slug','version'])||!Object.hasOwn(ARTIFACTS,c.artifact)||c.version!==null&&(!VERSION_NAME.test(c.version)||!c.version.startsWith(`${c.artifact}-follow-up-`)))throw 0;return[path.join(appFolder(p,c.scope,c.slug),c.version?`${c.version}.md`:ARTIFACTS[c.artifact]),r.audit]}
 if(kind==='lifecycle-transition'){if(!exact(c,['scope','slug','target']))throw 0;const f=appFolder(p,c.scope,c.slug);return[path.join(f,'metadata.md'),path.join(f,'index.md'),path.join(r.cand,'index.md'),path.join(r.active,'index.md'),r.audit]}
 if(kind==='artifact-apply'){if(!exact(c,['expectedRevision','runId','slug','targets'])||!SLUG.test(c.slug||'')||c.runId!==null&&!RUN.test(c.runId)||!Array.isArray(c.targets)||!c.targets.length)throw 0;const f=appFolder(p,'active',c.slug),files=c.targets.map(x=>{if(!exact(x,['artifact','version'])||!Object.hasOwn(ARTIFACTS,x.artifact)||x.version!==null&&(!VERSION_NAME.test(x.version)||!x.version.startsWith(`${x.artifact}-follow-up-`)))throw 0;return path.join(f,x.version?`${x.version}.md`:ARTIFACTS[x.artifact])});return[...files,path.join(f,'metadata.md'),r.audit,...(c.runId?[path.join(r.receipts,`${c.runId}.json`)]:[])]}
 if(kind==='relational-command'){if(!exact(c,['applicationId','commandId'])||typeof c.applicationId!=='string'||!c.applicationId.startsWith('application:')||typeof c.commandId!=='string'||!c.commandId)throw 0;return['applications.json','interactions.json','artifacts.json','manifest.json'].map(x=>path.join(r.cand,'records',x)).concat([r.audit,r.relationalLedger])}
 if(kind==='relational-reindex'){if(!exact(c,['applicationId','targets'])||c.applicationId!==null&&!String(c.applicationId).startsWith('application:')||!Array.isArray(c.targets)||!c.targets.length)throw 0;const allowed=new Set(['indexes/index.md','indexes/companies.md','indexes/vacancies.md','indexes/applications.md','indexes/people.md','indexes/interactions.md','indexes/artifacts.md','reports/inconsistencies.md','records/manifest.json']);if(c.targets.some(x=>!allowed.has(x))||new Set(c.targets).size!==c.targets.length)throw 0;return c.targets.map(x=>path.join(r.cand,x))}throw 0}
function expectedManifest(p,kind,c){try{return canonicalLockManifest(p.vaultRoot,expected(p,kind,c))}catch{throw new Error('Unsafe vault transaction context')}}
function validateJournal(paths,filename,j){if(!j||j.version!==VERSION||!RUN.test(j.id||'')||filename!==`${j.id}.journal`||!['prepared','committed'].includes(j.state))throw new Error(`Unsafe vault transaction journal: ${filename}`);const wanted=expectedManifest(paths,j.kind,j.context);if(JSON.stringify(j.manifest)!==JSON.stringify(wanted)||!Array.isArray(j.preimages)||j.preimages.length!==wanted.length)throw new Error(`Unsafe vault transaction manifest: ${filename}`);for(let i=0;i<wanted.length;i++){const x=j.preimages[i];if(!x||x.path!==wanted[i]||typeof x.existed!=='boolean'||typeof x.data!=='string')throw new Error(`Unsafe vault transaction preimages: ${filename}`)}return j}
function restore(io,paths,j){for(const x of j.preimages){const target=path.join(paths.vaultRoot,x.path);if(x.existed)durableAtomicWrite(io,target,Buffer.from(x.data,'base64'));else if(io.existsSync(target))removeDurably(io,target)}}
export function recoverVaultTransactions({paths,deps={}}){const io={...fs,...deps.io},root=transactionRoot(paths);if(!io.existsSync(root))return;for(const filename of io.readdirSync(root).sort()){const jf=path.join(root,filename);if(io.statSync(jf).isDirectory())continue;if(!filename.endsWith('.journal'))throw new Error(`Unsafe vault transaction journal name: ${filename}`);let j;try{j=validateJournal(paths,filename,JSON.parse(io.readFileSync(jf,'utf8')))}catch(e){if(String(e.message).startsWith('Unsafe'))throw e;throw new Error(`Invalid vault transaction journal: ${filename}`)}const lease=acquireVaultLocks({vaultRoot:paths.vaultRoot,lockDir:paths.locksDir||path.join(paths.vaultRoot,'.coordination','locks'),targets:j.manifest,taskId:`recover-${j.kind}`,operation:'transaction-recovery',runTool:deps.lockCommand});let primary;try{lease.assertSafe();if(j.state==='prepared')restore(io,paths,j);removeDurably(io,jf)}catch(e){primary=e;throw e}finally{lease.releaseAll({suppress:Boolean(primary)})}}}
export function runVaultTransaction({paths,kind,context,outputs,lease,deps={}}){const io={...fs,...deps.io},entries=outputs instanceof Map?[...outputs]:Object.entries(outputs||{});if(!entries.length)throw new Error('Vault transaction requires outputs');const by=new Map(entries.map(([x,d])=>[canonicalVaultIdentity(paths.vaultRoot,x),d])),manifest=canonicalLockManifest(paths.vaultRoot,[...by.keys()]),wanted=expectedManifest(paths,kind,stable(context||{}));if(by.size!==entries.length||JSON.stringify(manifest)!==JSON.stringify(wanted))throw new Error('Vault transaction targets do not match registered kind');const id=crypto.randomUUID(),root=transactionRoot(paths),jf=path.join(root,`${id}.journal`),preimages=manifest.map(identity=>{const f=path.join(paths.vaultRoot,identity),existed=io.existsSync(f);return{path:identity,existed,data:existed?io.readFileSync(f).toString('base64'):''}}),j={version:VERSION,id,kind,context:stable(context||{}),state:'prepared',manifest,preimages};io.mkdirSync(root,{recursive:true});durableAtomicWrite(io,jf,`${JSON.stringify(j)}\n`);deps.afterStep?.('prepared',j);try{lease?.assertSafe();for(let i=0;i<manifest.length;i++){lease?.assertSafe();const identity=manifest[i],target=path.join(paths.vaultRoot,identity),data=by.get(identity);if(data===null){if(io.existsSync(target))removeDurably(io,target)}else durableAtomicWrite(io,target,data);deps.afterStep?.(`target:${i}`,j)}lease?.assertSafe();j.state='committed';durableAtomicWrite(io,jf,`${JSON.stringify(j)}\n`);deps.afterStep?.('committed',j);removeDurably(io,jf);return{id,manifest}}catch(e){if(!e.simulatedCrash){restore(io,paths,j);removeDurably(io,jf)}throw e}}
export const TRANSACTION_KINDS=Object.freeze(['application-command','application-repair','document-save','lifecycle-transition','artifact-apply','relational-command','relational-reindex'])
