import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import { buildCountryMapModel, closedRatio, countryCentroid, isKeyboardActivation, isMarkerSelected, markerAccessibleLabel, markerRadius, normalizeCountry } from '../client/src/pages/countryMapModel.js'

test('country names normalize to stable centroid aliases',()=>{assert.equal(normalizeCountry('  U.S. '),'united states');assert.equal(normalizeCountry('Brásil'),'brazil');assert.deepEqual(countryCentroid('UK'),countryCentroid('United Kingdom'))})
test('marker radius is square-root scaled and bounded',()=>{assert.equal(markerRadius(0),5);assert.ok(markerRadius(4)>markerRadius(1));assert.equal(markerRadius(10000),18)})
test('closed ratio is mathematically exact and clamps invalid inputs',()=>{for(const value of [0,.1,.5,.9,1])assert.equal(closedRatio(value*10,10),value);for(const [closed,count,expected] of [[-1,10,0],[11,10,1],[1,0,0],['bad',10,0],[1,'bad',0]])assert.equal(closedRatio(closed,count),expected)})
test('map model sorts by count, retains unmapped rows, and projects closed ratio',()=>{const model=buildCountryMapModel([{country:'Atlantis',count:2,closed:1},{country:'Belgium',count:4,closed:1},{country:'Brazil',count:2,closed:0}]);assert.deepEqual(model.map(x=>x.country),['Belgium','Atlantis','Brazil']);assert.equal(model[0].centroid.length,2);assert.equal(model[0].closedRatio,.25);assert.equal(model[1].centroid,null)})
test('keyboard, accessible label/plural, and selection helpers are exact',()=>{assert.equal(isKeyboardActivation({key:'Enter'}),true);assert.equal(isKeyboardActivation({key:' '}),true);for(const key of ['Escape','Spacebar','a'])assert.equal(isKeyboardActivation({key}),false);assert.equal(markerAccessibleLabel('Belgium',1),'Belgium: 1 application. Show matching opportunities.');assert.match(markerAccessibleLabel('Brazil',2),/2 applications/);assert.equal(isMarkerSelected(' U.S. ','United States'),true);assert.equal(isMarkerSelected('Brazil','Belgium'),false)})
test('component and CSS integrate accessible interaction with a visible proportional ring',()=>{const source=fs.readFileSync(new URL('../client/src/pages/CountryMap.jsx',import.meta.url),'utf8'),css=fs.readFileSync(new URL('../client/src/index.css',import.meta.url),'utf8');for(const contract of ['role="button"','tabIndex="0"','aria-pressed={active}','strokeDasharray={`${row.closedRatio*circumference} ${circumference}`}','transform={`rotate(-90','Proportional closed share','Not mapped:','authoritative accessible list'])assert.match(source,new RegExp(contract.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(css,/\.map-closed\{[^}]*fill:none;[^}]*stroke:var\(--color-muted\)/);assert.doesNotMatch(css,/\.map-closed\{[^}]*fill:var\(/)})
