import test from 'node:test'
import assert from 'node:assert/strict'
import os from 'node:os'
import path from 'node:path'
import { promises as fs } from 'node:fs'
import { IntakeStore, sanitizeFilename, validatePublicUrl, retrievePublicUrl, createPinnedLookup, MAX_INTAKE_BYTES, MAX_URL_BYTES } from './intakes.js'

test('sanitizes filenames and rejects paths/extensions',()=>{assert.equal(sanitizeFilename('../../job role.md'),'job_role.md');assert.throws(()=>sanitizeFilename('x.exe'))})
test('accepts only credential-free http/https URL references',()=>{assert.match(validatePublicUrl('https://example.com/job'),/^https:/);assert.throws(()=>validatePublicUrl('file:///etc/passwd'));assert.throws(()=>validatePublicUrl('http://u:p@example.com'))})
test('creates bounded text/file manifests in UUID directories',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'intakes-'));const store=new IntakeStore(root);const text=await store.create({type:'text',text:'hello'});assert.match(text.id,/^[0-9a-f-]{36}$/);assert.equal(await fs.readFile(text.source.path,'utf8'),'hello');const file=await store.create({type:'file',filename:'job.md',mime:'text/markdown',base64:Buffer.from('safe').toString('base64')});assert.equal(file.size,4);await assert.rejects(store.create({type:'file',filename:'x.pdf',mime:'text/plain',base64:'eA=='}));await assert.rejects(store.create({type:'file',filename:'x.txt',base64:'%%%'}));await assert.rejects(store.create({type:'text',text:'x'.repeat(MAX_INTAKE_BYTES+1)}));await fs.rm(root,{recursive:true,force:true})})
test('TTL cleanup removes expired UUID intake directories',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'intakes-'));let now=100000;const store=new IntakeStore(root,{ttlMs:10,now:()=>now});const item=await store.create({type:'text',text:'x'});await fs.utimes(path.join(root,item.id),new Date(0),new Date(0));await store.cleanup();await assert.rejects(fs.stat(path.join(root,item.id)));await fs.rm(root,{recursive:true,force:true})})

const resolverFor=address=>async()=>[{address}]
const textResponse=(text,headers={})=>new Response(text,{status:200,headers:{'content-type':'text/plain',...headers}})
test('controlled URL intake rejects every private IPv4 and IPv6 class',async()=>{for(const address of ['0.1.2.3','10.1.2.3','127.0.0.1','169.254.1.2','172.16.0.1','172.31.255.255','192.168.1.1','224.0.0.1','255.255.255.255','::','::1','fe80::1','fc00::1','fd12::1','ff02::1','::ffff:192.168.1.1'])await assert.rejects(retrievePublicUrl('https://jobs.test/x',{resolver:resolverFor(address),fetchFn:()=>assert.fail('fetch must not run')}),/private, local, reserved, or multicast/)})
test('public DNS resolution is fetched with manual redirects and accepted content',async()=>{const calls=[];const out=await retrievePublicUrl('https://jobs.test/x',{resolver:resolverFor('93.184.216.34'),fetchFn:(url,options)=>{calls.push({url:String(url),options});return textResponse('This is a sufficiently detailed public job description.')}});assert.match(out.text,/public job/);assert.equal(calls[0].options.redirect,'manual');assert.ok(calls[0].options.dispatcher);assert.equal(calls[0].options.headers.accept.includes('text/html'),true)})
test('each hop uses an exact address-pinned dispatcher with correct family and closes it',async()=>{const made=[],closed=[],addresses=[{address:'93.184.216.34',family:4},{address:'2606:4700:4700::1111',family:6}];let resolution=0,fetches=0;const dispatcherFactory=pin=>{made.push(pin);return{pin,close:async()=>closed.push(pin.address)}};const out=await retrievePublicUrl('https://one.test/x',{resolver:async()=>[addresses[resolution++]],dispatcherFactory,fetchFn:(_url,{dispatcher})=>{assert.equal(dispatcher.pin.address,addresses[fetches].address);return fetches++===0?new Response(null,{status:302,headers:{location:'https://two.test/job'}}):textResponse('This is a sufficiently detailed redirected job description.')}});assert.match(out.url,/two\.test/);assert.deepEqual(made.map(x=>[x.hostname,x.address,x.family]),[['one.test','93.184.216.34',4],['two.test','2606:4700:4700::1111',6]]);assert.deepEqual(closed,addresses.map(x=>x.address))})
test('pinned lookup returns only the validated address and family',()=>{const lookup=createPinnedLookup({hostname:'jobs.test',address:'2606:4700:4700::1111',family:6});lookup('jobs.test',{},(error,address,family)=>{assert.ifError(error);assert.equal(address,'2606:4700:4700::1111');assert.equal(family,6)});lookup('other.test',{},error=>assert.match(error.message,/mismatch/))})
test('pinned lookup cannot be changed by a second resolver result',async()=>{let resolverCalls=0,lookupResult;await retrievePublicUrl('https://jobs.test/x',{resolver:async()=>{resolverCalls++;return resolverCalls===1?[{address:'93.184.216.34',family:4}]:[{address:'127.0.0.1',family:4}]},dispatcherFactory:pin=>({pin,close:async()=>{}}),fetchFn:(_url,{dispatcher})=>{lookupResult=dispatcher.pin;return textResponse('This is a sufficiently detailed public job description.')}});assert.equal(resolverCalls,1);assert.equal(lookupResult.address,'93.184.216.34')})
test('dispatcher closes on fetch error and timeout',async()=>{for(const timeout of [false,true]){let closed=0;await assert.rejects(retrievePublicUrl('https://jobs.test/x',{resolver:resolverFor('93.184.216.34'),dispatcherFactory:()=>({close:async()=>closed++}),setTimer:timeout?(fn=>{queueMicrotask(fn);return 1}):setTimeout,clearTimer:timeout?(()=>{}):clearTimeout,fetchFn:timeout?((_u,{signal})=>new Promise((_r,reject)=>signal.addEventListener('abort',()=>reject(Object.assign(new Error(),{name:'AbortError'}))))):(()=>Promise.reject(new Error('boom')))}),timeout?/timed out/:/could not/);assert.equal(closed,1)}})
test('redirects are revalidated at each hop and private redirects are rejected',async()=>{const resolved=[];await assert.rejects(retrievePublicUrl('https://public.test/x',{resolver:async host=>{resolved.push(host);return resolverFor(host==='public.test'?'93.184.216.34':'127.0.0.1')()},fetchFn:()=>new Response(null,{status:302,headers:{location:'http://private.test/secret'}})}),/private/);assert.deepEqual(resolved,['public.test','private.test'])})
test('redirect limit is enforced without an extra fetch',async()=>{let calls=0;await assert.rejects(retrievePublicUrl('https://jobs.test/x',{resolver:resolverFor('93.184.216.34'),maxRedirects:1,fetchFn:()=>{calls++;return new Response(null,{status:302,headers:{location:'/again'}})}}),/redirect limit/);assert.equal(calls,2)})
test('timeout aborts injected fetch and clears injected timer',async()=>{let cleared=false;await assert.rejects(retrievePublicUrl('https://jobs.test/x',{resolver:resolverFor('93.184.216.34'),setTimer:fn=>{queueMicrotask(fn);return 7},clearTimer:id=>{assert.equal(id,7);cleared=true},fetchFn:(_u,{signal})=>new Promise((_r,reject)=>signal.addEventListener('abort',()=>reject(Object.assign(new Error('abort'),{name:'AbortError'}))))}),/timed out/);assert.equal(cleared,true)})
test('content type and declared or streamed size are bounded',async()=>{await assert.rejects(retrievePublicUrl('https://jobs.test/x',{resolver:resolverFor('93.184.216.34'),fetchFn:()=>new Response('binary',{headers:{'content-type':'application/octet-stream'}})}),/not suitable text/);await assert.rejects(retrievePublicUrl('https://jobs.test/x',{resolver:resolverFor('93.184.216.34'),fetchFn:()=>textResponse('small',{'content-length':String(MAX_URL_BYTES+1)})}),/exceeds 1MB/);const chunk=new Uint8Array(MAX_URL_BYTES+1);let cancelled=false;let sent=false;const body=new ReadableStream({pull(c){if(!sent){sent=true;c.enqueue(chunk)}},cancel(){cancelled=true}});await assert.rejects(retrievePublicUrl('https://jobs.test/x',{resolver:resolverFor('93.184.216.34'),fetchFn:()=>new Response(body,{headers:{'content-type':'text/plain'}})}),/exceeds 1MB/);assert.equal(cancelled,true)})
test('malformed or unsuitable extraction fails closed',async()=>{for(const response of [textResponse(''),textResponse('too short'),new Response('<script>secret()</script><style>x{}</style>',{headers:{'content-type':'text/html'}})])await assert.rejects(retrievePublicUrl('https://jobs.test/x',{resolver:resolverFor('93.184.216.34'),fetchFn:()=>response}),/no suitable job text/)})
