import crypto from 'node:crypto'
import path from 'node:path'
import net from 'node:net'
import dns from 'node:dns/promises'
import { promises as fs } from 'node:fs'
import { Agent } from 'undici'

export const MAX_INTAKE_BYTES = 5 * 1024 * 1024
export const MAX_URL_BYTES = 1024 * 1024
export const INTAKE_TTL_MS = 24 * 60 * 60 * 1000
const MIME = Object.freeze({ '.txt': 'text/plain', '.md': 'text/markdown', '.pdf': 'application/pdf' })
const URL_TYPES = new Set(['text/plain','text/html','text/markdown','application/xhtml+xml'])
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i
const fail=(message,statusCode=400)=>Object.assign(new Error(message),{statusCode})

export function sanitizeFilename(value = '') { const base=path.basename(String(value)).normalize('NFKC').replace(/[^a-zA-Z0-9._-]+/g,'_').replace(/^\.+/,'').slice(0,120);if(!base||!MIME[path.extname(base).toLowerCase()])throw fail('Only .txt, .md, and .pdf files are supported');return base }
export function validatePublicUrl(value) { let url;try{url=new URL(value)}catch{throw fail('A valid public http/https URL is required')}if(!['http:','https:'].includes(url.protocol))throw fail('Only http/https URLs are accepted');if(url.username||url.password)throw fail('Credential-bearing URLs are not accepted');return url.toString() }
function privateIp(address){
 const ip=net.isIP(address);if(!ip)return true
 if(ip===4){const p=address.split('.').map(Number),n=((p[0]<<24)>>>0)+(p[1]<<16)+(p[2]<<8)+p[3];return p[0]===0||p[0]===10||p[0]===127||p[0]>=224||p[0]===169&&p[1]===254||p[0]===172&&p[1]>=16&&p[1]<=31||p[0]===192&&p[1]===168||p[0]===100&&p[1]>=64&&p[1]<=127||p[0]===198&&[18,19].includes(p[1])||p[0]===192&&p[1]===0&&p[2]===0||p[0]===192&&p[1]===0&&p[2]===2||p[0]===198&&p[1]===51&&p[2]===100||p[0]===203&&p[1]===0&&p[2]===113||p[0]===192&&p[1]===88&&p[2]===99||p[0]===192&&p[1]===31&&p[2]===196||n===0xffffffff}
 const x=address.toLowerCase().split('%')[0];if(x.startsWith('::ffff:')){const mapped=x.slice(7);return net.isIP(mapped)!==4||privateIp(mapped)}return x==='::'||x==='::1'||x.startsWith('fc')||x.startsWith('fd')||/^fe[89ab]/.test(x)||x.startsWith('ff')||x.startsWith('2001:db8:')
}
async function resolvePublicHost(url,resolver){const literal=net.isIP(url.hostname)?[{address:url.hostname,family:net.isIP(url.hostname)}]:await resolver(url.hostname,{all:true,verbatim:true});if(!literal.length||literal.some(x=>privateIp(x.address)))throw fail('URL host resolves to a private, local, reserved, or multicast address',400);const selected=literal[0],family=selected.family||net.isIP(selected.address);if(!family)throw fail('URL host resolution returned an invalid address',400);return {address:selected.address,family}}
export function createPinnedLookup({hostname,address,family}){return (requested,_options,callback)=>{if(requested!==hostname)return callback(new Error('Pinned dispatcher hostname mismatch'));callback(null,address,family)}}
export function createPinnedDispatcher(pin){return new Agent({connect:{lookup:createPinnedLookup(pin)}})}
function htmlText(raw){return raw.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+/g,' ').trim()}
export async function retrievePublicUrl(value,{resolver=dns.lookup,fetchFn=fetch,dispatcherFactory=createPinnedDispatcher,timeoutMs=8000,maxRedirects=3,setTimer=setTimeout,clearTimer=clearTimeout}={}){
 let current=new URL(validatePublicUrl(value));for(let hop=0;hop<=maxRedirects;hop++){const pinned=await resolvePublicHost(current,resolver),dispatcher=dispatcherFactory({hostname:current.hostname,...pinned,url:current});const controller=new AbortController(),timer=setTimer(()=>controller.abort(),timeoutMs);try{let response;try{response=await fetchFn(current,{redirect:'manual',signal:controller.signal,dispatcher,headers:{accept:'text/plain, text/markdown, text/html, application/xhtml+xml'}})}catch(e){throw fail(e.name==='AbortError'?'URL retrieval timed out':'URL could not be retrieved',422)}
  if(response.status>=300&&response.status<400){const location=response.headers.get('location');if(!location||hop===maxRedirects)throw fail('URL redirect limit exceeded',422);current=new URL(validatePublicUrl(new URL(location,current).toString()));continue}
  if(!response.ok)throw fail(`URL retrieval failed with status ${response.status}`,422);const type=(response.headers.get('content-type')||'').split(';')[0].trim().toLowerCase();if(!URL_TYPES.has(type))throw fail('URL content is not suitable text; paste the text or upload a supported file instead',422);const declared=Number(response.headers.get('content-length'));if(Number.isFinite(declared)&&declared>MAX_URL_BYTES)throw fail('URL response exceeds 1MB',413);const reader=response.body.getReader();let size=0,chunks=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>MAX_URL_BYTES){await reader.cancel();throw fail('URL response exceeds 1MB',413)}chunks.push(value)}const raw=Buffer.concat(chunks.map(x=>Buffer.from(x))).toString('utf8');const text=type.includes('html')?htmlText(raw):raw.trim();if(!text||text.length<20)throw fail('URL extraction produced no suitable job text; paste the text or upload a supported file instead',422);return {url:current.toString(),text,size:Buffer.byteLength(text)}}finally{clearTimer(timer);await dispatcher.close()}}throw fail('URL redirect limit exceeded',422)
}
function decodeBase64(value){if(typeof value!=='string'||!value.length||!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(value))throw fail('Invalid base64 file content');const data=Buffer.from(value,'base64');if(data.length>MAX_INTAKE_BYTES)throw fail('Intake exceeds 5MB',413);return data}
export class IntakeStore{
 constructor(root,{ttlMs=INTAKE_TTL_MS,now=()=>Date.now(),urlRetriever=retrievePublicUrl}={}){this.root=path.resolve(root);this.ttlMs=ttlMs;this.now=now;this.urlRetriever=urlRetriever}
 async cleanup(){await fs.mkdir(this.root,{recursive:true,mode:0o700});for(const entry of await fs.readdir(this.root,{withFileTypes:true})){if(!entry.isDirectory()||!UUID.test(entry.name))continue;const target=path.join(this.root,entry.name),stat=await fs.stat(target);if(this.now()-stat.mtimeMs>this.ttlMs)await fs.rm(target,{recursive:true,force:true})}}
 async create(input={}){await this.cleanup();const type=input.type,id=crypto.randomUUID(),dir=path.join(this.root,id);await fs.mkdir(dir,{mode:0o700});let source={},filename=null,size=0;try{if(type==='url'){const fetched=await this.urlRetriever(input.url);filename='source.txt';size=fetched.size;await fs.writeFile(path.join(dir,filename),fetched.text,{mode:0o600});source={url:fetched.url,path:path.join(dir,filename),mime:'text/plain',retrieved:true}}
 else if(type==='text'){const data=Buffer.from(String(input.text||''));if(!data.length)throw fail('Pasted text is required');if(data.length>MAX_INTAKE_BYTES)throw fail('Intake exceeds 5MB',413);filename='source.txt';size=data.length;await fs.writeFile(path.join(dir,filename),data,{mode:0o600});source.path=path.join(dir,filename)}
 else if(type==='file'){filename=sanitizeFilename(input.filename);const ext=path.extname(filename).toLowerCase();if(input.mime&&input.mime!==MIME[ext])throw fail('File MIME does not match its extension');const data=decodeBase64(input.base64);size=data.length;await fs.writeFile(path.join(dir,filename),data,{mode:0o600});source={path:path.join(dir,filename),mime:MIME[ext],pdf:ext==='.pdf'}}else throw fail('Intake type must be url, text, or file');const manifest={id,type,filename,size,createdAt:new Date(this.now()).toISOString(),source};await fs.writeFile(path.join(dir,'manifest.json'),JSON.stringify(manifest,null,2),{mode:0o600});return manifest}catch(e){await fs.rm(dir,{recursive:true,force:true});throw e}}
 async get(id){await this.cleanup();if(!UUID.test(id||''))throw fail('Invalid intake ID');try{return JSON.parse(await fs.readFile(path.join(this.root,id,'manifest.json'),'utf8'))}catch{throw fail('Intake not found or expired',404)}}
 public(manifest){return {id:manifest.id,type:manifest.type,filename:manifest.filename,size:manifest.size,createdAt:manifest.createdAt,source:{mime:manifest.source.mime||null,pdf:Boolean(manifest.source.pdf),retrieved:Boolean(manifest.source.retrieved),url:manifest.source.url||undefined}}}
}
