import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import { applicationActionsView } from '../client/src/applicationViewModel.js'
import { buildCommandPayload } from '../client/src/quickUpdateModel.js'

const gates={
 'job-source':{type:'action',label:'Add job source and analyze fit',action:'generate-fit-analysis'},
 fit:{type:'action',label:'Generate fit analysis',action:'generate-fit-analysis'},
 'reuse-evidence':{type:'quick-update',label:'Confirm company and people review',focus:'application.recordReuseAssessment'},
 'dominant-narrative':{type:'quick-update',label:'Choose dominant narrative',focus:'application.selectDominantNarrative'},
 cv:{type:'action',label:'Create tailored CV',action:'create-cv'},
 'cover-letter':{type:'action',label:'Generate cover letter',action:'generate-cover-letter'},
 'metadata-index':{type:'quick-update',label:'Repair application record',focus:'application.repairRecord'},
}
test('every preparation gate maps to an exact actionable CTA, never a generic overview no-op',()=>{for(const [id,expected] of Object.entries(gates)){const app={lifecycle:{status:'to_apply'},preparation:{steps:[{id,label:id,complete:false}]},actions:{}};assert.deepEqual(applicationActionsView(app).primary,expected)}const source=fs.readFileSync(new URL('../client/src/pages/ApplicationDetail.jsx',import.meta.url),'utf8');assert.doesNotMatch(source,/Continue preparation/);assert.match(source,/openDoc\(\{fit:'fitAnalysis',cv:'cv','cover-letter':'coverLetter'\}\[step.id\]\)/)})

test('Quick Update builds exact typed payloads for every visible command',()=>{const now='2026-08-20T10:00:00.000Z';assert.deepEqual(buildCommandPayload('application.setPriority',{priority:'high'},now),{priority:'high'});assert.deepEqual(buildCommandPayload('application.setLocation',{country:' BE ',location:' Brussels '},now),{country:'BE',location:'Brussels'});assert.deepEqual(buildCommandPayload('application.setSource',{url:'https://example.test/job',reference:'x'},now),{url:'https://example.test/job',reference:null});assert.deepEqual(buildCommandPayload('application.recordReuseAssessment',{note:' reviewed '},now),{reviewed:true,note:'reviewed',reviewed_at:now});assert.deepEqual(buildCommandPayload('application.selectDominantNarrative',{narrative:'AI Transformation Leader'},now),{narrative:'AI Transformation Leader'});assert.deepEqual(buildCommandPayload('application.recordSubmission',{occurredAt:'2026-08-20',channel:' portal ',note:''},now),{occurredAt:'2026-08-20',channel:'portal',note:null,artifactVersions:{}});assert.deepEqual(buildCommandPayload('application.recordEmployerResponse',{responseType:'screening',occurredAt:'2026-08-20',note:'ok',lifecycleTarget:'recruiter_screen'},now),{responseType:'screening',occurredAt:'2026-08-20',note:'ok',lifecycleTarget:'recruiter_screen'});assert.deepEqual(buildCommandPayload('application.recordInterview',{occurredAt:'2026-08-20',interviewType:'panel',outcome:'next',note:'',lifecycleTarget:''},now),{occurredAt:'2026-08-20',interviewType:'panel',outcome:'next',note:null,lifecycleTarget:null});assert.deepEqual(buildCommandPayload('application.addNote',{note:' hello '},now),{note:'hello'})})

test('visible source contracts cover command concurrency, runs states, IA, Companies and query roundtrip',()=>{const read=p=>fs.readFileSync(new URL(p,import.meta.url),'utf8'),quick=read('../client/src/components/QuickUpdatePanel.jsx'),runs=read('../client/src/components/RecentRuns.jsx'),today=read('../client/src/pages/Today.jsx'),detail=read('../client/src/pages/ApplicationDetail.jsx'),app=read('../client/src/App.jsx'),companies=read('../client/src/pages/Companies.jsx');for(const text of ['idempotencyKey:id','expectedRevision:app.revision','err.status===412','err.status===409','err.status===422','aria-live="polite"','window.confirm'])assert.ok(quick.includes(text),text);for(const text of ['getApplicationRuns(slug)','getRecentRuns()','Loading recent runs','Could not load recent runs','No generation runs','Retry or inspect'])assert.ok(runs.includes(text),text);assert.ok(today.includes('<RecentRuns />'));assert.ok(detail.includes('<RecentRuns slug={slug}/>'));assert.match(app,/\['\/companies', 'Companies',/);assert.ok(companies.includes("params.get('q')"));assert.ok(companies.includes("next.set('q',value)"))})
