import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { acquireVaultLocks } from '../lockAdapter.js'
import { runVaultTransaction } from '../transactionJournal.js'
import { counts, fail, json, loadCanonical, shaFile, validateApplication, validateModel } from './model.js'

const TYPES=new Set(['application.recordSubmission','application.recordOutreach']),DATE=/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v
const digest=v=>crypto.createHash('sha256').update(JSON.stringify(stable(v))).digest('hex'),unique=x=>[...new Set(x)]
const exact=(x,required,optional=[])=>x&&typeof x==='object'&&!Array.isArray(x)&&required.every(k=>Object.hasOwn(x,k))&&Object.keys(x).every(k=>required.includes(k)||optional.includes(k))
function validateCommand(c){const envelope=['schemaVersion','commandId','idempotencyKey','expectedRevision','applicationId','type','payload'],submission=['note','artifactIds','transmittedArtifactIds','interactionId'],outreach=['note','personIds','messageArtifactId','interactionId'];if(!exact(c,envelope)||c.schemaVersion!==1||!TYPES.has(c.type)||typeof c.commandId!=='string'||!c.commandId||typeof c.idempotencyKey!=='string'||!c.idempotencyKey||typeof c.applicationId!=='string'||!c.applicationId.startsWith('application:')||!Number.isSafeInteger(c.expectedRevision)||c.expectedRevision<0||!exact(c.payload,['occurredAt','channel'],c.type.endsWith('Submission')?submission:outreach)||!DATE.test(c.payload.occurredAt)||typeof c.payload.channel!=='string'||!c.payload.channel.trim())fail('Invalid command envelope','INVALID_COMMAND');for(const k of ['artifactIds','transmittedArtifactIds','personIds'])if(c.payload[k]!=null&&(!Array.isArray(c.payload[k])||c.payload[k].some(x=>typeof x!=='string'||!x.includes(':'))))fail(`Invalid ${k}`,'INVALID_COMMAND');if(c.payload.messageArtifactId!=null&&(!String(c.payload.messageArtifactId).startsWith('artifact:')))fail('Invalid messageArtifactId','INVALID_COMMAND');if(c.payload.interactionId!=null&&(!String(c.payload.interactionId).startsWith('interaction:')))fail('Invalid interactionId','INVALID_COMMAND');if(c.payload.note!=null&&typeof c.payload.note!=='string')fail('Invalid note','INVALID_COMMAND')}
const finals=(m,id,role)=>m.artifacts.filter(a=>a.owner_type==='application'&&a.owner_id===id&&a.document?.role===role&&a.document.representation==='canonical_markdown'&&a.document.state==='final'&&a.document.primary)
function one(m,id,role){const x=finals(m,id,role);if(x.length!==1)fail(`${id} requires exactly one primary final ${role}; found ${x.length}`,'AMBIGUOUS_FINAL_ARTIFACT');return x[0]}
function owned(m,id,artifactId){const a=m.artifacts.find(x=>x.id===artifactId);if(!a||a.owner_type!=='application'||a.owner_id!==id)fail(`Artifact ${artifactId} is not owned by ${id}`,'INVALID_ARTIFACT_SELECTION');return a}
function verifyFrozen(root,m,id){const errors=[];for(const i of m.interactions.filter(x=>x.application_id===id)){for(const x of i.submission_bundle?.items||[])for(const [artifactId,hash] of [[x.artifact_id,x.sha256],[x.transmitted_artifact_id,x.transmitted_sha256]])if(artifactId){const a=m.artifacts.find(y=>y.id===artifactId),file=a&&path.join(root,'Candidatures',a.path);if(!a||a.sha256!==hash||!fs.existsSync(file)||shaFile(file)!==hash)errors.push(`${i.id} frozen artifact changed: ${artifactId}`)}if(i.transmission){const a=m.artifacts.find(y=>y.id===i.transmission.message_artifact_id),file=a&&path.join(root,'Candidatures',a.path);if(!a||a.sha256!==i.transmission.message_sha256||!fs.existsSync(file)||shaFile(file)!==i.transmission.message_sha256)errors.push(`${i.id} frozen outreach message changed`)}}if(errors.length)fail('Submitted or transmitted artifact immutability check failed','FROZEN_ARTIFACT_CHANGED',{errors})}
function submissionItems(m,c){const explicit=c.payload.artifactIds!=null,sources=explicit?c.payload.artifactIds.map(x=>owned(m,c.applicationId,x)):[one(m,c.applicationId,'cv'),one(m,c.applicationId,'application_letter'),...finals(m,c.applicationId,'application_answer')];const answerKeys=finals(m,c.applicationId,'application_answer').map(x=>x.document.answer_key);if(!explicit&&new Set(answerKeys).size!==answerKeys.length)fail('Ambiguous application answers','AMBIGUOUS_FINAL_ARTIFACT');const sourceIds=new Set(sources.map(x=>x.id)),renditions=new Map();for(const id of c.payload.transmittedArtifactIds||[]){const r=owned(m,c.applicationId,id),source=r.document?.source_artifact_id;if(r.document?.representation!=='generated_docx'||!sourceIds.has(source)||renditions.has(source))fail('Invalid generated rendition selection','INVALID_ARTIFACT_SELECTION');renditions.set(source,r)}return sources.map(a=>{const r=renditions.get(a.id);return{role:a.document?.role||a.kind,answer_key:a.document?.answer_key||null,artifact_id:a.id,version:a.document?.version||1,sha256:a.sha256,transmitted_artifact_id:r?.id||null,transmitted_sha256:r?.sha256||null}})}
function interactionId(appId,kind,at,channel){return `interaction:${appId.slice(12)}:${kind}-${at.replace(/[^0-9]/g,'').slice(0,14)}-${channel.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}`}
function record(m,c,now){const app=m.applications.find(x=>x.id===c.applicationId);if(!app)fail(`Application not found: ${c.applicationId}`,'APPLICATION_NOT_FOUND');const id=c.payload.interactionId||interactionId(app.id,c.type.endsWith('Submission')?'submission':'outreach',c.payload.occurredAt,c.payload.channel);if(m.interactions.some(x=>x.id===id))fail(`Interaction already exists: ${id}`,'INTERACTION_CONFLICT');let i;if(c.type.endsWith('Submission')){if(['rejected','withdrawn','archived'].includes(app.lifecycle_status))fail('Cannot submit a terminal Application','TERMINAL_APPLICATION');const items=submissionItems(m,c);i={id,application_id:app.id,vacancy_id:app.vacancy_id,person_ids:[],kind:'submission',evidence_state:'confirmed',occurred_at:c.payload.occurredAt,artifact_ids:unique(items.flatMap(x=>[x.artifact_id,x.transmitted_artifact_id].filter(Boolean))).sort(),submission_bundle:{schema_version:1,selection_mode:c.payload.artifactIds==null?'default_final':'explicit_override',channel:c.payload.channel.trim(),confirmed_at:c.payload.occurredAt,note:c.payload.note?.trim()||null,items},provenance:[`command:${c.commandId}`]};app.lifecycle_status='applied'}else{const explicit=c.payload.messageArtifactId!=null,message=explicit?owned(m,app.id,c.payload.messageArtifactId):one(m,app.id,'outreach_message');if(message.document?.representation!=='canonical_markdown'||message.document?.state!=='final')fail('Outreach message must be final canonical Markdown','INVALID_ARTIFACT_SELECTION');const people=c.payload.personIds||(app.people_relations||[]).filter(x=>x.relationship_role?.includes('contact')).map(x=>x.person_id);for(const p of people)if(!m.people.some(x=>x.id===p))fail(`Person not found: ${p}`,'INVALID_PERSON_ID');i={id,application_id:app.id,vacancy_id:app.vacancy_id,person_ids:unique(people).sort(),kind:'outreach',evidence_state:'confirmed',occurred_at:c.payload.occurredAt,artifact_ids:[message.id],transmission:{schema_version:1,selection_mode:explicit?'explicit_override':'default_final',channel:c.payload.channel.trim(),sent_at:c.payload.occurredAt,confirmed_at:now.toISOString(),message_artifact_id:message.id,message_sha256:message.sha256,note:c.payload.note?.trim()||null},provenance:[`command:${c.commandId}`]}}
 m.interactions.push(i);app.interaction_ids=unique([...(app.interaction_ids||[]),i.id]).sort();app.updated=c.payload.occurredAt.slice(0,10);app.source_revision+=1;app.provenance=unique([...(app.provenance||[]),`command:${c.commandId}`]);return{app,interaction:i}}

export function executeRelationalCommand({paths,command,actor='local-user',now=new Date(),deps={}}){validateCommand(command);const root=paths.vaultRoot,cand=paths.candidaturesDir||path.join(root,'Candidatures'),records=paths.recordsDir||path.join(cand,'records'),ledger=path.join(paths.stateRoot||path.join(root,'.nextstep'),'transactions','relational-commands','ledger.json'),audit=paths.auditLogPath||path.join(root,'.coordination','audit-log.md'),targets=['applications.json','interactions.json','artifacts.json','manifest.json'].map(x=>path.join(records,x)).concat([audit,ledger]),lease=(deps.acquireLocks||acquireVaultLocks)({vaultRoot:root,lockDir:paths.locksDir,targets,taskId:`command-${command.commandId}`,operation:'relational-command',runTool:deps.lockCommand});let primary;try{let l={schema_version:1,entries:{}};if(fs.existsSync(ledger))try{l=JSON.parse(fs.readFileSync(ledger,'utf8'))}catch{fail('Invalid relational command ledger','INVALID_LEDGER')}const key=`${command.applicationId}|${command.idempotencyKey}`,d=digest(command),prior=l.entries?.[key],m=loadCanonical(cand),app=m.applications.find(x=>x.id===command.applicationId);if(!app)fail(`Application not found: ${command.applicationId}`,'APPLICATION_NOT_FOUND');verifyFrozen(root,m,command.applicationId);if(prior){if(prior.digest!==d)fail('Idempotency key conflict','IDEMPOTENCY_CONFLICT');return prior.result}if(app.source_revision!==command.expectedRevision)fail(`Expected revision ${command.expectedRevision}; current revision is ${app.source_revision}`,'STALE_REVISION');const changed=record(m,command,now);validateModel(m,{allowIncomplete:true});const manifest=JSON.parse(fs.readFileSync(path.join(records,'manifest.json'),'utf8')),result={status:'recorded',commandId:command.commandId,type:command.type,applicationId:command.applicationId,interactionId:changed.interaction.id,revision:changed.app.source_revision,previousRevision:command.expectedRevision};l.entries||={};l.entries[key]={digest:d,result};const old=fs.existsSync(audit)?fs.readFileSync(audit,'utf8'):'# Audit Log\n',outputs=new Map([[path.join(records,'applications.json'),json(m.applications)],[path.join(records,'interactions.json'),json(m.interactions)],[path.join(records,'artifacts.json'),json(m.artifacts)],[path.join(records,'manifest.json'),json({...manifest,counts:counts(m)})],[ledger,json(l)],[audit,`${old.trimEnd()}\n\n- ${now.toISOString()} | ${actor} | ${command.commandId} | ${command.type} | ${command.applicationId} | ${changed.interaction.id}\n`]]);runVaultTransaction({paths,kind:'relational-command',context:{applicationId:command.applicationId,commandId:command.commandId},outputs,lease,deps:deps.transaction});validateApplication(cand,command.applicationId);return result}catch(e){primary=e;throw e}finally{lease.releaseAll({suppress:Boolean(primary)})}}
