import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'

export const RECORD_TYPES = Object.freeze(['companies','vacancies','applications','people','interactions','artifacts'])
const PREFIXES={companies:'company',vacancies:'vacancy',applications:'application',people:'person',interactions:'interaction',artifacts:'artifact'}
const LIFECYCLES=new Set(['identified','to_apply','applied','recruiter_screen','interview','offer','rejected','withdrawn','archived'])
export const json=value=>`${JSON.stringify(value,null,2)}\n`
export const sha=value=>crypto.createHash('sha256').update(value).digest('hex')
export const shaFile=file=>sha(fs.readFileSync(file))
export const counts=model=>Object.fromEntries(RECORD_TYPES.map(key=>[key,model[key].length]))
export function fail(message,code='RELATIONAL_FAILED',context={}){throw Object.assign(new Error(message),{code,...context})}
const unique=values=>[...new Set(values)]
const sameIds=(a,b)=>JSON.stringify(unique(a||[]).sort())===JSON.stringify(unique(b||[]).sort())

export function loadCanonical(candidaturesRoot){const model={};for(const key of RECORD_TYPES){const file=path.join(candidaturesRoot,'records',`${key}.json`);if(!fs.existsSync(file))fail(`Missing canonical record file: ${key}.json`,'CANONICAL_MODEL_INCOMPLETE');model[key]=JSON.parse(fs.readFileSync(file,'utf8'))}return model}

export function validateModel(model,{allowIncomplete=false}={}){
 const errors=[],ids=new Map();for(const type of RECORD_TYPES){if(!Array.isArray(model[type])){errors.push(`${type} must be an array`);continue}for(const item of model[type]){if(typeof item.id!=='string'||!item.id.startsWith(`${PREFIXES[type]}:`))errors.push(`Invalid ${type} id: ${item.id}`);if(ids.has(item.id))errors.push(`Duplicate id: ${item.id}`);else ids.set(item.id,type)}}
 const sets=Object.fromEntries(RECORD_TYPES.map(k=>[k,new Set((model[k]||[]).map(x=>x.id))])),artifacts=new Map((model.artifacts||[]).map(x=>[x.id,x]))
 for(const c of model.companies||[]){if(!sameIds(c.vacancy_ids,(model.vacancies||[]).filter(x=>x.company_id===c.id).map(x=>x.id)))errors.push(`${c.id} vacancy backlinks differ`);if(!sameIds(c.person_ids,(model.people||[]).filter(x=>x.company_id===c.id).map(x=>x.id)))errors.push(`${c.id} person backlinks differ`)}
 for(const v of model.vacancies||[]){if(!sets.companies.has(v.company_id))errors.push(`${v.id} missing company ${v.company_id}`);if(!sameIds(v.application_ids,(model.applications||[]).filter(x=>x.vacancy_id===v.id).map(x=>x.id)))errors.push(`${v.id} application backlinks differ`)}
 for(const a of model.applications||[]){if(!sets.vacancies.has(a.vacancy_id))errors.push(`${a.id} missing vacancy ${a.vacancy_id}`);if(!Object.hasOwn(a,'lifecycle_status')||!Object.hasOwn(a,'outcome')||!Object.hasOwn(a,'storage_scope'))errors.push(`${a.id} must separate lifecycle_status, outcome, and storage_scope`);if(a.lifecycle_status!=null&&!LIFECYCLES.has(a.lifecycle_status))errors.push(`${a.id} invalid lifecycle ${a.lifecycle_status}`);if(!['active','archive'].includes(a.storage_scope))errors.push(`${a.id} invalid storage scope ${a.storage_scope}`);if(!allowIncomplete&&a.record_state==='incomplete')errors.push(`${a.id} is incomplete`);for(const x of a.people_relations||[])if(!sets.people.has(x.person_id))errors.push(`${a.id} missing person ${x.person_id}`);for(const x of a.interaction_ids||[])if(!sets.interactions.has(x))errors.push(`${a.id} missing interaction ${x}`);for(const x of a.artifact_ids||[])if(!sets.artifacts.has(x))errors.push(`${a.id} missing artifact ${x}`)}
 for(const p of model.people||[]){const apps=(model.applications||[]).filter(x=>(x.people_relations||[]).some(r=>r.person_id===p.id)).map(x=>x.id),vacancies=apps.map(id=>(model.applications||[]).find(x=>x.id===id)?.vacancy_id).filter(Boolean);if(!sameIds(p.application_ids,apps))errors.push(`${p.id} application backlinks differ`);if(!sameIds(p.vacancy_ids,vacancies))errors.push(`${p.id} vacancy backlinks differ`)}
 for(const i of model.interactions||[]){if(i.application_id&&!sets.applications.has(i.application_id))errors.push(`${i.id} missing application ${i.application_id}`);for(const x of i.person_ids||[])if(!sets.people.has(x))errors.push(`${i.id} missing person ${x}`);for(const x of i.artifact_ids||[])if(!sets.artifacts.has(x))errors.push(`${i.id} missing artifact ${x}`);if(i.submission_bundle){const b=i.submission_bundle;if(i.kind!=='submission'||b.schema_version!==1||!['default_final','explicit_override'].includes(b.selection_mode)||!b.channel||!b.confirmed_at||!Array.isArray(b.items)||!b.items.length)errors.push(`${i.id} invalid submission bundle`);for(const x of b.items||[]){if(artifacts.get(x.artifact_id)?.sha256!==x.sha256)errors.push(`${i.id} submission hash mismatch ${x.artifact_id}`);if(x.transmitted_artifact_id&&artifacts.get(x.transmitted_artifact_id)?.sha256!==x.transmitted_sha256)errors.push(`${i.id} rendition hash mismatch ${x.transmitted_artifact_id}`)}}if(i.transmission){const t=i.transmission;if(i.kind!=='outreach'||t.schema_version!==1||!['default_final','explicit_override'].includes(t.selection_mode)||!t.channel||!t.sent_at||artifacts.get(t.message_artifact_id)?.sha256!==t.message_sha256)errors.push(`${i.id} invalid outreach transmission`)}}
 const ownerSet={company:sets.companies,vacancy:sets.vacancies,application:sets.applications,person:sets.people,interaction:sets.interactions},primary=new Set();for(const a of model.artifacts||[]){if(a.owner_type!=='shared'&&!ownerSet[a.owner_type]?.has(a.owner_id))errors.push(`${a.id} missing owner ${a.owner_id}`);if(a.document){const d=a.document;if(!['cv','application_letter','application_answer','outreach_message'].includes(d.role)||!['canonical_markdown','generated_docx'].includes(d.representation)||!['draft','final'].includes(d.state)||!Number.isSafeInteger(d.version)||d.version<1||typeof d.primary!=='boolean')errors.push(`${a.id} invalid document metadata`);if(d.representation==='canonical_markdown'&&(!a.path.endsWith('.md')||d.source_artifact_id!=null))errors.push(`${a.id} canonical source must be Markdown`);if(d.representation==='generated_docx'){const s=artifacts.get(d.source_artifact_id);if(!a.path.endsWith('.docx')||!s||s.sha256!==d.source_sha256||s.document?.representation!=='canonical_markdown'||s.document?.role!==d.role)errors.push(`${a.id} invalid generated DOCX source`)}if(d.representation==='canonical_markdown'&&d.state==='final'&&d.primary){const key=`${a.owner_id}\0${d.role}\0${d.answer_key||''}`;if(primary.has(key))errors.push(`${a.owner_id} has multiple primary final ${d.role}`);primary.add(key)}}}
 if(errors.length)fail(`Relational model validation failed with ${errors.length} error(s)`,'MODEL_INVALID',{errors});return{valid:true,errors:[]}
}

export function canonicalIssues(model){return [...model.applications.filter(x=>x.record_state==='incomplete').map(x=>({type:'incomplete_application_record',application:x.id})),...model.vacancies.filter(x=>x.source_url&&x.source_preservation!=='snapshot_preserved').map(x=>({type:'source_url_without_snapshot',vacancy:x.id,source_url:x.source_url}))]}
function validateManifest(root,model){const file=path.join(root,'records','manifest.json');if(!fs.existsSync(file))fail('Missing canonical manifest','CANONICAL_MODEL_INCOMPLETE');const m=JSON.parse(fs.readFileSync(file,'utf8')),errors=[];if(m.schema_version!==1)errors.push('Manifest schema_version must be 1');for(const [k,n] of Object.entries(counts(model)))if(m.counts?.[k]!==n)errors.push(`Manifest count for ${k} is ${m.counts?.[k]??'missing'}; expected ${n}`);if(errors.length)fail('Canonical manifest validation failed','MANIFEST_INVALID',{errors});return m}
export function validateStructure(root,{allowIncomplete=true}={}){const model=loadCanonical(root);validateModel(model,{allowIncomplete});validateManifest(root,model);return{valid:true,scope:'global_structure',counts:counts(model),findings:canonicalIssues(model).length}}
export function auditChecksums(root){const model=loadCanonical(root),errors=[];for(const a of model.artifacts){const file=path.join(root,a.path);if(!fs.existsSync(file))errors.push(`Missing artifact file ${a.path}`);else if(shaFile(file)!==a.sha256)errors.push(`Artifact checksum mismatch ${a.path}`)}if(errors.length)fail('Global checksum audit failed','CHECKSUM_AUDIT_FAILED',{errors});return{valid:true,scope:'global_checksums',checked_artifacts:model.artifacts.length}}
export function related(model,application){const interactionIds=new Set(application.interaction_ids||[]),interactions=model.interactions.filter(x=>x.application_id===application.id||interactionIds.has(x.id)),ids=new Set(application.artifact_ids||[]);for(const i of interactions){for(const x of i.artifact_ids||[])ids.add(x);for(const x of i.submission_bundle?.items||[]){ids.add(x.artifact_id);if(x.transmitted_artifact_id)ids.add(x.transmitted_artifact_id)}if(i.transmission?.message_artifact_id)ids.add(i.transmission.message_artifact_id)}return{interactions,artifacts:model.artifacts.filter(x=>ids.has(x.id))}}
export function validateApplication(root,applicationId,{verifyChecksums=true}={}){if(typeof applicationId!=='string'||!applicationId.startsWith('application:'))fail('A typed Application ID is required','INVALID_APPLICATION_ID');const model=loadCanonical(root),app=model.applications.find(x=>x.id===applicationId);if(!app)fail(`Application not found: ${applicationId}`,'APPLICATION_NOT_FOUND');const subset=related(model,app),errors=[];if(!model.vacancies.some(x=>x.id===app.vacancy_id))errors.push(`${app.id} missing vacancy`);for(const i of subset.interactions)if(i.application_id!==app.id)errors.push(`${i.id} belongs to another application`);for(const a of subset.artifacts){if(a.owner_type!=='application'||a.owner_id!==app.id)errors.push(`${a.id} is not owned by ${app.id}`);if(verifyChecksums){const file=path.join(root,a.path);if(!fs.existsSync(file)||shaFile(file)!==a.sha256)errors.push(`Artifact checksum mismatch ${a.path}`)}}if(errors.length)fail('Application validation failed','APPLICATION_INVALID',{errors});return{valid:true,scope:'application',application_id:app.id,checked:{applications:1,interactions:subset.interactions.length,artifacts:subset.artifacts.length}}}
