import fs from 'node:fs'
import path from 'node:path'
import { acquireVaultLocks } from '../lockAdapter.js'
import { runVaultTransaction } from '../transactionJournal.js'
import { canonicalIssues, counts, fail, json, loadCanonical, sha, shaFile, validateApplication, validateModel, validateStructure } from './model.js'

const cell=v=>String(v??'—').replaceAll('|','\\|').replaceAll('\n',' ')
const link=(from,to,label)=>`[${cell(label)}](${encodeURI(path.relative(path.dirname(from),to).replaceAll('\\','/'))})`
function render(root,m){const out=new Map(),file=n=>path.join(root,'indexes',n),art=new Map(m.artifacts.map(x=>[x.id,x])),companies=new Map(m.companies.map(x=>[x.id,x])),vacancies=new Map(m.vacancies.map(x=>[x.id,x]));out.set('indexes/index.md','# Career Model Index\n\n- [Companies](companies.md)\n- [Vacancies](vacancies.md)\n- [Applications](applications.md)\n- [People](people.md)\n- [Interactions](interactions.md)\n- [Artifacts](artifacts.md)\n- [Inconsistency report](../reports/inconsistencies.md)\n');const table=(name,headers,rows)=>out.set(`indexes/${name}.md`,`# ${name[0].toUpperCase()+name.slice(1)}\n\n| ${headers.join(' | ')} |\n|${headers.map(()=> '---').join('|')}|\n${rows.join('\n')}\n`);table('companies',['ID','Company','Vacancies','Profile'],m.companies.map(x=>{const a=x.profile_artifact_ids.map(id=>art.get(id)).find(Boolean);return`| ${cell(x.id)} | ${cell(x.name)} | ${x.vacancy_ids.length} | ${a?link(file('companies.md'),path.join(root,a.path),'profile'):'—'} |`}));table('vacancies',['ID','Company','Role','State','Snapshot'],m.vacancies.map(x=>{const a=x.snapshot_artifact_ids.map(id=>art.get(id)).find(Boolean);return`| ${cell(x.id)} | ${cell(companies.get(x.company_id)?.name)} | ${cell(x.title)} | ${cell(x.vacancy_state)} | ${a?link(file('vacancies.md'),path.join(root,a.path),'snapshot'):'—'} |`}));table('applications',['ID','Company','Role','Lifecycle','Outcome','Storage','Previous'],m.applications.map(x=>{const v=vacancies.get(x.vacancy_id);return`| ${cell(x.id)} | ${cell(companies.get(v?.company_id)?.name)} | ${cell(v?.title)} | ${cell(x.lifecycle_status)} | ${cell(x.outcome)} | ${cell(x.storage_scope)} | ${cell(x.previous_application_id)} |`}));table('people',['ID','Person','Company','Applications','Profile'],m.people.map(x=>{const a=x.profile_artifact_ids.map(id=>art.get(id)).find(Boolean);return`| ${cell(x.id)} | ${cell(x.name)} | ${cell(companies.get(x.company_id)?.name)} | ${x.application_ids.length} | ${a?link(file('people.md'),path.join(root,a.path),'profile'):'—'} |`}));table('interactions',['ID','Kind','Application','Evidence state','Artifact'],m.interactions.map(x=>{const a=x.artifact_ids.map(id=>art.get(id)).find(Boolean);return`| ${cell(x.id)} | ${cell(x.kind)} | ${cell(x.application_id)} | ${cell(x.evidence_state)} | ${a?link(file('interactions.md'),path.join(root,a.path),'evidence'):'—'} |`}));table('artifacts',['ID','Kind','Owner','File','SHA-256'],m.artifacts.map(x=>`| ${cell(x.id)} | ${cell(x.kind)} | ${cell(`${x.owner_type}:${x.owner_id}`)} | ${link(file('artifacts.md'),path.join(root,x.path),path.basename(x.path))} | ${x.sha256.slice(0,12)} |`));return out}
function findings(issues){const lines=['# Relational Model Inconsistency Report','',`Total findings: ${issues.length}`,''];if(!issues.length)lines.push('No inconsistencies detected.');else for(const i of issues)lines.push(`- **${i.type}** — ${Object.entries(i).filter(([k])=>k!=='type').map(([k,v])=>`${k}: ${v}`).join('; ')}`);return`${lines.join('\n')}\n`}

export function buildReindexPlan(paths,{applicationId=null}={}){const root=paths.candidaturesDir,m=loadCanonical(root);validateModel(m,{allowIncomplete:true});if(applicationId)validateApplication(root,applicationId);const issues=canonicalIssues(m),generated=render(root,m);generated.set('reports/inconsistencies.md',findings(issues));const manifestFile=path.join(root,'records','manifest.json'),manifest=JSON.parse(fs.readFileSync(manifestFile,'utf8'));generated.set('records/manifest.json',json({...manifest,counts:counts(m)}));const relevant=applicationId?['indexes/index.md','indexes/companies.md','indexes/vacancies.md','indexes/applications.md','indexes/people.md','indexes/interactions.md','indexes/artifacts.md','reports/inconsistencies.md','records/manifest.json']:[...generated.keys()],selected=new Map(relevant.map(x=>[x,generated.get(x)])),sourceFiles=['applications','vacancies','companies','people','interactions','artifacts'].map(x=>path.join(root,'records',`${x}.json`)),sourceDigest=sha(sourceFiles.map(x=>`${path.basename(x)}\0${shaFile(x)}`).join('\n')),planDigest=sha(`canonical-reindex-v3\0${applicationId||'global'}\0${sourceDigest}\0${[...selected].map(([x,c])=>`${x}\0${sha(c)}`).join('\n')}`),changes=[...selected].filter(([x,c])=>!fs.existsSync(path.join(root,x))||fs.readFileSync(path.join(root,x),'utf8')!==c).map(([x])=>x);return{mode:'canonical-reindex',scope:applicationId?'application':'global_structure',applicationId,digest:planDigest,sourceDigest,generated:selected,changes,issues}}
export function applyReindexPlan(paths,plan,{expectDigest,deps={}}={}){if(plan.mode!=='canonical-reindex'||plan.digest!==expectDigest)fail('Approved digest does not match current reindex preview','DIGEST_MISMATCH');if(!plan.changes.length)return{status:'noop',digest:plan.digest,changes:0};const targets=plan.changes.map(x=>path.join(paths.candidaturesDir,x)),lease=(deps.acquireLocks||acquireVaultLocks)({vaultRoot:paths.vaultRoot,lockDir:paths.locksDir,targets,taskId:`reindex-${plan.digest.slice(0,12)}`,operation:'relational-reindex',runTool:deps.lockCommand});let primary;try{runVaultTransaction({paths,kind:'relational-reindex',context:{applicationId:plan.applicationId,targets:plan.changes},outputs:new Map(plan.changes.map(x=>[path.join(paths.candidaturesDir,x),plan.generated.get(x)])),lease,deps:deps.transaction});const validation=plan.applicationId?validateApplication(paths.candidaturesDir,plan.applicationId):validateStructure(paths.candidaturesDir);return{status:'reindexed',digest:plan.digest,changes:plan.changes.length,validation}}catch(e){primary=e;throw e}finally{lease.releaseAll({suppress:Boolean(primary)})}}
