import test from 'node:test'
import assert from 'node:assert/strict'
import crypto from 'node:crypto'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { executeRelationalCommand } from './commands.js'
import { auditChecksums, json, validateApplication, validateStructure } from './model.js'
import { applyReindexPlan, buildReindexPlan } from './reindex.js'
import { buildTransmissionBackfillPreview } from './backfill.js'

const hash=x=>crypto.createHash('sha256').update(x).digest('hex'),write=(f,c)=>{fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,c)},lease=()=>({assertSafe(){},releaseAll(){}})
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'nextstep-rel-')),cand=path.join(root,'Candidatures'),records=path.join(cand,'records'),folder=path.join(cand,'artifacts','applications','acme');const docs=[['artifact:cv-md','cv.md','# CV\n','cv','canonical_markdown',null],['artifact:cv-docx','cv.docx',Buffer.from('docx'),'cv','generated_docx','artifact:cv-md'],['artifact:letter','letter.md','# Letter\n','application_letter','canonical_markdown',null],['artifact:answer','answer.md','# Answer\n','application_answer','canonical_markdown',null],['artifact:message','message.md','# Message\n','outreach_message','canonical_markdown',null]];for(const[,name,c]of docs)write(path.join(folder,name),c);const by=new Map(docs.map(x=>[x[0],x])),artifacts=docs.map(([id,name,c,role,representation,source])=>({id,kind:role,owner_type:'application',owner_id:'application:acme',path:`artifacts/applications/acme/${name}`,original_path:`artifacts/applications/acme/${name}`,sha256:hash(c),size_bytes:Buffer.byteLength(c),media_type:name.endsWith('.md')?'text/markdown':'application/vnd.openxmlformats-officedocument.wordprocessingml.document',document:{role,representation,state:'final',version:1,primary:representation==='canonical_markdown',answer_key:role==='application_answer'?'why':null,source_artifact_id:source,source_sha256:source?hash(by.get(source)[2]):null}})),model={companies:[{id:'company:acme',name:'Acme',aliases:[],profile_artifact_ids:[],vacancy_ids:['vacancy:acme'],person_ids:['person:recruiter'],provenance:[]}],vacancies:[{id:'vacancy:acme',company_id:'company:acme',title:'Role',source_url:null,source_preservation:'snapshot_missing',vacancy_state:'active',snapshot_artifact_ids:[],application_ids:['application:acme'],provenance:[]}],applications:[{id:'application:acme',vacancy_id:'vacancy:acme',lifecycle_status:'to_apply',outcome:null,storage_scope:'active',record_state:'complete',people_relations:[{person_id:'person:recruiter',relationship_role:'recruiter_contact'}],interaction_ids:[],artifact_ids:artifacts.map(x=>x.id),created:'2026-08-28',updated:'2026-08-28',source_revision:0,provenance:[]}],people:[{id:'person:recruiter',name:'Recruiter',company_id:'company:acme',profile_artifact_ids:[],application_ids:['application:acme'],vacancy_ids:['vacancy:acme'],provenance:[]}],interactions:[],artifacts};for(const[k,v]of Object.entries(model))write(path.join(records,`${k}.json`),json(v));write(path.join(records,'manifest.json'),json({schema_version:1,counts:Object.fromEntries(Object.entries(model).map(([k,v])=>[k,v.length]))}));write(path.join(root,'.coordination','audit-log.md'),'# Audit Log\n');return{root,cand,records,paths:{vaultRoot:root,stateRoot:path.join(root,'.nextstep'),candidaturesDir:cand,recordsDir:records,locksDir:path.join(root,'.coordination','locks'),auditLogPath:path.join(root,'.coordination','audit-log.md')}}}
const cmd=(type,extra={})=>({schemaVersion:1,commandId:`cmd-${type}`,idempotencyKey:`idem-${type}`,expectedRevision:0,applicationId:'application:acme',type,payload:{occurredAt:'2026-08-28T12:00:00.000Z',channel:type.endsWith('Submission')?'portal':'linkedin',...extra}})
const run=(f,c,transaction={})=>executeRelationalCommand({paths:f.paths,command:c,now:new Date('2026-08-28T13:00:00.000Z'),deps:{acquireLocks:lease,transaction}})
const load=(f,n)=>JSON.parse(fs.readFileSync(path.join(f.records,`${n}.json`),'utf8'))

test('submission defaults freeze final Markdown sources and all applicable answers',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const r=run(f,cmd('application.recordSubmission')),i=load(f,'interactions').find(x=>x.id===r.interactionId);assert.equal(i.submission_bundle.selection_mode,'default_final');assert.deepEqual(i.submission_bundle.items.map(x=>x.role),['cv','application_letter','application_answer']);assert.equal(i.submission_bundle.items.every(x=>x.sha256&&x.transmitted_artifact_id===null),true);assert.deepEqual(validateApplication(f.cand,'application:acme').checked,{applications:1,interactions:1,artifacts:5})})
test('explicit exception freezes exact generated DOCX rendition',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));run(f,cmd('application.recordSubmission',{artifactIds:['artifact:cv-md','artifact:letter'],transmittedArtifactIds:['artifact:cv-docx']}));const b=load(f,'interactions')[0].submission_bundle;assert.equal(b.selection_mode,'explicit_override');assert.equal(b.items[0].transmitted_artifact_id,'artifact:cv-docx');assert.equal(b.items[0].transmitted_sha256,load(f,'artifacts')[1].sha256)})
test('outreach defaults to final Markdown message and registered contact',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));run(f,cmd('application.recordOutreach'));const i=load(f,'interactions')[0];assert.equal(i.transmission.message_artifact_id,'artifact:message');assert.deepEqual(i.person_ids,['person:recruiter'])})
test('idempotency, conflict, immutability, and absence of legacy structures',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const c=cmd('application.recordSubmission'),a=run(f,c);assert.deepEqual(run(f,c),a);const conflict=structuredClone(c);conflict.payload.channel='email';assert.throws(()=>run(f,conflict),e=>e.code==='IDEMPOTENCY_CONFLICT');write(path.join(f.cand,'artifacts','applications','acme','cv.md'),'changed');assert.throws(()=>run(f,c),e=>e.code==='FROZEN_ARTIFACT_CHANGED');assert.equal(fs.existsSync(path.join(f.cand,'applications')),false)})
test('journal transaction rolls back every output after a synthetic failure',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const before=fs.readFileSync(path.join(f.records,'applications.json'));assert.throws(()=>run(f,cmd('application.recordSubmission'),{afterStep(step){if(step==='target:1')throw new Error('synthetic')}}),/synthetic/);assert.deepEqual(fs.readFileSync(path.join(f.records,'applications.json')),before);assert.equal(load(f,'interactions').length,0)})
test('local validation stays scoped while global checksum audit remains explicit',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const unrelated=path.join(f.cand,'artifacts','shared.txt');write(unrelated,'x');const artifacts=load(f,'artifacts');artifacts.push({id:'artifact:shared',kind:'reference',owner_type:'shared',owner_id:null,path:'artifacts/shared.txt',sha256:'0'.repeat(64),size_bytes:1,media_type:'text/plain'});write(path.join(f.records,'artifacts.json'),json(artifacts));const manifest=JSON.parse(fs.readFileSync(path.join(f.records,'manifest.json')));manifest.counts.artifacts++;write(path.join(f.records,'manifest.json'),json(manifest));assert.equal(validateApplication(f.cand,'application:acme').checked.artifacts,5);assert.throws(()=>auditChecksums(f.cand),e=>e.code==='CHECKSUM_AUDIT_FAILED');assert.equal(validateStructure(f.cand).scope,'global_structure')})
test('reindex preview recalculates findings and apply is digest-bound and transactional',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const p=buildReindexPlan(f.paths,{applicationId:'application:acme'});assert.equal(p.scope,'application');assert.throws(()=>applyReindexPlan(f.paths,p,{expectDigest:'bad',deps:{acquireLocks:lease}}),e=>e.code==='DIGEST_MISMATCH');const r=applyReindexPlan(f.paths,p,{expectDigest:p.digest,deps:{acquireLocks:lease}});assert.equal(r.validation.scope,'application');assert.equal(fs.readFileSync(path.join(f.cand,'reports','inconsistencies.md'),'utf8').includes('Total findings: 0'),true)})
test('backfill preview is read-only and reports current-state changes without applying them',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const before=fs.readFileSync(path.join(f.records,'artifacts.json')),spec={schemaVersion:1,applicationId:'application:acme',artifactDocuments:[{artifactId:'artifact:cv-md',role:'cv',representation:'canonical_markdown',state:'final',version:2,primary:true}],submission:{interactionId:'interaction:submission',channel:'portal',artifactIds:['artifact:cv-md']},outreach:{interactionId:'interaction:outreach',channel:'linkedin',messageArtifactId:'artifact:message'}};const interactions=[{id:'interaction:submission',application_id:'application:acme',kind:'submission',artifact_ids:[]},{id:'interaction:outreach',application_id:'application:acme',kind:'outreach',artifact_ids:[]}];write(path.join(f.records,'interactions.json'),json(interactions));const apps=load(f,'applications');apps[0].interaction_ids=interactions.map(x=>x.id);write(path.join(f.records,'applications.json'),json(apps));const p=buildTransmissionBackfillPreview({paths:f.paths,spec});assert.equal(p.readOnly,true);assert.ok(p.changeCount>=3);assert.deepEqual(fs.readFileSync(path.join(f.records,'artifacts.json')),before)})
