import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import crypto from 'node:crypto'
import matter from 'gray-matter'
import { normalizeHarnessOutput, parseFinalPayload, createBackendDocuments, createApplicationArtifacts, applyExistingArtifacts, recoverApplicationTransactions, hashApplyKey, readApplyReceipt } from './artifacts.js'
import { recoverVaultTransactions } from '../vault/transactionJournal.js'
import { executeApplicationCommand } from '../vault/commands.js'
const wrap=x=>`prose\n<<<FINAL_JSON>>>${JSON.stringify(x)}<<<END_FINAL_JSON>>>\n`
const payload=(artifacts=[])=>({status:'completed',summary:'ok',artifacts,blockers:[],next_recommended_action:null})
test('strict parser accepts one delimited exact payload',()=>assert.equal(parseFinalPayload(wrap(payload([{artifact:'cv',content:'# CV'}])),'create-cv',{existingSlug:true}).artifacts[0].artifact,'cv'))
test('official Codex JSONL extracts only the final agent envelope',()=>{const envelope=`<<<FINAL_JSON>>>${JSON.stringify(payload([{artifact:'cv',content:'# CV'}]))}<<<END_FINAL_JSON>>>`,output=[{type:'thread.started',thread_id:'opaque'},{type:'item.completed',item:{id:'item_0',type:'reasoning',text:'ignored'}},{type:'item.completed',item:{id:'item_1',type:'agent_message',text:envelope}},{type:'turn.completed',usage:{input_tokens:1,output_tokens:1}}].map(JSON.stringify).join('\n');assert.equal(parseFinalPayload(normalizeHarnessOutput(output,'codex'),'create-cv',{existingSlug:true}).artifacts[0].content,'# CV')})
test('official Claude JSON extracts only the successful result envelope',()=>{const envelope=`<<<FINAL_JSON>>>${JSON.stringify(payload([{artifact:'cv',content:'# CV'}]))}<<<END_FINAL_JSON>>>`,output=JSON.stringify({type:'result',subtype:'success',is_error:false,result:envelope,session_id:'opaque',total_cost_usd:0});assert.equal(parseFinalPayload(normalizeHarnessOutput(output,'claude'),'create-cv',{existingSlug:true}).artifacts[0].content,'# CV')})
test('harness normalization rejects prose, paths and ambiguous structured results',()=>{const envelope=`<<<FINAL_JSON>>>${JSON.stringify(payload())}<<<END_FINAL_JSON>>>`;assert.throws(()=>normalizeHarnessOutput(JSON.stringify({type:'result',subtype:'success',is_error:false,result:`prose Candidatures/applications/acme/cv.md\n${envelope}`}),'claude'),/Invalid final payload/);assert.throws(()=>normalizeHarnessOutput([JSON.stringify({type:'item.completed',item:{type:'agent_message',text:envelope}}),JSON.stringify({type:'item.completed',item:{type:'agent_message',text:envelope}})].join('\n'),'codex'),/Invalid final payload/);assert.throws(()=>normalizeHarnessOutput(`not-json\n${JSON.stringify({type:'item.completed',item:{type:'agent_message',text:envelope}})}`,'codex'),/Invalid final payload/)})
for(const [name,text] of [['prose','hello'],['malformed','<<<FINAL_JSON>>>{x}<<<END_FINAL_JSON>>>'],['duplicate',wrap(payload())+wrap(payload())],['oversize','x'.repeat(513*1024)]])test(`parser rejects ${name}`,()=>assert.throws(()=>parseFinalPayload(text,'review-pipeline'),/Invalid final payload/))
test('rejects extra/control and prototype-pollution keys',()=>{assert.throws(()=>parseFinalPayload(wrap({...payload(),path:'x'}),'review-pipeline'),/forbidden key|top-level/);assert.throws(()=>parseFinalPayload('<<<FINAL_JSON>>>'+`{"status":"completed","summary":"ok","artifacts":[],"blockers":[],"next_recommended_action":null,"__proto__":{}}`+'<<<END_FINAL_JSON>>>','review-pipeline'),/forbidden key/);assert.throws(()=>parseFinalPayload(wrap({...payload(),summary:'x\u0000'}),'review-pipeline'),/summary/)})
test('per-action artifact allowlists are exact',()=>{assert.throws(()=>parseFinalPayload(wrap(payload([{artifact:'fitAnalysis',content:'x'}])),'position-analysis',{existingSlug:true}),/not allowed/);assert.doesNotThrow(()=>parseFinalPayload(wrap(payload([{artifact:'fitAnalysis',content:'x'}])),'generate-fit-analysis',{existingSlug:true}));assert.throws(()=>parseFinalPayload(wrap(payload([{artifact:'fitAnalysis',content:'x'}])),'position-analysis',{existingSlug:false}),/not allowed/);assert.doesNotThrow(()=>parseFinalPayload(wrap(payload([{artifact:'jobDescription',content:'x'},{artifact:'fitAnalysis',content:'y'}])),'create-application-analysis'));assert.throws(()=>parseFinalPayload(wrap(payload([{artifact:'cv',content:'x'}])),'interview-prep'),/not allowed/);assert.doesNotThrow(()=>parseFinalPayload(wrap(payload([])),'review-pipeline'))})
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'artifacts-')),apps=path.join(root,'Candidatures','applications'),coord=path.join(root,'.coordination');fs.mkdirSync(apps,{recursive:true});fs.mkdirSync(path.join(coord,'locks'),{recursive:true});fs.writeFileSync(path.join(root,'Candidatures','index.md'),'# Candidatures\n\n## Active Pipeline\n\n| Company | Role | Status | Priority | Main Risk | Workspace |\n|---|---|---:|---:|---|---|\n\n## Closed\n');fs.writeFileSync(path.join(apps,'index.md'),'# Applications\n\n## identified\n\n## applied\n');fs.writeFileSync(path.join(coord,'audit-log.md'),'# Audit\n');return{root,paths:{vaultRoot:root,applicationsDir:apps,archiveApplicationsDir:path.join(root,'archive'),candidaturesDir:path.join(root,'Candidatures'),locksDir:path.join(coord,'locks'),auditLogPath:path.join(coord,'audit-log.md')}}}
function fakeLocks(events=[]){let n=0;return(tool,args)=>{const command=args[0],artifact=args[args.indexOf('--artifact')+1];events.push(`${command}:${artifact}`);return command==='acquire'?{lock:{owner_token:`t${++n}`}}:{status:'released'}}}
const newPayload=payload([{artifact:'jobDescription',content:'# JD'},{artifact:'fitAnalysis',content:'# Fit'}])
test('backend documents have exact canonical machine-owned frontmatter',()=>{const actual=createBackendDocuments({slug:'acme-chief-ai',company:'Acme',role:'Chief AI',source:'https://example.test/job',now:new Date('2026-08-05T12:00:00Z')});assert.equal(actual.metadata,`---\nschema_version: 2\ntype: application\ncompany: Acme\nrole: Chief AI\nstatus: identified\napplication_revision: 0\nstorage_scope: active\npriority: medium\ncountry: null\nlocation: null\nlanguage_risk: null\ncreated: '2026-08-05'\nupdated: '2026-08-05'\njob_description: '[[job-description]]'\nfit_analysis: '[[fit-analysis]]'\ncv: '[[cv]]'\ncover_letter: '[[cover-letter]]'\ncompany_profile: '[[company-profile]]'\npeople: []\ntags:\n  - application\nsource: https://example.test/job\nsource_validation: partial\nreuse_state: partial\n---\n`);assert.equal(actual.index,`---\nschema_version: 2\ntype: application-index\napplication: acme-chief-ai\nstatus: identified\nstorage_scope: active\nupdated: '2026-08-05'\n---\n# Chief AI at Acme\n\n- Status: identified\n- [[job-description|Job description]]\n- [[fit-analysis|Fit analysis]]\n`)})
test('new application transaction writes governed files, indexes, audit and verified links',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const events=[],links=createApplicationArtifacts({paths:f.paths,slug:'acme-chief-ai',company:'Acme',role:'Chief AI',source:'https://example.test/job',payload:newPayload,deps:{lockCommand:fakeLocks(events)}});const folder=path.join(f.paths.applicationsDir,'acme-chief-ai');assert.match(fs.readFileSync(path.join(folder,'metadata.md'),'utf8'),/schema_version: 2[\s\S]*status: identified[\s\S]*source_validation: partial/);assert.equal(fs.readFileSync(path.join(folder,'job-description.md'),'utf8'),'# JD');assert.equal(links.length,2);assert.equal((fs.readFileSync(path.join(f.paths.candidaturesDir,'index.md'),'utf8').match(/acme-chief-ai/g)||[]).length,1);assert.equal((fs.readFileSync(path.join(f.paths.applicationsDir,'index.md'),'utf8').match(/acme-chief-ai/g)||[]).length,1);assert.match(fs.readFileSync(f.paths.auditLogPath,'utf8'),/create-application-analysis/);assert.deepEqual(events.filter(x=>x.startsWith('acquire:')).map(x=>x.slice(8)),[...events.filter(x=>x.startsWith('acquire:')).map(x=>x.slice(8))].sort());assert.equal(events.filter(x=>x.startsWith('release:')).length,8)})
test('model artifact bodies cannot control generated metadata or index frontmatter',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const hostile=payload([{artifact:'jobDescription',content:'---\nstatus: offer\n---\n# JD'},{artifact:'fitAnalysis',content:'---\ntype: attacker\n---\n# Fit'}]);createApplicationArtifacts({paths:f.paths,slug:'safe-record',company:'Safe',role:'Lead',payload:hostile,deps:{lockCommand:fakeLocks()}});assert.equal(matter(fs.readFileSync(path.join(f.paths.applicationsDir,'safe-record','metadata.md'),'utf8')).data.status,'identified');assert.equal(matter(fs.readFileSync(path.join(f.paths.applicationsDir,'safe-record','index.md'),'utf8')).data.type,'application-index')})
test('new application rejects duplicate and malformed indexes without mutation or leaked locks',t=>{for(const mutate of [()=>{},f=>fs.writeFileSync(path.join(f.paths.applicationsDir,'index.md'),'## identified\n## identified\n')]){const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const events=[];if(mutate.length)mutate(f);else fs.mkdirSync(path.join(f.paths.applicationsDir,'acme-chief-ai'));assert.throws(()=>createApplicationArtifacts({paths:f.paths,slug:'acme-chief-ai',company:'Acme',role:'Chief AI',payload:newPayload,deps:{lockCommand:fakeLocks(events)}}),/already exists|exactly one/);assert.equal(events.filter(x=>x.startsWith('acquire:')).length,events.filter(x=>x.startsWith('release:')).length)}})
test('startup recovery restores every injected crash state and committed cleanup is idempotent',t=>{for(const step of ['prepared','folder','candidatures','applications','audit','committed']){const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const before=[fs.readFileSync(path.join(f.paths.candidaturesDir,'index.md'),'utf8'),fs.readFileSync(path.join(f.paths.applicationsDir,'index.md'),'utf8'),fs.readFileSync(f.paths.auditLogPath,'utf8')],events=[];const crash=Object.assign(new Error(`crash ${step}`),{simulatedCrash:true});assert.throws(()=>createApplicationArtifacts({paths:f.paths,slug:'crash-app',company:'Acme',role:'Lead',payload:newPayload,deps:{lockCommand:fakeLocks(events),afterStep:s=>{if(s===step)throw crash}}}),/crash/);assert.equal(events.filter(x=>x.startsWith('acquire:')).length,events.filter(x=>x.startsWith('release:')).length);recoverApplicationTransactions({paths:f.paths});recoverApplicationTransactions({paths:f.paths});const exists=fs.existsSync(path.join(f.paths.applicationsDir,'crash-app'));assert.equal(exists,step==='committed');if(step==='committed')assert.match(fs.readFileSync(path.join(f.paths.candidaturesDir,'index.md'),'utf8'),/crash-app/);else assert.deepEqual([fs.readFileSync(path.join(f.paths.candidaturesDir,'index.md'),'utf8'),fs.readFileSync(path.join(f.paths.applicationsDir,'index.md'),'utf8'),fs.readFileSync(f.paths.auditLogPath,'utf8')],before)}})
test('fsync and rename failures roll back atomically and always release locks',t=>{for(const kind of ['fsync','rename']){const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const events=[],base=kind==='fsync'?fs.fsyncSync:fs.renameSync;let calls=0;const io=kind==='fsync'?{fsyncSync(fd){if(++calls===3)throw Object.assign(new Error('fsync failure'),{code:'EIO'});return base(fd)}}:{renameSync(a,b){if(++calls===2)throw Object.assign(new Error('rename failure'),{code:'EIO'});return base(a,b)}};assert.throws(()=>createApplicationArtifacts({paths:f.paths,slug:`${kind}-app`,company:'Acme',role:'Lead',payload:newPayload,deps:{io,lockCommand:fakeLocks(events)}}),/failure/);assert.equal(events.filter(x=>x.startsWith('acquire:')).length,events.filter(x=>x.startsWith('release:')).length);assert.equal(fs.existsSync(path.join(f.paths.applicationsDir,`${kind}-app`)),false);assert.doesNotMatch(fs.readFileSync(path.join(f.paths.candidaturesDir,'index.md'),'utf8'),new RegExp(`${kind}-app`))}})
test('recovery rejects path traversal or forged journal identity',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const root=path.join(f.root,'.nextstep','transactions','application-artifacts');fs.mkdirSync(root,{recursive:true});fs.writeFileSync(path.join(root,'evil.json'),JSON.stringify({version:1,id:'00000000-0000-4000-8000-000000000000',slug:'../escape',state:'prepared'}));assert.throws(()=>recoverApplicationTransactions({paths:f.paths}),/Unsafe/)})
test('existing missing artifact is created atomically and audited',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const folder=path.join(f.paths.applicationsDir,'existing');fs.mkdirSync(folder);fs.writeFileSync(path.join(folder,'metadata.md'),'---\nstatus: identified\n---\n');const links=applyExistingArtifacts({paths:f.paths,slug:'existing',payload:payload([{artifact:'cv',content:'# CV'}]),deps:{lockCommand:fakeLocks()}});assert.equal(fs.readFileSync(path.join(folder,'cv.md'),'utf8'),'# CV');assert.equal(links[0].path,'Candidatures/applications/existing/cv.md');assert.match(fs.readFileSync(f.paths.auditLogPath,'utf8'),/artifact-apply/)})
test('existing apply locks the full target set before staged payload read and writes a durable idempotent receipt',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const slug='receipt-app',folder=path.join(f.paths.applicationsDir,slug);fs.mkdirSync(folder);fs.writeFileSync(path.join(folder,'metadata.md'),'---\nstatus: identified\napplication_revision: 0\n---\n');const events=[],runId='00000000-0000-4000-8000-000000000001',context={runId,keyHash:hashApplyKey('key-one'),stageDigest:'a'.repeat(64),expectedRevision:0,actionId:'create-cv',application:{slug,scope:'active'}},payloadReader=()=>{assert.equal(events.filter(x=>x.startsWith('acquire:')).length,5);assert.equal(events.some(x=>x.startsWith('release:')),false);return payload([{artifact:'cv',content:'# CV'}])};const applied=applyExistingArtifacts({paths:f.paths,slug,artifactNames:['cv'],payloadReader,expectedRevision:0,applyContext:context,deps:{lockCommand:fakeLocks(events)}});assert.equal(applied.resultingRevision,1);assert.equal(readApplyReceipt(f.paths,runId).keyHash,context.keyHash);const retried=applyExistingArtifacts({paths:f.paths,slug,artifactNames:['cv'],payloadReader:()=>{throw new Error('stage must not be reread')},expectedRevision:0,applyContext:context,deps:{lockCommand:fakeLocks()}});assert.equal(retried.idempotent,true);assert.throws(()=>applyExistingArtifacts({paths:f.paths,slug,artifactNames:['cv'],payloadReader,expectedRevision:0,applyContext:{...context,keyHash:hashApplyKey('different')},deps:{lockCommand:fakeLocks()}}),e=>e.statusCode===409)})

test('concurrent command revision makes a staged apply stale with zero artifact writes',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const slug='stale-app',folder=path.join(f.paths.applicationsDir,slug);fs.mkdirSync(folder);fs.writeFileSync(path.join(folder,'metadata.md'),'---\nstatus: identified\napplication_revision: 0\n---\n');executeApplicationCommand({paths:f.paths,slug,scope:'active',command:{schemaVersion:1,commandId:'concurrent',idempotencyKey:'concurrent',expectedRevision:0,type:'application.setPriority',payload:{priority:'high'}}});const context={runId:'00000000-0000-4000-8000-000000000002',keyHash:hashApplyKey('key'),stageDigest:'b'.repeat(64),expectedRevision:0,actionId:'create-cv',application:{slug,scope:'active'}};assert.throws(()=>applyExistingArtifacts({paths:f.paths,slug,artifactNames:['cv'],payloadReader:()=>payload([{artifact:'cv',content:'# stale'}]),expectedRevision:0,applyContext:context}),e=>e.statusCode===412);assert.equal(fs.existsSync(path.join(folder,'cv.md')),false);assert.equal(readApplyReceipt(f.paths,context.runId),null)})

test('artifact apply crash boundaries recover to entirely old or entirely new state',t=>{for(const step of ['prepared','target:0','target:2','committed']){const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const slug=`crash-${step.replace(':','-')}`,folder=path.join(f.paths.applicationsDir,slug);fs.mkdirSync(folder);fs.writeFileSync(path.join(folder,'metadata.md'),'---\nstatus: identified\napplication_revision: 0\n---\n');const context={runId:crypto.randomUUID(),keyHash:hashApplyKey('key'),stageDigest:'c'.repeat(64),expectedRevision:0,actionId:'create-cv',application:{slug,scope:'active'}},crash=Object.assign(new Error(`crash ${step}`),{simulatedCrash:true});assert.throws(()=>applyExistingArtifacts({paths:f.paths,slug,artifactNames:['cv'],payloadReader:()=>payload([{artifact:'cv',content:'# new'}]),expectedRevision:0,applyContext:context,deps:{afterStep:s=>{if(s===step)throw crash}}}),/crash/);recoverVaultTransactions({paths:f.paths});recoverVaultTransactions({paths:f.paths});const committed=step==='committed';assert.equal(fs.existsSync(path.join(folder,'cv.md')),committed);assert.equal(readApplyReceipt(f.paths,context.runId)!==null,committed);assert.equal(Number(matter(fs.readFileSync(path.join(folder,'metadata.md'),'utf8')).data.application_revision||0),committed?1:0)}})

test('returned artifact links are exact allowlisted existing contained files',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const links=createApplicationArtifacts({paths:f.paths,slug:'safe-app',company:'Safe',role:'Role',payload:newPayload,deps:{lockCommand:fakeLocks()}});assert.deepEqual(links.map(x=>x.path).sort(),['Candidatures/applications/safe-app/fit-analysis.md','Candidatures/applications/safe-app/job-description.md']);for(const item of links){const absolute=path.resolve(f.root,item.path);assert.equal(path.relative(f.paths.applicationsDir,absolute).startsWith('..'),false);assert.equal(fs.existsSync(absolute),true);assert.ok(['jobDescription','fitAnalysis'].includes(item.artifact));assert.match(item.url,/^\/api\/vault\/documents\/active\/safe-app\/(jobDescription|fitAnalysis)$/)}assert.throws(()=>createApplicationArtifacts({paths:f.paths,slug:'..-escape',company:'X',role:'Y',payload:newPayload,deps:{lockCommand:fakeLocks()}}),/Invalid application slug/)})
