import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'

const ID=/^[0-9a-f-]{36}$/i
const STATES=new Set(['draft','queued','generating','generated','validating','awaiting_apply','applying','completed','failed','timed_out','cancel_requested','cancellation_failed','cancelled','interrupted','expired'])
const TERMINAL=new Set(['completed','failed','timed_out','cancelled','interrupted','expired','awaiting_apply'])
const safeText=(value,max=1000)=>String(value??'').replace(/[\u0000-\u001f\u007f]/g,' ').replace(/(?:[A-Za-z]:\\|\/[\w.-]+\/)[^\s]*/g,'[redacted-path]').slice(0,max)
function syncDir(directory){let fd;try{fd=fs.openSync(directory,'r');fs.fsyncSync(fd)}catch(error){if(!['EPERM','EINVAL'].includes(error.code))throw error}finally{if(fd!==undefined)fs.closeSync(fd)}}
function renameWithRetry(from,to){for(let attempt=0;;attempt++){try{return fs.renameSync(from,to)}catch(error){if(!['EPERM','EBUSY'].includes(error.code)||attempt>=5)throw error;Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,10*(attempt+1))}}}
function atomic(file,value){const temp=`${file}.tmp-${process.pid}-${crypto.randomUUID()}`;fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(temp,JSON.stringify(value,null,2),{mode:0o600,flag:'wx'});const fd=fs.openSync(temp,'r+');try{fs.fsyncSync(fd)}finally{fs.closeSync(fd)}renameWithRetry(temp,file);syncDir(path.dirname(file))}
export class RunStore{
 constructor(root,{maxEvents=200}={}){this.root=path.resolve(root);this.maxEvents=maxEvents;fs.mkdirSync(this.root,{recursive:true,mode:0o700})}
 file(id){if(!ID.test(id||''))throw Object.assign(new Error('Invalid run ID'),{statusCode:400});return path.join(this.root,`${id}.json`)}
 stageFile(id){return path.join(this.root,`${id}.stage`)}
 create(run){const clean={...run,id:run.id||crypto.randomUUID(),events:[],attempt:run.attempt||1};this.save(clean);return clean}
 save(run){if(!STATES.has(run.state))throw new Error('Invalid run state');const allowed={id:run.id,actionId:run.actionId,application:run.application||null,harnessId:run.harnessId,state:run.state,phase:run.phase||run.state,createdAt:run.createdAt,startedAt:run.startedAt||null,finishedAt:run.finishedAt||null,updatedAt:new Date().toISOString(),attempt:run.attempt||1,input:run.input||null,generationRevision:run.generationRevision??null,resultingRevision:run.resultingRevision??null,applyKeyHash:run.applyKeyHash||null,applyIntent:run.applyIntent||null,result:run.result||null,expectedWrites:run.expectedWrites||[],stagedArtifacts:run.stagedArtifacts||[],stageDigest:run.stageDigest||null,stageExpiresAt:run.stageExpiresAt||null,artifactLinks:run.artifactLinks||[],errorCode:run.errorCode||null,failureReason:run.failureReason?safeText(run.failureReason,500):null,retryable:Boolean(run.retryable),events:(run.events||[]).slice(-this.maxEvents)};atomic(this.file(run.id),allowed);return allowed}
 rawGet(id){try{return JSON.parse(fs.readFileSync(this.file(id),'utf8'))}catch(e){if(e.code==='ENOENT')return null;throw e}}
 get(id){const run=this.rawGet(id);return run?.state==='awaiting_apply'?this.reconcileStage(run):run}
 reconcileStage(run,now=Date.now()){let code=null,state='interrupted';try{const envelope=JSON.parse(fs.readFileSync(this.stageFile(run.id),'utf8')),actual=crypto.createHash('sha256').update(JSON.stringify(envelope.artifacts)).digest('hex');if(Date.parse(envelope.expiresAt)<=now){code='STAGE_EXPIRED';state='expired'}else if(envelope.digest!==actual||run.stageDigest!==actual)code='STAGE_MISSING'}catch{code='STAGE_MISSING'}if(!code)return run;fs.rmSync(this.stageFile(run.id),{force:true});run.state=state;run.phase=state;run.errorCode=code;run.retryable=true;run.finishedAt=new Date().toISOString();return this.event(run,state,code)}
 list(application){return fs.readdirSync(this.root).filter(x=>x.endsWith('.json')).map(x=>{try{return JSON.parse(fs.readFileSync(path.join(this.root,x),'utf8'))}catch{return null}}).filter(x=>x&&(!application||x.application?.slug===application)).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))}
 event(run,type,detail=''){const last=run.events?.at(-1)?.id||0;run.events=[...(run.events||[]),{id:last+1,type,at:new Date().toISOString(),detail:safeText(detail,500)}].slice(-this.maxEvents);return this.save(run)}
 stage(id,artifacts){const data=JSON.stringify(artifacts.map(x=>({artifact:x.artifact,content:String(x.content)}))),digest=crypto.createHash('sha256').update(data).digest('hex'),expiresAt=new Date(Date.now()+24*60*60*1000).toISOString();atomic(this.stageFile(id),{digest,expiresAt,artifacts:JSON.parse(data)});return {digest,expiresAt,metadata:artifacts.map(x=>({artifact:x.artifact,bytes:Buffer.byteLength(x.content),digest:crypto.createHash('sha256').update(x.content).digest('hex')}))}}
 readStage(id,expectedDigest){let envelope;try{envelope=JSON.parse(fs.readFileSync(this.stageFile(id),'utf8'))}catch(error){throw Object.assign(new Error('Staged artifacts are unavailable'),{statusCode:409,code:'STAGE_MISSING',cause:error})}const actual=crypto.createHash('sha256').update(JSON.stringify(envelope.artifacts)).digest('hex');if(envelope.digest!==actual||expectedDigest!==actual)throw Object.assign(new Error('Staged artifacts failed integrity validation'),{statusCode:409,code:'STAGE_MISSING'});if(Date.parse(envelope.expiresAt)<=Date.now())throw Object.assign(new Error('Staged artifacts expired'),{statusCode:410,code:'STAGE_EXPIRED'});return envelope.artifacts}
 eraseStage(id){fs.rmSync(this.stageFile(id),{force:true});syncDir(this.root)}
 cleanupStages(now=Date.now()){for(const run of this.list())if(run.state==='awaiting_apply')this.reconcileStage(run,now);for(const name of fs.readdirSync(this.root)){if(!name.endsWith('.stage'))continue;const id=name.slice(0,-6),run=this.rawGet(id);if(!run||!['awaiting_apply','applying'].includes(run.state))fs.rmSync(path.join(this.root,name),{force:true})}}
 recover({receiptReader=()=>null}={}){this.cleanupStages();for(const run of this.list()){if(run.state==='generating'||run.state==='validating'||run.state==='cancel_requested'||run.state==='cancellation_failed'){run.state='interrupted';run.phase='interrupted';run.retryable=true;run.errorCode='SERVER_RESTART';run.finishedAt=new Date().toISOString();this.event(run,'interrupted','Run interrupted by server restart')}else if(run.state==='applying'){const receipt=receiptReader(run.id);if(receipt){const intent=run.applyIntent;if(!intent||receipt.keyHash!==intent.keyHash||receipt.intentDigest!==intent.intentDigest||receipt.stageDigest!==intent.stageDigest||receipt.expectedRevision!==intent.expectedRevision||receipt.actionId!==intent.actionId||receipt.application?.slug!==intent.application?.slug||receipt.application?.scope!==intent.application?.scope)throw new Error('Durable apply receipt does not match applying run');run.state='completed';run.phase='completed';run.applyKeyHash=receipt.keyHash;run.resultingRevision=receipt.resultingRevision;run.artifactLinks=receipt.artifactLinks;run.errorCode=null;run.finishedAt=receipt.committedAt||new Date().toISOString();this.event(run,'apply_recovered','Committed apply recovered from durable receipt');this.eraseStage(run.id)}else{run.state='awaiting_apply';run.phase='awaiting_apply';run.retryable=false;run.errorCode='APPLY_INTERRUPTED';run.finishedAt=null;this.event(run,'apply_recovered','Interrupted apply rolled back and can be retried idempotently');this.reconcileStage(run)} }else if(run.state==='queued'){run.retryable=true;this.save(run)}}}
 public(run){const copy={...run};delete copy.events;return copy}
 events(id,after=0){return (this.get(id)?.events||[]).filter(e=>e.id>after)}
}
export { STATES, TERMINAL }
