import { useEffect, useRef, useState } from 'react'
import { api } from '../api/client.js'
import { buildCommandPayload, narratives } from '../quickUpdateModel.js'

const priorities=[['very_high','Very high'],['high','High'],['medium','Medium'],['low','Low'],['none','Not set']]
const responseTypes=['acknowledged','rejected','screening','interview','offer','other']
const interviewTypes=['recruiter','hiring_manager','technical','panel','case','executive','other']
export default function QuickUpdatePanel({app,scope,onReload}){
 const panel=useRef(null),pendingFocus=useRef(null)
 const [kind,setKind]=useState('application.setPriority'),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[fieldErrors,setFieldErrors]=useState({})
 useEffect(()=>{const node=panel.current;const focus=e=>{pendingFocus.current=e.detail;if(e.detail===kind)requestAnimationFrame(()=>node?.querySelector(`[data-command="${CSS.escape(e.detail)}"] input, [data-command="${CSS.escape(e.detail)}"] select, [data-command="${CSS.escape(e.detail)}"] textarea`)?.focus());else setKind(e.detail)};node?.addEventListener('quick-update-focus',focus);return()=>node?.removeEventListener('quick-update-focus',focus)},[kind])
 useEffect(()=>{if(pendingFocus.current===kind){panel.current?.querySelector(`[data-command="${CSS.escape(kind)}"] input, [data-command="${CSS.escape(kind)}"] select, [data-command="${CSS.escape(kind)}"] textarea`)?.focus();pendingFocus.current=null}},[kind])
 useEffect(()=>{const form=panel.current?.querySelector('form');if(!form)return;form.querySelectorAll('[aria-invalid="true"]').forEach(node=>{node.removeAttribute('aria-invalid');node.removeAttribute('aria-describedby')});for(const name of Object.keys(fieldErrors)){const node=form.elements.namedItem(name);if(node instanceof HTMLElement){node.setAttribute('aria-invalid','true');node.setAttribute('aria-describedby',`quick-error-${name}`)}}},[fieldErrors,kind])
 const submit=async e=>{e.preventDefault();if(busy)return;const form=e.currentTarget,values=Object.fromEntries(new FormData(form));if(values.lifecycleTarget&&!window.confirm('This update also changes lifecycle status. Continue?'))return
  let payload;try{payload=buildCommandPayload(kind,values)}catch(err){setError(err.message);return}setBusy(true);setMessage('Saving update…');setError('');setFieldErrors({});const id=crypto.randomUUID();try{await api.commandApplication(app.slug,scope,{schemaVersion:1,commandId:id,idempotencyKey:id,expectedRevision:app.revision||0,type:kind,payload});setMessage('Update saved.');await onReload()}catch(err){setMessage('');if(err.status===412){setError('This application changed elsewhere. The latest version was reloaded; review the fields and retry.');await onReload()}else if(err.status===409)setError('This update conflicts with another operation. Reload and retry when it finishes.')
   else if(err.status===422){setError('Check the highlighted fields and try again.');setFieldErrors(err.fields||{});requestAnimationFrame(()=>{const first=Object.keys(err.fields||{})[0];if(first)panel.current?.querySelector(`[name="${CSS.escape(first)}"]`)?.focus()})}else setError(err.message)}finally{setBusy(false)}}
 const repairing=kind==='application.repairRecord',readOnly=(app.lifecycle?.terminal||scope==='archive')&&!repairing,field=(name)=>fieldErrors[name]?<small id={`quick-error-${name}`} className="document-error">{fieldErrors[name]}</small>:null
 const allowedTransitions=app.lifecycle?.allowedTransitions||[]
 return <article ref={panel} className="card quick-update" id="quick-update"><p className="eyebrow">Quick update</p><h2>Update application details</h2>{readOnly?<p className="protection-note">Closed, archived, and legacy applications are read-only. Reopen to update details.</p>:<form onSubmit={submit}><label>Update type<select value={kind} onChange={e=>{setKind(e.target.value);setMessage('');setError('');setFieldErrors({})}}><option value="application.setPriority">Priority</option><option value="application.setLocation">Country and location</option><option value="application.setSource">Job source</option><option value="application.recordReuseAssessment">Company and people review</option><option value="application.selectDominantNarrative">Dominant narrative</option><option value="application.recordSubmission">Submission</option><option value="application.recordEmployerResponse">Employer response</option><option value="application.recordInterview">Interview</option><option value="application.addNote">Activity note</option>{(!app.metadataExists||!app.artifacts?.index)&&<option value="application.repairRecord">Repair missing metadata/index</option>}</select></label>
 <div data-command={kind}>
 {kind==='application.setPriority'&&<label>Priority<select name="priority" defaultValue={app.priority||'none'} required>{priorities.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
 {kind==='application.setLocation'&&<><label>Country<input name="country" maxLength="100" defaultValue={app.country||''}/>{field('country')}</label><label>Location<input name="location" maxLength="200" defaultValue={app.location||''}/>{field('location')}</label></>}
 {kind==='application.setSource'&&<><label>Source URL<input name="url" type="url" defaultValue={app.jobSource?.startsWith('http')?app.jobSource:''}/>{field('url')}</label><label>Or source reference<input name="reference" maxLength="500"/></label></>}
 {kind==='application.selectDominantNarrative'&&<label>Narrative<select name="narrative" defaultValue={app.dominantNarrative||narratives[0]} required>{narratives.map(n=><option key={n}>{n}</option>)}</select></label>}
 {kind==='application.recordReuseAssessment'&&<label>Review confirmation note<textarea name="note" maxLength="2000"/></label>}
 {kind==='application.recordSubmission'&&<><label>Submission date<input name="occurredAt" type="date"/></label><label>Channel<input name="channel" required maxLength="100"/></label><label>Note<textarea name="note" maxLength="2000"/></label></>}
 {kind==='application.recordEmployerResponse'&&<><label>Response type<select name="responseType" required>{responseTypes.map(x=><option key={x}>{x}</option>)}</select></label><label>Response date<input name="occurredAt" type="date" required/></label><label>Note<textarea name="note" maxLength="2000"/></label><LifecycleSelect allowed={allowedTransitions}/></>}
 {kind==='application.recordInterview'&&<><label>Interview date<input name="occurredAt" type="date" required/></label><label>Interview type<select name="interviewType" required>{interviewTypes.map(x=><option key={x}>{x}</option>)}</select></label><label>Outcome<input name="outcome" maxLength="200"/></label><label>Note<textarea name="note" maxLength="2000"/></label><LifecycleSelect allowed={allowedTransitions}/></>}
 {kind==='application.addNote'&&<label>Note<textarea name="note" required maxLength="4000" aria-describedby={fieldErrors.note?'quick-error-note':undefined}/>{field('note')}</label>}
 {kind==='application.repairRecord'&&<><label>Missing record<select name="target" defaultValue={!app.metadataExists?'metadata':'index'}><option value="metadata">metadata.md</option><option value="index">index.md</option></select></label><p className="protection-note">The existing counterpart will be validated. No dates or claims will be invented.</p></>}</div><button className="button button--primary" disabled={busy}>{busy?'Saving…':'Save update'}</button></form>}<p aria-live="polite">{message}</p>{error&&<p role="alert" className="document-error">{error}</p>}</article>
}
function LifecycleSelect({allowed=[]}){return <details><summary>Also change lifecycle status</summary><label>New lifecycle status<select name="lifecycleTarget" defaultValue=""><option value="">No lifecycle change</option>{allowed.map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></label><p className="muted">Only transitions allowed by the current server record are shown. You will be asked to confirm.</p></details>}
