#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import { fileURLToPath } from 'node:url'
import matter from 'gray-matter'
import { acquireVaultLocks, canonicalLockManifest, canonicalVaultIdentity } from '../vault/lockAdapter.js'
import { canonicalizeApplicationMetadata, canonicalizeApplicationIndex, serializeApplicationMetadata, serializeApplicationIndex } from '../vault/applicationRecordSchema.js'
import { findApplicationIndexRows, updateApplicationIndexLifecycle } from '../vault/indexLifecycle.js'
import { durableAtomicWrite } from '../vault/transactionJournal.js'

const MIGRATION='normalize-records-v2'
const REASONS=new Set(['missing_metadata','canonical_metadata','missing_index','canonical_local_index','canonical_global_index'])
const hash=v=>crypto.createHash('sha256').update(v).digest('hex')
const stable=v=>Array.isArray(v)?v.map(stable):v&&typeof v==='object'?Object.fromEntries(Object.keys(v).sort().map(k=>[k,stable(v[k])])):v
function fail(message,code='MIGRATION_PROVENANCE_INVALID',context={}){throw Object.assign(new Error(message),{code,...context})}
function pathsFor(root){root=path.resolve(root);const state=path.resolve(process.env.NEXTSTEP_STATE_ROOT||path.join(root,'.nextstep'));return{root,active:path.join(root,'Candidatures','applications'),archive:path.join(root,'Candidatures','archive','applications'),activeIndex:path.join(root,'Candidatures','applications','index.md'),archiveIndex:path.join(root,'Candidatures','archive','applications','index.md'),state:path.join(state,'migrations','normalize-records'),audit:path.join(root,'.coordination','audit-log.md')}}
const body=raw=>matter(raw).content
function migration(data){const current=data.migration&&typeof data.migration==='object'?data.migration:{};return{...current,name:MIGRATION,normalizations:[...(Array.isArray(current.normalizations)?current.normalizations:[])]}}
function normalized(data,field,from,to,source,rule){const m=migration(data);m.normalizations.push({field,from:from??null,to,source,rule});return{...data,migration:m}}
function artifacts(folder,data){const names={job_description:'job-description.md',fit_analysis:'fit-analysis.md',cv:'cv.md',cover_letter:'cover-letter.md',company_profile:'company-profile.md'},out={...data};for(const [key,name] of Object.entries(names))out[key]=fs.existsSync(path.join(folder,name))?`[[${name.slice(0,-3)}]]`:null;return out}
function legacyRole(folder,slug,data){if(typeof data.role==='string'&&data.role.trim())return data;if(slug!=='argenx')fail('Blank role has no unique authoritative source','MIGRATION_PROVENANCE_INVALID',{reason:'invalid_role'});const dir=path.join(folder,'legacy-files');const exact='Job Specification - argenx BV., Global Lead Enterprise Platforms & Delivery.pdf';const files=fs.existsSync(dir)?fs.readdirSync(dir).filter(n=>/^Job Specification - .*\.pdf$/.test(n)):[];if(files.length!==1||files[0]!==exact)fail('Blank role has no unique authoritative source','MIGRATION_PROVENANCE_INVALID',{reason:'invalid_role'});return normalized({...data,role:'Global Lead Enterprise Platforms & Delivery'},'role',data.role,'Global Lead Enterprise Platforms & Delivery',path.relative(folder,path.join(dir,exact)).replaceAll('\\','/'),'exact sole job-spec filename: Job Specification - <company>, <role>.pdf')}
function legacyMappings(folder,slug,scope,input){let data={...input};if(data.type==='archived-application'){data={...data,legacy_type:data.type,type:'application'};data=normalized(data,'type','archived-application','application','metadata/index frontmatter','explicit legacy type mapping')}if(data.priority==='medium_high'){data={...data,priority:'high'};data=normalized(data,'priority','medium_high','high','metadata/index frontmatter','explicit legacy priority mapping: medium_high -> high')}else if(['archive','closed',''].includes(data.priority)){const from=data.priority;data={...data,priority:'none'};data=normalized(data,'priority',from,'none','metadata/index frontmatter','explicit legacy priority mapping')}data=legacyRole(folder,slug,data);if(scope==='archive'&&(data.status==null||data.status==='')){data={...data,status:'archived'};data=normalized(data,'status',input.status,'archived','physical archive scope','missing status in physical archive')}return data}
function appliedEvidence(folder,data){if(data.status!=='applied'||data.submission?.occurred_at!==undefined)return data;const notes=path.join(folder,'submission-notes.md'),candidates=[];if(fs.existsSync(notes)){const raw=fs.readFileSync(notes,'utf8'),parsed=matter(raw);for(const field of ['submitted','applied']){const value=parsed.data[field] instanceof Date?parsed.data[field].toISOString().slice(0,10):String(parsed.data[field]??'');if(/^\d{4}-\d{2}-\d{2}$/.test(value))candidates.push({date:value,field:`frontmatter.${field}`})}for(const re of [/^\s*-\s*\*\*Date:\*\*\s*(\d{4}-\d{2}-\d{2})\s*[.]?\s*$/gmi,/^\s*Applied on (\d{4}-\d{2}-\d{2})[.]?\s*$/gmi]){let m;while((m=re.exec(parsed.content)))candidates.push({date:m[1],field:`submission-notes.md:${raw.slice(0,m.index).split('\n').length}`})}}const dates=[...new Set(candidates.map(x=>x.date))];if(dates.length>1)fail('Conflicting authoritative submission dates','MIGRATION_PROVENANCE_INVALID',{reason:'conflicting_authoritative_submission_dates'});return{...data,submission:{confirmed:true,occurred_at:dates[0]||null,date_precision:dates.length?'day':'unknown',provenance:{source:dates.length?'submission-notes.md':'legacy metadata status',fields:candidates.map(x=>x.field),migration:MIGRATION}}}}
function canonicalRecord(folder,slug,scope,metadataRaw,indexRaw){if(metadataRaw==null&&indexRaw==null)fail('Missing metadata and local index','MIGRATION_PROVENANCE_INVALID',{reason:'missing_record_provenance'});const source=(metadataRaw!=null?matter(metadataRaw):matter(indexRaw)).data;let seed=legacyMappings(folder,slug,scope,artifacts(folder,{...source,application_revision:source.application_revision??0,storage_scope:scope}));seed=appliedEvidence(folder,seed);delete seed.schema_version;delete seed.application;if(seed.type==='application')delete seed.type;return canonicalizeApplicationMetadata(seed,{company:typeof source.company==='string'?source.company.trim():source.company,role:seed.role,status:seed.status,scope})}
function change(p,scope,slug,file,before,after,reason){if(before===after)return null;return{scope,slug,path:path.relative(p.root,file).replaceAll('\\','/'),before,after,reason}}
function normalizeGlobal(raw,slug,status,label){const found=findApplicationIndexRows(raw,slug);if(found.indexes.length>1)fail(`${label} has duplicate application rows`,'MIGRATION_PROVENANCE_INVALID',{reason:'duplicate_global_rows'});if(!found.indexes.length){const eol=raw.includes('\r\n')?'\r\n':'\n';return raw+(raw&&!raw.endsWith('\n')?eol:'')+`- [[${slug}/index|${slug}]] — ${status};${eol}`}try{return updateApplicationIndexLifecycle(raw,slug,status,label)}catch(e){const i=found.indexes[0],line=found.lines[i],link=[...line.matchAll(/\[\[[^\]]+\]\]/g)].find(m=>m[0].includes(slug)),tail=link&&line.slice(link.index+link[0].length),legacy=tail&&tail.match(/^(\s+—\s+)([^;\r\n]+)(;[^\r\n]*)(\r?\n)?$/);if(!legacy)throw e;found.lines[i]=line.slice(0,link.index+link[0].length)+legacy[1]+status+legacy[3]+(legacy[4]||'');return found.lines.join('')}}
export function buildNormalizationPlan({vaultRoot}){const p=pathsFor(vaultRoot),changes=[],records=[],unresolved=[];for(const [scope,base,indexFile] of [['active',p.active,p.activeIndex],['archive',p.archive,p.archiveIndex]]){if(!fs.existsSync(base))continue;for(const slug of fs.readdirSync(base).sort()){const folder=path.join(base,slug);if(!fs.statSync(folder).isDirectory())continue;try{const mf=path.join(folder,'metadata.md'),xf=path.join(folder,'index.md'),mr=fs.existsSync(mf)?fs.readFileSync(mf,'utf8'):null,xr=fs.existsSync(xf)?fs.readFileSync(xf,'utf8'):null,canonical=canonicalRecord(folder,slug,scope,mr,xr),ma=serializeApplicationMetadata(canonical)+body(mr||'');const mc=change(p,scope,slug,mf,mr,ma,mr==null?'missing_metadata':'canonical_metadata');if(mc)changes.push(mc);let ix=xr?{...matter(xr).data}:{};delete ix.schema_version;delete ix.type;const ic=canonicalizeApplicationIndex(ix,{application:slug,status:canonical.status,scope,date:canonical.updated}),ia=serializeApplicationIndex(ic,body(xr||'')),xc=change(p,scope,slug,xf,xr,ia,xr==null?'missing_index':'canonical_local_index');if(xc)changes.push(xc);records.push({scope,slug,status:canonical.status,indexFile})}catch(e){unresolved.push({scope,slug,reason:e.reason||`invalid_${e.field||'provenance'}`})}}}if(unresolved.length)fail(`${unresolved.length} application record(s) have no deterministic mapping`,'MIGRATION_PROVENANCE_INVALID',{unresolved});for(const [scope,indexFile] of [['active',p.activeIndex],['archive',p.archiveIndex]]){let raw=fs.existsSync(indexFile)?fs.readFileSync(indexFile,'utf8'):'';const before=raw;for(const r of records.filter(x=>x.scope===scope))raw=normalizeGlobal(raw,r.slug,r.status,`${scope} application index`);const c=change(p,scope,null,indexFile,before,raw,'canonical_global_index');if(c)changes.push(c)}const publicChanges=changes.map(({before,after,...x})=>({...x,beforeHash:before==null?null:hash(before),afterHash:hash(after)})),reasonCounts={};for(const c of publicChanges)reasonCounts[c.reason]=(reasonCounts[c.reason]||0)+1;const publicPlan={migration:MIGRATION,changes:publicChanges,summary:{changeCount:changes.length,reasonCounts,unresolved:[]}};return{...publicPlan,vaultRoot:p.root,changes,digest:hash(JSON.stringify(stable(publicPlan)))}}
function canonical(root,file){try{return canonicalVaultIdentity(root,file)}catch{fail('Unsafe migration target','MIGRATION_RECOVERY_INVALID')}}
function expectedRule(p,x){if(x.kind==='audit'&&x.scope==null&&x.slug==null&&x.reason==null)return canonical(p.root,p.audit);if(x.kind==='global_index'&&['active','archive'].includes(x.scope)&&x.slug==null&&x.reason==='canonical_global_index')return canonical(p.root,x.scope==='active'?p.activeIndex:p.archiveIndex);if(['metadata','local_index'].includes(x.kind)&&['active','archive'].includes(x.scope)&&/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(x.slug||'')&&REASONS.has(x.reason)){const metadata=x.kind==='metadata';if(metadata&&!['missing_metadata','canonical_metadata'].includes(x.reason))return null;if(!metadata&&!['missing_index','canonical_local_index'].includes(x.reason))return null;return canonical(p.root,path.join(x.scope==='active'?p.active:p.archive,x.slug,metadata?'metadata.md':'index.md'))}return null}
function candidates(p){const out=[p.audit,p.activeIndex,p.archiveIndex];for(const base of [p.active,p.archive])if(fs.existsSync(base))for(const slug of fs.readdirSync(base).sort()){const f=path.join(base,slug);if(fs.statSync(f).isDirectory())for(const n of fs.readdirSync(f).sort())out.push(path.join(f,n))}return out}
export function recoverNormalization({vaultRoot,deps={},skipLocks=false}){const p=pathsFor(vaultRoot);if(!fs.existsSync(p.state))return;for(const n of fs.readdirSync(p.state).sort()){if(!/^[0-9a-f-]{36}\.journal$/i.test(n))fail('Unsafe migration journal name','MIGRATION_RECOVERY_INVALID');const jf=path.join(p.state,n);let j;try{j=JSON.parse(fs.readFileSync(jf))}catch{fail('Unsafe migration journal','MIGRATION_RECOVERY_INVALID')}if(j.version!==3||j.migration!==MIGRATION||!Array.isArray(j.manifest)||!Array.isArray(j.preimages)||JSON.stringify(j.manifest)!==JSON.stringify(j.preimages.map(x=>x.path))||new Set(j.manifest).size!==j.manifest.length)fail('Unsafe migration journal','MIGRATION_RECOVERY_INVALID');for(const x of j.preimages)if(Object.keys(x).sort().join(',')!=='data,existed,kind,path,reason,scope,slug'||x.path!==expectedRule(p,x)||typeof x.existed!=='boolean'||typeof x.data!=='string')fail('Unsafe migration journal rule','MIGRATION_RECOVERY_INVALID');const lease=skipLocks?null:acquireVaultLocks({vaultRoot:p.root,lockDir:path.join(p.root,'.coordination','locks'),targets:j.manifest,agent:'normalize-records',taskId:'recovery'});let error;try{for(const x of [...j.preimages].reverse()){const f=path.join(p.root,x.path);if(x.existed)durableAtomicWrite(fs,f,Buffer.from(x.data,'base64'));else fs.rmSync(f,{force:true})}fs.rmSync(jf)}catch(e){error=e;throw e}finally{lease?.releaseAll({suppress:!!error})}}}
export function runNormalization({vaultRoot,apply=false,expectDigest,deps={}}){const p=pathsFor(vaultRoot);if(!apply){const plan=buildNormalizationPlan({vaultRoot});return{...plan,changes:plan.changes.map(({before,after,...x})=>({...x,beforeHash:before==null?null:hash(before),afterHash:hash(after)})),mode:'dry-run'}}if(!/^[0-9a-f]{64}$/.test(expectDigest||''))fail('--expect-digest is required for apply','MIGRATION_DIGEST_REQUIRED');recoverNormalization({vaultRoot,deps});const lease=acquireVaultLocks({vaultRoot:p.root,lockDir:path.join(p.root,'.coordination','locks'),targets:candidates(p),agent:'normalize-records',taskId:'normalize-records-apply',operation:'migration-apply',runTool:deps.lockCommand});let error;try{const plan=buildNormalizationPlan({vaultRoot});if(plan.digest!==expectDigest)fail('Approved migration digest does not match locked plan','MIGRATION_DIGEST_MISMATCH');if(!plan.changes.length)return{migration:MIGRATION,mode:'apply',digest:plan.digest,summary:{...plan.summary,applied:0}};const rules=new Map(plan.changes.map(c=>[canonical(p.root,path.join(p.root,c.path)),c])),manifest=canonicalLockManifest(p.root,[...plan.changes.map(c=>path.join(p.root,c.path)),p.audit]),preimages=manifest.map(x=>{const f=path.join(p.root,x),r=rules.get(x),kind=r?(r.reason==='canonical_global_index'?'global_index':r.path.endsWith('/metadata.md')?'metadata':'local_index'):'audit';return{path:x,kind,scope:r?.scope??null,slug:r?.slug??null,reason:r?.reason??null,existed:fs.existsSync(f),data:fs.existsSync(f)?fs.readFileSync(f).toString('base64'):''}});fs.mkdirSync(p.state,{recursive:true});const journal=path.join(p.state,crypto.randomUUID()+'.journal');durableAtomicWrite(fs,journal,JSON.stringify({version:3,migration:MIGRATION,manifest,preimages}));for(const c of plan.changes){const f=path.join(p.root,c.path);durableAtomicWrite(fs,f,c.after);lease.heartbeatAll();deps.afterWrite?.(c.path)}const old=fs.existsSync(p.audit)?fs.readFileSync(p.audit,'utf8'):'';durableAtomicWrite(fs,p.audit,old+`\n- migration ${MIGRATION} | changes ${plan.summary.changeCount} | reasons ${JSON.stringify(plan.summary.reasonCounts)} | digest ${plan.digest}\n`);deps.afterAudit?.();fs.rmSync(journal);fs.rmSync(p.state,{recursive:true,force:true});return{migration:MIGRATION,mode:'apply',digest:plan.digest,summary:{...plan.summary,applied:plan.changes.length}}}catch(e){error=e;if(!e.simulatedCrash)recoverNormalization({vaultRoot,deps,skipLocks:true});throw e}finally{lease.releaseAll({suppress:!!error})}}
function cli(){const a=process.argv.slice(2),allowed=new Set(['--apply','--dry-run','--vault-root','--expect-digest']);for(let i=0;i<a.length;i++){if(!allowed.has(a[i]))fail('Usage','MIGRATION_USAGE');if(['--vault-root','--expect-digest'].includes(a[i]))i++}const apply=a.includes('--apply'),dry=a.includes('--dry-run'),ri=a.indexOf('--vault-root'),di=a.indexOf('--expect-digest');if(apply===dry||ri<0||!a[ri+1]||(apply&&(di<0||!a[di+1])))fail('Usage','MIGRATION_USAGE');console.log(JSON.stringify(runNormalization({vaultRoot:path.resolve(a[ri+1]),apply,expectDigest:di<0?undefined:a[di+1]}),null,2))}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){try{cli()}catch(e){const o={error:'Migration failed',code:e.code||'MIGRATION_FAILED'};if(Array.isArray(e.unresolved))o.unresolved=e.unresolved;for(const k of ['scope','slug','reason'])if(e[k]!=null)o[k]=e[k];process.stderr.write(JSON.stringify(o)+'\n');process.exitCode=1}}
