import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawnSync } from 'node:child_process'
import matter from 'gray-matter'
import { buildNormalizationPlan, recoverNormalization, runNormalization } from './normalize-records.js'

function vault(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'normalize-'));fs.mkdirSync(path.join(root,'Candidatures','applications'),{recursive:true});fs.mkdirSync(path.join(root,'Candidatures','archive','applications'),{recursive:true});return root}
function app(root,base,slug,metadata,index=null){const d=path.join(root,'Candidatures',base,'applications',slug);fs.mkdirSync(d,{recursive:true});if(metadata!=null)fs.writeFileSync(path.join(d,'metadata.md'),metadata);if(index!=null)fs.writeFileSync(path.join(d,'index.md'),index);return d}
const meta=(overrides='')=>`---\ntype: application\ncompany: Acme\nrole: Role\nstatus: identified\n${overrides}---\nNarrative stays.\n`
const local=(eol='\n',body='Body\n')=>`---${eol}type: application${eol}status: identified${eol}---${eol}${body}`

test('schema-v2 canonicalizes metadata, local index, and global row with reason counts',()=>{const r=vault();app(r,'','acme-role',meta('priority: closed\n'),local());fs.writeFileSync(path.join(r,'Candidatures','applications','index.md'),'- [[acme-role/index|Acme]] — lead; keep\n');const plan=buildNormalizationPlan({vaultRoot:r});assert.deepEqual(plan.summary.reasonCounts,{canonical_metadata:1,canonical_local_index:1,canonical_global_index:1});const md=matter(plan.changes.find(x=>x.reason==='canonical_metadata').after).data;assert.equal(md.schema_version,2);assert.equal(md.priority,'none');assert.equal(md.migration.normalizations[0].from,'closed');assert.match(plan.changes.find(x=>x.reason==='canonical_global_index').after,/— identified; keep/)})
test('global row grammar preserves unrelated trailing body and CRLF',()=>{const r=vault();app(r,'','acme-role',meta(),local('\r\n','Body\r\nTail\r\n'));const global='Header\r\n- [[acme-role/index|Acme]] — lead; note\r\nFooter\r\n';fs.writeFileSync(path.join(r,'Candidatures','applications','index.md'),global);const plan=buildNormalizationPlan({vaultRoot:r});const ix=plan.changes.find(x=>x.reason==='canonical_local_index').after;assert.ok(ix.endsWith('Body\r\nTail\r\n'));const g=plan.changes.find(x=>x.reason==='canonical_global_index').after;assert.equal(g,'Header\r\n- [[acme-role/index|Acme]] — identified; note\r\nFooter\r\n')})
test('nullable unknown fields and applied date precision remain explicit',()=>{const r=vault();const d=app(r,'','acme-role',meta('country: ""\n').replace('status: identified','status: applied'));fs.writeFileSync(path.join(d,'submission-notes.md'),'No authoritative date.\n');const md=matter(buildNormalizationPlan({vaultRoot:r}).changes.find(x=>x.reason==='canonical_metadata').after).data;assert.equal(md.country,null);assert.equal(md.submission.occurred_at,null);assert.equal(md.submission.date_precision,'unknown')})
test('legacy Argenx mapping derives exact sole filename and records provenance',()=>{const r=vault(),d=app(r,'archive','argenx',`---\ntype: archived-application\ncompany: ' argenx BV. '\nrole: ''\nstatus: ''\npriority: archive\n---\nStory\n`);const legacy=path.join(d,'legacy-files');fs.mkdirSync(legacy);fs.writeFileSync(path.join(legacy,'Job Specification - argenx BV., Global Lead Enterprise Platforms & Delivery.pdf'),'pdf');const md=matter(buildNormalizationPlan({vaultRoot:r}).changes.find(x=>x.reason==='canonical_metadata').after).data;assert.equal(md.type,'application');assert.equal(md.legacy_type,'archived-application');assert.equal(md.company,'argenx BV.');assert.equal(md.role,'Global Lead Enterprise Platforms & Delivery');assert.equal(md.status,'archived');assert.equal(md.priority,'none');assert.deepEqual(md.migration.normalizations.map(x=>x.field),['type','priority','role','status']);assert.match(md.migration.normalizations[2].source,/legacy-files\//)})
test('medium_high maps to high for all three archived record shapes with provenance',()=>{const r=vault();app(r,'archive','datashift-data-ai-strategy-senior-manager',meta('priority: medium_high\ncountry: Belgium\n'));app(r,'archive','ooredoo-data-governance-associate-director',meta('priority: medium_high\nsource: JD.docx\n'),local());app(r,'archive','telenet-b2b-delivery-services-excellence',meta('priority: medium_high\ntags: [application, b2b]\n'),null);const plan=buildNormalizationPlan({vaultRoot:r});for(const slug of ['datashift-data-ai-strategy-senior-manager','ooredoo-data-governance-associate-director','telenet-b2b-delivery-services-excellence']){const md=matter(plan.changes.find(x=>x.slug===slug&&x.reason==='canonical_metadata').after).data;assert.equal(md.priority,'high');const provenance=md.migration.normalizations.find(x=>x.field==='priority');assert.deepEqual({from:provenance.from,to:provenance.to,rule:provenance.rule},{from:'medium_high',to:'high',rule:'explicit legacy priority mapping: medium_high -> high'})}})
test('aggregate inventory reports every arbitrary unknown role and priority safely',()=>{const r=vault();app(r,'','bad-role',meta().replace('role: Role','role: ""'));app(r,'','bad-priority',meta('priority: urgent\n'));assert.throws(()=>buildNormalizationPlan({vaultRoot:r}),e=>{assert.equal(e.code,'MIGRATION_PROVENANCE_INVALID');assert.deepEqual(e.unresolved,[{scope:'active',slug:'bad-priority',reason:'invalid_priority'},{scope:'active',slug:'bad-role',reason:'invalid_role'}]);return true});const script=fileURLToPath(new URL('./normalize-records.js',import.meta.url)),result=spawnSync(process.execPath,[script,'--dry-run','--vault-root',r],{encoding:'utf8'});assert.equal(result.status,1);assert.deepEqual(JSON.parse(result.stderr).unresolved,[{scope:'active',slug:'bad-priority',reason:'invalid_priority'},{scope:'active',slug:'bad-role',reason:'invalid_role'}]);assert.equal(result.stderr.includes(r),false)})
test('digest mismatch, rollback/recovery, and idempotent zero',()=>{const r=vault(),d=app(r,'','acme-role',meta(),local()),plan=buildNormalizationPlan({vaultRoot:r});assert.throws(()=>runNormalization({vaultRoot:r,apply:true,expectDigest:'0'.repeat(64)}),e=>e.code==='MIGRATION_DIGEST_MISMATCH');const before=fs.readFileSync(path.join(d,'metadata.md'),'utf8');assert.throws(()=>runNormalization({vaultRoot:r,apply:true,expectDigest:plan.digest,deps:{afterWrite(){throw new Error('crash')}}}),/crash/);assert.equal(fs.readFileSync(path.join(d,'metadata.md'),'utf8'),before);runNormalization({vaultRoot:r,apply:true,expectDigest:buildNormalizationPlan({vaultRoot:r}).digest});assert.equal(buildNormalizationPlan({vaultRoot:r}).summary.changeCount,0)})
test('recovery accepts exact new kinds and rejects forged extras',()=>{const r=vault(),state=path.join(r,'.nextstep','migrations','normalize-records');fs.mkdirSync(state,{recursive:true});const target='Candidatures/applications/index.md';fs.writeFileSync(path.join(r,target),'changed');const journal={version:3,migration:'normalize-records-v2',manifest:[target],preimages:[{path:target,kind:'global_index',scope:'active',slug:null,reason:'canonical_global_index',existed:true,data:Buffer.from('before').toString('base64')}]};fs.writeFileSync(path.join(state,'00000000-0000-4000-8000-000000000000.journal'),JSON.stringify(journal));recoverNormalization({vaultRoot:r,skipLocks:true});assert.equal(fs.readFileSync(path.join(r,target),'utf8'),'before');fs.mkdirSync(state,{recursive:true});journal.preimages[0].extra='forged';fs.writeFileSync(path.join(state,'00000000-0000-4000-8000-000000000001.journal'),JSON.stringify(journal));assert.throws(()=>recoverNormalization({vaultRoot:r,skipLocks:true}),e=>e.code==='MIGRATION_RECOVERY_INVALID')})
